table hg19
"Panel App Genes with color and attributes"
(
string  chrom;                  "Reference sequence chromosome or scaffold"
uint    chromStart;             "Start position of feature on chromosome"
uint    chromEnd;               "End position of feature on chromosome"
string  name;                   "Name of gene"
uint    score;                  "Score"
char[1] strand;                 "+ or - for strand"
uint    thickStart;             "Coding region start"
uint    thickEnd;               "Coding region end"
uint    itemRgb;                "Color based on confidence level"
string  blockCount;             "Number of gene entry"
string  blockSizes;             "Size of gene"
string  blockStarts;            "Block begins at first chromStart"
string  geneSymbol;             "Gene Symbol"
string  biotype;                "Biotype"
string  hgncID;                 "hgnc ID"
string  geneName;               "Gene Name"
string  omimGene;               "Reference to OMIM Gene"
string  ensemblGenes;           "Ensembl Gene ID"
string  entityType;             "Entity Type"
string  entityName;             "Entity Name"
string  confidenceLevel;        "Confidence Level"
string  penetrance;             "Penetrance"
string  modeOfPanthogenicity;   "Mode of Pathogenicity"
lstring publications;           "Publications"
lstring evidence;               "Evidence"
lstring phenotypes;             "Phenotypes"
string  modeOfInheritance;      "Mode of Inheritance"
string  tags;                   "Tags"
string  panelID;                "Panel ID"
string  panelName;              "Panel Name"
string  diseaseGroup;           "Disease Group"
string  diseaseSubgroup;        "Disease Subgroup"
string  status;                 "Status"
string  panelVersion;           "Panel Version"
string  versionCreated;         "Date of Creation"
lstring relevantDisorders;      "Relevant Disorders"
lstring	mouseOverField;		"Mouse over field displaying gene symbol, Inheritance, Phenotypes, Confidence Level"
)
