table hg38
"Panel App STR with color and attributes"
(
string  chrom;                  "Reference sequence chromosome or scaffold"
uint    chromStart;             "Start position of feature on chromosome"
uint    chromEnd;               "End position of feature on chromosome"
string  name;                   "Name of gene"
uint    score;                  "Score"
char[1] strand;                 "+ or - for strand"
uint    thickStart;             "Coding region start"
uint    thickEnd;               "Coding region end"
uint    itemRgb;                "Color based on confidence level"
string  blockCount;             "Number of gene entry"
string  blockSizes;             "Size of gene"
string  blockStarts;            "Block begins at first chromStart"
string	geneSymbol;				"Gene Symbol"
string	confidenceLevel;		"Confidence Level"		
string	entityType;				"Entity Type"
string	evidence;				"Evidence"
string	alias;					"Alias"
string	ensemblID;				"Ensembl ID"
string	geneName;				"Gene Name"
string	hgncID;					"hgnc Id"
string	hgncSymbol;				"hgnc Symbol"
string	omimGene;				"Reference to OMIM Gene"
string	modeOfInheritance;		"Mode of Inheritance"
string	normalRepeats;			"Normal Repeats"
string	diseaseGroup;			"Disease Group"
string	diseaseSubgroup;		"Disease Subgroup"
string	panelID;				"Panel ID"
string	panelName;				"Panel Name"
lstring	relevantDisorders;		"Relevant Disorders"
string	numberOfGene;			"Number Of Genes"
string	numberOfRegions;		"Number Of Regions"
string	numberOfStrs;			"Number Of STRs"
lstring	description;			"Description"
string	version;				"Version"
string	versionCreated;			"Version Created"
string	pathogenicRepeats;		"Pathogenic Repeats"
string	penetrance;				"Penetrance"
string	phenotypes;				"Phenotypes"
string	publications;			"Publications"
string	repeatedSequence;		"Repeated Sequence"
)
