#!/bin/tcsh
# we want to use autoSql to make the .sql 
# which is handy for initializing empty tables
# but we do not need the .c and .h files at this time.
foreach f ( *.as )
    echo $f
    autoSql $f $f:r
    rm $f:r.c
    rm $f:r.h
end
