table meiEul1db
"euL1db: curated L1-HS retrotransposon insertion polymorphisms (Mir et al. 2015)"
(
string  chrom;            "Reference chromosome"
uint    chromStart;       "0-based start of MRIP region"
uint    chromEnd;         "Half-open end of MRIP region"
string  name;             "MRIP accession (mripN)"
uint    score;            "Score (pseudo-allele-frequency * 1000)"
char[1] strand;           "Strand"
uint    thickStart;       "Start of thick drawing region"
uint    thickEnd;         "End of thick drawing region"
uint    itemRgb;          "RGB color, by lineage (germline/somatic/mixed)"
float   pseudoAlleleFreq; "Pseudo-allele frequency|Aggregated frequency reported by euL1db"
int     sripCount;        "Sample observations (SRIPs)|Number of sample-level SRIP entries merged into this MRIP"
int     sampleCount;      "Distinct samples|Number of unique samples contributing"
int     individualCount;  "Distinct individuals|Number of unique individuals contributing"
int     studyCount;       "Distinct studies|Number of studies reporting this insertion"
string  subGroups;        "L1HS sub-group(s)|Comma-separated set (L1-Ta, L1-pre-Ta, L1-Hybrid, unknown)"
string  integrity;        "Integrity|Comma-separated set (full-length, 5prime-truncated, unknown)"
string  lineage;          "Lineage|germline, somatic, or both"
string  pcrValidated;     "PCR validated|yes if any contributing SRIP has PCR evidence"
string  gene;             "Overlapping gene|Reported in euL1db MRIP table"
string  inReferenceL1HS;  "In reference L1HS|yes if euL1db marks this MRIP as present in reference"
string  warning;          "Warning|euL1db curation warning, if any"
lstring studies;          "Study list|Comma-separated study IDs"
lstring pmids;            "PubMed IDs|Comma-separated PMIDs"
lstring methods;          "Detection methods|Comma-separated method names"
lstring tissues;          "Tissues|Comma-separated unique tissues"
lstring diseases;         "Clinical conditions|Comma-separated unique disease/clinical states"
lstring populations;      "Populations|Comma-separated unique populations"
lstring sampleTable;      "Contributing samples|HTML table (sample, individual, study, lineage, integrity, subgroup, PCR)"
)
