table meiHgsvc3
"Novel Mobile Element Insertions in 65 HGSVC3 long-read assembled samples (vs GRCh38)"
(
string  chrom;             "Reference chromosome or scaffold"
uint    chromStart;        "0-based start position (anchor base)"
uint    chromEnd;           "Half-open end position (anchor base + 1)"
string  name;              "Item label (INS, insertion length, carrier sample count)"
uint    score;             "Score (alt-allele frequency * 1000)"
char[1] strand;            "Strand (always .)"
uint    thickStart;        "Start of thick drawing region"
uint    thickEnd;          "End of thick drawing region"
uint    itemRgb;           "RGB color, by mobile-element class"
string  teClass;           "TE class|Family of mobile element (Alu, L1, SVA, HERVK, snRNA)"
string  teType;            "Repeat designation|Repeat designation as reported in source (e.g. SINE/Alu)"
int     svLen;             "Insertion length (bp)"
int     altAlleleCount;    "Carrier haplotypes|Haplotypes carrying the insertion"
int     alleleNumber;      "Genotyped haplotypes|Total haplotypes successfully genotyped"
float   altAlleleFreq;     "Allele frequency|Fraction of genotyped haplotypes carrying the insertion"
int     carrierCount;      "Carrier samples|Samples with at least one insertion allele"
int     sampleCount;       "Genotyped samples|Samples with at least one called haplotype"
string  sourceSample;      "Discovery sample|Sample-haplotype in which the insertion was originally called"
int     callerCount;       "Caller count|Number of MEI callers supporting this insertion (1 or 2)"
string  l1meAid;           "L1ME-AID validated|Whether the insertion was validated by L1ME-AID (Yes/No)"
string  palmer;            "PALMER validated|Whether the insertion was validated by PALMER (Yes/No)"
float   refSegDup;         "Segmental dup. overlap|Fraction of insertion site overlapping reference segmental duplications (REF_SD)"
string  refTrf;            "Tandem repeat|Insertion site overlaps a reference tandem repeat (REF_TRF)"
lstring carrierSamples;    "Carrier sample list|Comma-separated list of samples with at least one insertion allele"
lstring insertSeq;         "Inserted sequence|DNA sequence of the inserted mobile element (ALT allele minus the anchor base)"
)
