table meiHmeid
"Mobile Element Insertions in 5,675 genomes (HMEID v1.1 / NyuWa + 1KGP, GRCh38)"
(
string  chrom;             "Reference chromosome or scaffold"
uint    chromStart;        "0-based start position (anchor base)"
uint    chromEnd;          "Half-open end position (anchor base + 1)"
string  name;              "Item label (INS, MEI class, carrier allele count)"
uint    score;             "Score (alt-allele frequency * 1000)"
char[1] strand;            "Strand (always .)"
uint    thickStart;        "Start of thick drawing region"
uint    thickEnd;          "End of thick drawing region"
uint    itemRgb;           "RGB color, by mobile-element class"
string  teClass;           "TE class|Family of mobile element (Alu, L1, SVA, HERVK)"
int     svLen;             "Insertion length (bp), -1 if unknown"
string  tsd;               "Target site duplication|TSD sequence reported by MELT, '.' if unknown"
int     assess;            "MELT ASSESS score|0=no overlapping reads, 1=imprecise, 2=discordant pairs only, 3=left-side TSD only, 4=right-side TSD only, 5=TSD decided with split reads (highest quality)"
int     altAlleleCount;    "Carrier haplotypes (all)|Haplotypes carrying the insertion across all 5,675 samples"
int     alleleNumber;      "Genotyped haplotypes (all)|Total haplotypes successfully genotyped"
float   altAlleleFreq;     "Allele frequency (all)|Alt-allele frequency across all 5,675 samples"
int     nyuwaAC;           "NyuWa AC|Alt-allele count in NyuWa (Chinese) cohort"
int     nyuwaAN;           "NyuWa AN|Genotyped haplotypes in NyuWa cohort"
float   nyuwaAF;           "NyuWa AF|Alt-allele frequency in NyuWa (Chinese) cohort"
int     kgpAC;             "1KGP AC|Alt-allele count in 1000 Genomes cohort"
int     kgpAN;             "1KGP AN|Genotyped haplotypes in 1000 Genomes cohort"
float   kgpAF;             "1KGP AF|Alt-allele frequency in 1000 Genomes cohort"
int     afrAC;             "AFR AC|Alt-allele count in 1KGP African super-population"
int     afrAN;             "AFR AN|Genotyped haplotypes in AFR"
float   afrAF;             "AFR AF|Alt-allele frequency in AFR"
int     amrAC;             "AMR AC|Alt-allele count in 1KGP Admixed American super-population"
int     amrAN;             "AMR AN|Genotyped haplotypes in AMR"
float   amrAF;             "AMR AF|Alt-allele frequency in AMR"
int     easAC;             "EAS AC|Alt-allele count in East Asian super-population (1KGP only)"
int     easAN;             "EAS AN|Genotyped haplotypes in EAS (1KGP only)"
float   easAF;             "EAS AF|Alt-allele frequency in EAS (1KGP only)"
int     eurAC;             "EUR AC|Alt-allele count in 1KGP European super-population"
int     eurAN;             "EUR AN|Genotyped haplotypes in EUR"
float   eurAF;             "EUR AF|Alt-allele frequency in EUR"
int     sasAC;             "SAS AC|Alt-allele count in 1KGP South Asian super-population"
int     sasAN;             "SAS AN|Genotyped haplotypes in SAS"
float   sasAF;             "SAS AF|Alt-allele frequency in SAS"
)
