all:
	cd bptForTwoBit && ${MAKE}
	cd bptLookupStringToBits64 && ${MAKE}
	cd bptMakeStringToBits64 && ${MAKE}
	cd indexfa && ${MAKE}
	cd indexgl && ${MAKE}
	cd ixali && ${MAKE}
	cd ixIxx && ${MAKE}
	cd ixword1 && ${MAKE}
	cd ixword3 && ${MAKE}
	cd makepgo && ${MAKE}
	cd stToXao && ${MAKE}
	cd trixContextIndex && ${MAKE}
	cd trixSearch && ${MAKE}

clean::
	cd bptForTwoBit && ${MAKE} clean
	cd bptLookupStringToBits64 && ${MAKE} clean
	cd bptMakeStringToBits64 && ${MAKE} clean
	cd indexfa && ${MAKE} clean
	cd indexgl && ${MAKE} clean
	cd ixali && ${MAKE} clean
	cd ixIxx && ${MAKE} clean
	cd ixword1 && ${MAKE} clean
	cd ixword3 && ${MAKE} clean
	cd makepgo && ${MAKE} clean
	cd stToXao && ${MAKE} clean
	cd trixContextIndex && ${MAKE} clean
	cd trixSearch && ${MAKE} clean
