all:
	cd bptForTwoBit && ${MAKE}
	cd bptLookupStringToBits64 && ${MAKE}
	cd bptMakeStringToBits64 && ${MAKE}
	cd indexfa && ${MAKE}
	cd indexgl && ${MAKE}
	cd ixali && ${MAKE}
	cd ixword1 && ${MAKE}
	cd ixword3 && ${MAKE}
	cd makepgo && ${MAKE}
	cd stToXao && ${MAKE}
	cd ixIxx && ${MAKE}
	cd trixSearch && ${MAKE}

clean::
