#!/bin/bash -e
gfServer=${1:-gfServer}   # first arg is optional name of gfServer program
testName=$(basename $0)

# build index
gfIdx=output/$testName.gfidx
rm -f $gfIdx
mkdir -p output
$gfServer index $gfIdx input/creaGeno.2bit >/dev/null

# read index
$gfServer start -indexFile=$gfIdx localhost 17768 -canStop input/creaGeno.2bit >/dev/null &
sleep 1
$gfServer query localhost 17768 input/mCrea.mrna > output/$testName.out
$gfServer stop localhost 17768 > /dev/null
diff -u expected/$testName.out output/$testName.out
