#!/bin/bash -e
gfServer pcrDirect CCTGAAGGCATCAGTGTACCCCAGGAATGCCCAA CTCATGAGTGGCTCCTAAAGCAGCTGCGTGG input/testPcr.2bit | grep -v seconds > output/testPcr.out
gfServer pcrDirect tggtgagagggggaaggtttt ggagctctgacatctgggttctg input/testPcr.2bit | grep -v seconds >> output/testPcr.out
gfServer pcrDirect GGAGCTCTGACATCTGGGTTCTGGA tggtgagagggggaaggttttcttt input/testPcr.2bit | grep -v seconds >> output/testPcr.out
diff -u expected/testPcr.out output/testPcr.out
