#!/bin/bash -e

# build index
gfIdx=output/creaGeno.trans.gfidx
rm -f $gfIdx
mkdir -p output
gfServer index -trans $gfIdx input/creaGeno.2bit >/dev/null

# read index
gfServer start -trans -indexFile=$gfIdx localhost 17768 -canStop input/creaGeno.2bit >/dev/null &
sleep 1
gfServer transQuery localhost 17768 input/mCrea.mrna > output/testIndexFileTrans.out
gfServer stop localhost 17768 > /dev/null
diff -u expected/testIndexFileTrans.out output/testIndexFileTrans.out
