#!/bin/bash
gfServer start -trans localhost 17768 -canStop input/mCreaGeno.nib input/hCreaGeno.nib > /dev/null 2>&1 &
sleep 1
gfServer protQuery localhost 17768 input/mCrea.pep > output/testProtNib.out
gfServer stop localhost 17768 > /dev/null
diff -u expected/testProtNib.out output/testProtNib.out
