#!/bin/bash -e

testName=$(basename $0)

# build index
gfRootDir=output/${testName}_root
gfDir=${gfRootDir}/extra/stuff/crea
rm -rf $gfDir
mkdir -p $gfDir
cp -f input/creaGeno.2bit $gfDir/crea.2bit
gfServer index $gfDir/crea.untrans.gfidx $gfDir/crea.2bit >/dev/null

# test query

./dynTester ${gfRootDir} query crea extra/stuff/crea input/crea.mrna output/${testName}.ver.out
sed -e 's/^version .*$/version XXX/' output/${testName}.ver.out > output/${testName}.out
diff -u expected/${testName}.out output/${testName}.out
