#!/bin/bash -e

testName=$(basename $0)

# build index
gfRootDir=output/${testName}_root
gfDir=${gfRootDir}/crea
rm -rf $gfDir
mkdir -p $gfDir
cp -f input/creaGeno.2bit $gfDir/crea.2bit
gfServer index -trans $gfDir/crea.trans.gfidx $gfDir/crea.2bit >/dev/null

# test query

./dynTester $gfRootDir transQuery crea crea input/crea.mrna output/${testName}.ver.out
sed -e 's/^version .*$/version XXX/' output/${testName}.ver.out > output/${testName}.out
diff -u expected/${testName}.out output/${testName}.out
