#!/bin/tcsh -efx
autoSql encodeDataWarehouse.as encodeDataWarehouse -dbLink -defaultZeros
rm ../*/*.o
pushd .
cd ..
make
popd
mv encodeDataWarehouse.h ../inc
cat encodeDataWarehouse.sql | sed 's/id int unsigned default 0/id int unsigned auto_increment/' > tmp.sql
mv tmp.sql encodeDataWarehouse.sql
./resetEdw
