#!/bin/tcsh -x

# Relaunch edwRunDaemons.  Send them initial wake up message
set subFifo = /usr/local/apache/userdata/edwSubmit.fifo
set qaFifo = /usr/local/apache/userdata/edwQaAgent.fifo
killall edwRunDaemon
edwRunDaemon encodeDataWarehouse edwSubmitJob 4 $subFifo -log=edwSubmit.log
echo hi > $subFifo
edwRunDaemon encodeDataWarehouse edwJob 4 $qaFifo -log=edwQaAgent.log
echo hi > $qaFifo

