#!/bin/tcsh
set sql = "select name from sysobjects where type='U' order by name"
query "$sql" "bcp" | sed -e 's/|//g' > temptablelist

#cat temptablelist

set tables = ( `cat temptablelist` )

while ("$tables" != "")
    set table = $tables[1] 
    shift tables
    echo $table
    # I already loaded this big table, don't need to do it again.
    #if ("$table" != "ACC_Accession") then
    	getTable $table
    #endif
end

	
