#!/bin/tcsh -ef
if ("$jdb" == "") then
    echo "env var jdb not set.  should be something like jackson20060125"
    exit 1
endif

set outpath = "/san/sanvol1/visiGene/offline/jax/$jdb"

set tables = ( `cat temptablelist` )

set op = "do" #"skip"
while ("$tables" != "")
    set table = $tables[1] 
    shift tables
    # I already indexed these big tables, don't need to do it again.
    #if ("$table" == "SNP_SubSnp_StrainAllele") then
	#set op = "do"
    #endif
    if ("$op" == "do") then
	echo $table
    	loadIndex $table
    endif
end

	
