#!/bin/tcsh -ef
if ("$jdb" == "") then
    echo "env var jdb not set.  should be something like jackson20060125"
    exit 1
endif

set outpath = "/san/sanvol1/visiGene/offline/jax/$jdb"

set tables = ( `cat temptablelist` )
set op = "do" # "skip"
while ("$tables" != "")
    set table = $tables[1] 
    shift tables
    # If I already loaded some big tables, don't need to do them again.
    #if ("$table" == "MGI_Tables") then
    #	set op = "do"
    #endif
    if ( "$op" == "do" ) then
	echo $table
    	loadTable $table
    endif
end

	
