table abelSv
"Structural variants from Abel et al. 2020 (CCDG, 17,795 human genomes)"
    (
    string chrom;      "Chromosome"
    uint   chromStart; "Start position"
    uint   chromEnd;   "End position"
    string name;       "Variant ID"
    uint   score;      "Score (0-1000), higher AF is higher"
    char[1] strand;    "Strand (. for most SVs)"
    uint   thickStart; "Thick start (same as chromStart)"
    uint   thickEnd;   "Thick end (same as chromEnd)"
    uint   itemRgb;    "RGB color based on SV type"
    string svType;     "SV Type|DEL=deletion, DUP=duplication, INV=inversion, MEI=mobile element insertion, BND=breakend/translocation"
    int    svLength;   "SV Length (bp)|Difference in length between REF and ALT alleles; -1 for BND"
    string callset;    "Source callset|B38=native GRCh38 calls (14,623 samples), B37lift=lifted from GRCh37 (8,417 samples)"
    string filter;     "Filter status|PASS (high confidence) or LOW (low confidence)"
    int    ac;         "Allele Count (AC)|Total alternate-allele count across all samples"
    int    an;         "Allele Number (AN)|Total called alleles across all samples"
    float  af;         "Allele Frequency (AF)|AC/AN"
    float  msq;        "Mean Sample Quality (MSQ)|Mean GQ across positively genotyped samples"
    int    nSamp;      "Samples with non-reference genotype (NSAMP)"
    int    nFam;       "Families with non-reference genotype (NFAM)"
    string mateChrom;  "Mate chromosome|For BND only; translocation partner"
    int    matePos;    "Mate position|For BND only; -1 otherwise"
    int    acAfr;      "AC - African (AFR)"
    int    anAfr;      "AN - African (AFR)"
    int    acAmr;      "AC - Latino/Admixed-American (AMR)"
    int    anAmr;      "AN - Latino/Admixed-American (AMR)"
    int    acNfe;      "AC - Non-Finnish European (NFE)"
    int    anNfe;      "AN - Non-Finnish European (NFE)"
    int    acFe;       "AC - Finnish European (FE)"
    int    anFe;       "AN - Finnish European (FE)"
    int    acEas;      "AC - East-Asian (EAS)"
    int    anEas;      "AN - East-Asian (EAS)"
    int    acSas;      "AC - South-Asian (SAS)"
    int    anSas;      "AN - South-Asian (SAS)"
    int    acPi;       "AC - Pacific Islander (PI)"
    int    anPi;       "AN - Pacific Islander (PI)"
    int    acOther;    "AC - Other"
    int    anOther;    "AN - Other"
    )
