table lrSv1kg3202Sr
"1000 Genomes 3202-sample short-read GATK-SV structural variants (Byrska-Bishop 2022)"
    (
    string chrom;           "Chromosome"
    uint chromStart;        "Start position"
    uint chromEnd;          "End position"
    string name;            "Variant ID"
    uint score;             "Score"
    char[1] strand;         "Strand"
    uint thickStart;        "Thick start (same as chromStart)"
    uint thickEnd;          "Thick end (same as chromEnd)"
    uint reserved;          "Item color"
    string svType;          "SV Type|DEL, INS, DUP, INV, CPX, CTX or CNV"
    int svLen;              "SV Length|Length of the variant on the reference in base pairs"
    int insLen;             "Insertion Length|Length of inserted sequence, 0 for DEL/INV/CPX"
    int AC;                 "Allele Count (AC)"
    uint alleleNumber;      "Allele Number (AN)"
    float alleleFreq;       "Allele Frequency (AF)"
    float popmaxAf;         "Population Max AF|Highest AF across the five superpopulations"
    float afAfr;            "AF African"
    float afAmr;            "AF Admixed American"
    float afAsn;            "AF East Asian"
    float afEur;            "AF European"
    float afSan;            "AF South Asian"
    uint nHet;              "Het Carriers|Number of heterozygous samples"
    uint nHomalt;           "Hom-alt Carriers|Number of homozygous-alternate samples"
    string algorithms;      "Source Algorithms|SV callers contributing evidence (depth, PE, SR, ...)"
    string source;          "Source Pipeline|Upstream SV pipeline (gatksv, svtools, etc.)"
    string filterStatus;    "Filter Status|PASS, LowQual, MinGQ, etc. (VCF FILTER column)"
    string chr2;            "Second Chromosome|For translocations (CTX)"
    )
