#!/usr/bin/awk -f

# getQNames psl ..
# get query/target names for all partitions for comparing results

BEGIN {
    FS = "\t";
    OFS = "\t";
}

FNR == 1 {
    # remove leading directory (normally output/)
    file = gensub("^[^/]+/","","g", FILENAME);
    print file;
}
{
    print "",$10,$14;
}
