table gencNcOrfBigGenePred
"bigGenePred for GENCODE ncORFs with Kozak strength"
   (
   string chrom;       "Reference sequence chromosome or scaffold"
   uint   chromStart;  "Start position in chromosome"
   uint   chromEnd;    "End position in chromosome"
   string name;        "Name or ID of item, ideally both human readable and unique"
   uint score;         "Score (0-1000)"
   char[1] strand;     "+ or - for strand"
   uint thickStart;    "Start of where display should be thick (start codon)"
   uint thickEnd;      "End of where display should be thick (stop codon)"
   uint reserved;      "RGB value (use R,G,B string in input file). Color reflects Kozak translational efficiency."
   int blockCount;     "Number of blocks"
   int[blockCount] blockSizes; "Comma separated list of block sizes"
   int[blockCount] chromStarts; "Start positions relative to chromStart"
   string name2;       "Alternative/human readable name"
   string cdsStartStat; "Status of CDS start annotation (none, unknown, incomplete, or complete)"
   string cdsEndStat;   "Status of CDS end annotation (none, unknown, incomplete, or complete)"
   int[blockCount] exonFrames; "Exon frame {0,1,2}, or -1 if no frame for exon"
   string type;        "Transcript type ('orf biotype' for Ribo-seq ORFs)"
   string geneName;    "Primary identifier for gene"
   string geneName2;   "Alternative/human readable gene name"
   string geneType;    "Gene type"
   string transcript_biotype; "protein_coding, processed_transcript or lncRNA"
   lstring sequence;    "Translated protein sequence"
   lstring all_transcript_ids; "List of transcript_ids that are fully compatible with the ORF sequence"
   string all_gene_ids; "List of gene_ids that are fully compatible with the ORF sequence"
   string replicated;   "'yes' or 'no' depending on whether it was replicated in more than one Ribo-seq ORF study"
   string ref_studies;  "List of PMID studies where the Ribo-seq ORF was identified"
   string startCodon;   "Start codon (ATG, CTG, GTG, TTG, ACG, other) read from genome|First 3 bp of ORF on transcript strand"
   string kozakStrength; "Kozak consensus strength|Strong/Moderate/Weak per Kozak rule on -3 and +4"
   float  kozakTE;       "Kozak translational efficiency|Noderer 2014 TE for the 11-base TIS context (-1 if non-ATG or context unavailable)"
   )
