table metamorfKozak
"MetamORF ORFs as bigGenePred with Kozak strength"
   (
   string chrom;       "Reference sequence chromosome or scaffold"
   uint   chromStart;  "Start position in chromosome"
   uint   chromEnd;    "End position in chromosome"
   string name;        "ORF ID in MetamORF"
   uint score;         "Score (0-1000)"
   char[1] strand;     "+ or - for strand"
   uint thickStart;    "Start of where display should be thick (start codon)"
   uint thickEnd;      "End of where display should be thick (stop codon)"
   uint reserved;      "RGB value (use R,G,B string in input file). Color reflects Kozak consensus strength."
   int blockCount;     "Number of blocks"
   int[blockCount] blockSizes; "Comma separated list of block sizes"
   int[blockCount] chromStarts; "Start positions relative to chromStart"
   string name2;       "Gene symbol"
   string cdsStartStat; "Status of CDS start annotation"
   string cdsEndStat;   "Status of CDS end annotation"
   int[blockCount] exonFrames; "Exon frame {0,1,2}, or -1 if no frame for exon"
   string type;        "ORF annotation"
   string geneName;    "Primary transcript identifier"
   string geneName2;   "Alternative gene name"
   string geneType;    "RNA biotype"
   lstring transcripts;        "Comma-separated list of transcripts harboring this ORF"
   lstring rna_biotypes;       "Comma-separated list of RNA biotypes harboring this ORF"
   lstring cell_types;         "Comma-separated list of cell types in which the ORF was identified"
   string  orf_annotations;    "Comma-separated list of ORF annotations"
   string  kozak_contexts;     "Comma-separated list of Kozak contexts found for this ORF"
   string  startCodon;         "Start codon (ATG, CTG, GTG, TTG, ACG, other) read from genome"
   string  kozakStrength;      "Kozak consensus strength|Strong/Moderate/Weak per Kozak rule on -3 and +4"
   float   kozakTE;            "Kozak translational efficiency|Noderer 2014 TE (-1 if non-ATG or context unavailable)"
   string  _teRgb;             "Alternate RGB color from Kozak TE bin (reserved for future second-color use)"
   )
