table nuorfdbKozak
"nuORFdb ORFs as bigGenePred with Kozak strength"
   (
   string chrom;       "Reference sequence chromosome or scaffold"
   uint   chromStart;  "Start position in chromosome"
   uint   chromEnd;    "End position in chromosome"
   string name;        "ORF identifier"
   uint score;         "Score (0-1000)"
   char[1] strand;     "+ or - for strand"
   uint thickStart;    "Start of where display should be thick (start codon)"
   uint thickEnd;      "End of where display should be thick (stop codon)"
   uint reserved;      "RGB value (use R,G,B string in input file). Color reflects Kozak translational efficiency."
   int blockCount;     "Number of blocks"
   int[blockCount] blockSizes; "Comma separated list of block sizes"
   int[blockCount] chromStarts; "Start positions relative to chromStart"
   string name2;       "Gene name"
   string cdsStartStat; "Status of CDS start annotation"
   string cdsEndStat;   "Status of CDS end annotation"
   int[blockCount] exonFrames; "Reading frame of the start of the CDS region of the exon"
   string type;        "ORF merge type (e.g. Pseudogene, lincRNA, 5' uORF)"
   string geneName;    "Ensembl gene ID"
   string geneName2;   "Gene name (same as name2)"
   string geneType;    "Gene biotype"
   string predictorType;      "ORF predictor classification"
   string plotType;            "Simplified ORF category for display"
   lstring proteinSequence;    "Predicted protein sequence"
   string startCodon;          "Start codon (ATG, CTG, GTG, TTG, ACG, other) read from genome"
   string kozakStrength;       "Kozak consensus strength|Strong/Moderate/Weak per Kozak rule on -3 and +4"
   float  kozakTE;             "Kozak translational efficiency|Noderer 2014 TE (-1 if non-ATG or context unavailable)"
   )
