table openprotKozak
"OpenProt proteins as bigGenePred with Kozak strength"
   (
   string chrom;       "Reference sequence chromosome or scaffold"
   uint   chromStart;  "Start position in chromosome"
   uint   chromEnd;    "End position in chromosome"
   string name;        "Protein identifier"
   uint score;         "Score (0-1000)"
   char[1] strand;     "+ or - for strand"
   uint thickStart;    "Start of where display should be thick (start codon)"
   uint thickEnd;      "End of where display should be thick (stop codon)"
   uint reserved;      "RGB value (use R,G,B string in input file). Color reflects Kozak translational efficiency."
   int blockCount;     "Number of blocks"
   int[blockCount] blockSizes; "Comma separated list of block sizes"
   int[blockCount] chromStarts; "Start positions relative to chromStart"
   string name2;       "Gene symbol"
   string cdsStartStat; "Status of CDS start annotation"
   string cdsEndStat;   "Status of CDS end annotation"
   int[blockCount] exonFrames; "Reading frame (-1 for all)"
   string type;        "Protein type (AltProt, RefProt, or Isoform)"
   string geneName;    "Gene symbol"
   string geneName2;   "Gene symbol"
   string geneType;    "Transcript type (mRNA or ncRNA)"
   string localization; "ORF localization relative to CDS (5'UTR, CDS, 3'UTR, ncRNA)"
   uint   msScore;      "MS score: sum of unique peptides per study"
   uint   teScore;      "TE score: number of studies detecting translation"
   string kozakMotif;   "Kozak motif present (+) or absent (-) (per OpenProt)"
   uint   domains;      "Number of predicted InterPro domains"
   string frame;        "Reading frame (+1, +2, or +3)"
   string startCodon;          "Start codon (ATG, CTG, GTG, TTG, ACG, other) read from genome"
   string kozakStrength;       "Kozak consensus strength|Strong/Moderate/Weak per Kozak rule on -3 and +4"
   float  kozakTE;             "Kozak translational efficiency|Noderer 2014 TE (-1 if non-ATG or context unavailable)"
   )
