table utrAnnotUorfsKozak
"UTRannotator uORFs as bigGenePred with Kozak strength"
   (
   string chrom;       "Reference sequence chromosome or scaffold"
   uint   chromStart;  "Start position in chromosome"
   uint   chromEnd;    "End position in chromosome"
   string name;        "Gene symbol"
   uint score;         "Score (0-1000)"
   char[1] strand;     "+ or - for strand"
   uint thickStart;    "Start of where display should be thick (start codon)"
   uint thickEnd;      "End of where display should be thick (stop codon)"
   uint reserved;      "RGB value (use R,G,B string in input file). Color reflects Kozak translational efficiency."
   int blockCount;     "Number of blocks"
   int[blockCount] blockSizes; "Comma separated list of block sizes"
   int[blockCount] chromStarts; "Start positions relative to chromStart"
   string name2;       "Gene symbol"
   string cdsStartStat; "Status of CDS start annotation"
   string cdsEndStat;   "Status of CDS end annotation"
   int[blockCount] exonFrames; "Exon frame {0,1,2}, or -1 if no frame for exon"
   string type;        "Transcript type"
   string geneName;    "Primary identifier for gene"
   string geneName2;   "Alternative/human readable gene name"
   string geneType;    "Gene type"
   string uorfType;    "Type of uORF: 5'UTR only or 5'UTR extending into 3'UTR"
   string intronsSource; "Source database that contributed the intron/exon structure|Comma-separated list of databases that had a matching (chrom, start, end, strand) feature; 'none' = single-block, no donor found"
   string startCodon;   "Start codon (ATG, CTG, GTG, TTG, ACG, other) read from genome|First 3 bp of ORF on transcript strand"
   string kozakStrength; "Kozak consensus strength|Strong/Moderate/Weak per Kozak rule on -3 and +4"
   float  kozakTE;       "Kozak translational efficiency|Noderer 2014 TE for the 11-base TIS context (-1 if non-ATG or context unavailable)"
   )
