
all::
	cd raToLines && $(MAKE)
	cd linesToRa && $(MAKE)

compile::
	cd raToLines && $(MAKE) compile
	cd linesToRa && $(MAKE) compile

clean::
	cd raToLines && $(MAKE) clean
	cd linesToRa && $(MAKE) clean

