table sedef
"SedDups Features Description"
(
    string  chrom;		"Reference sequence chromosome or scaffold"
    uint    chromStart;	"Alignment start"
    uint    chromEnd;	"Alignment end"
    string  name;		"Position of the matching duplication"
    uint    score;		"fake score"
    char[1] strand;		"+ or - for strand"
    uint    thickStart;	"thick start"
    uint    thickEnd;	"thick end"
    uint    color;		"Color reflects %id. Approximatly matches WGAC track."
    string  chrom2;		"Reference sequence chromosome or scaffold"
    uint    Start2;     "second alignment start"
    uint    End2;		"second alignment end"
    float    score2;	"Score"
    char[1] strand2;	"+ or - for strand"
    uint    maxlen;     "max_len"
    uint    alnlen;     "aln_len"
    uint    indela;     "indel_a"
    uint    indelb;     "indel_b"
    uint    alnB;       "alnB"
    uint    matchB;     "matchB"
    uint    mismatchB;     "mismatchB"
    uint    transitionsB;       "transitionsB"
    uint    transvertionsB;     "transvertionsB"
    float   fracMatch;          "fracMatch"
    float   fracMatchIndel;     "fracMatchIndel"
    float   jck;                "jck"
    float   k2K;                "k2K"
    uint    alngaps;            "aln_gaps"
    uint    uppercaseA;         "uppercaseA"
    uint    uppercaseB;         "uppercaseB"
    uint    uppercaseMatches;   "uppercaseMatches"
    uint    alnMatches;         "aln_matches"
    uint    alnMismatches;      "aln_mismatches"
    uint    alnGapBases;        "aln_gap_bases"
    float   filterScore;        "filter_score"
    uint    satBases;        "sat bases"
    uint    uniqueID;        "unique_id"
    string  original;		"Whether the SD is the original SD, or the symetric copy."
    uint    telo;     "is telomeric"
    uint    peri;     "is pericentromeric"
    uint    acro;     "is acrocentric"
    uint    telo2;     "other is telomeric"
    uint    peri2;     "other is pericentromeric"
    uint    acro2;     "other is acrocentric"
)
