# affyTranscriptome.sql was originally generated by the autoSql program, which also 
# generated affyTranscriptome.c and affyTranscriptome.h.  This creates the database representation of
# an object which can be loaded and saved from RAM in a fairly 
# automatic way.

#Affymetrix Transcriptome
CREATE TABLE affyTranscriptome (
    bin int unsigned,
    chrom varchar(255) not null,	# Chromosome
    chromStart int unsigned not null,	# Start in Chromosome
    chromEnd int unsigned not null,	# End in Chromosome
    name varchar(255) not null,		# Name
    score int unsigned not null,	# Score
    strand char(1) not null,		# Strand
    sampleCount int unsigned not null,	# Number of points in this record
    samplePosition longblob not null,	# Posititions of the oligos
    sampleHeight longblob not null,	# Intentisy of hybridization
              #Indices
#    PRIMARY KEY(chrom)
    INDEX(chrom(8),bin)
);
