table alleleFreqs
"Allele Frequencies from HapMap"
(
string 	rsId; 		" rs			rs2104604"
string	chrom;		"Reference sequence chromosome or scaffold"
int	chromStart;	" pos			101809619"
char	strand;		" strand		+"
string	assembly;	" build			ncbi_b34"
string	center;		" center		bcm"
string  protLSID;       "protLSID"
string  assayLSID;      "assayLSID"
string  panelLSID;      "panelLSID"
char	majAllele;	" major_allele		G"
int	majCount;	" major_allele_count	120"
float	majFreq;	" major_allele_freq	1"
char	minAllele;	" minor_allele		T"
int	minCount;	" minor_allele_count	0"
float	minFreq;	" minor_allele_freq	0"
int	total;		" total			120"
)
