table bgiSnp
"Beijing Genomics Institute SNP information as bed 4 +"
    (
    string chrom;	"Reference sequence chromosome or scaffold"
    uint   chromStart;	"Start position in chromosome"
    uint   chromEnd;	"End position in chromosome"
    string name;	"BGI SNP name: snp.superctg.ctg.pos.type.strainID"
    char[1] snpType;	"S (substitution), I (insertion), or D (deletion)"
    uint readStart;	"Start position in alternate allele read"
    uint readEnd;	"End position in alternate allele read"
    uint qualChr;	"Quality score in reference assembly"
    uint qualReads;	"Quality score in alternate allele read"
    string snpSeq;	"'X->Y' or indel sequence"
    string readName;	"Name of alternate allele read"
    char[1] readDir;    "Direction of read relative to reference"
    char[4] inBroiler;	"SNP found in Broiler strain? yes, no or n/a if not covered"
    char[4] inLayer;	"SNP found in Layer strain? yes, no or n/a if not covered"
    char[4] inSilkie;	"SNP found in Silkie strain? yes, no or n/a if not covered"
    string primerL;	"Left primer sequence"
    string primerR;	"Right primer sequence"
    char[1] questionM;	"L for dubious indels, H for other indels and SNPs"
    string extra;	"Additional information"
    )
