
table bigNet
"bigNet - a net of pairwise alignments in bigBed format"
    (
    string chrom;       "Reference sequence chromosome or scaffold"
    uint   chromStart;  "Start position in chromosome"
    uint   chromEnd;    "End position in chromosome"
    string name;        "Name of the query sequence"
    uint   score;       "Score (0-1000)"
    char[1] strand;     "+ or - for strand of the query sequence"
    uint   level;       "Depth in the net.  Odd levels are fills, even levels are gaps"
    uint   qStart;      "Start of alignment on query sequence"
    uint   qEnd;        "End of alignment on query sequence"
    uint   chainId;     "Id of the chain that fills this gap.  0 for a gap"
    uint   ali;         "Bases in gap-free alignments"
    double chainScore;  "Score from the chain"
    string type;        "Syntenic type: gap, top, syn, nonSyn or inv"
    int    qOver;       "Overlap with parent gap on query side.  -1 for undefined"
    int    qFar;        "Distance from parent gap on query side.  -1 for undefined"
    int    qDup;        "Bases with two or more copies in query.  -1 for undefined"
    int    tN;          "Unsequenced bases on target.  -1 for undefined"
    int    qN;          "Unsequenced bases on query.  -1 for undefined"
    int    tR;          "RepeatMasker bases on target.  -1 for undefined"
    int    qR;          "RepeatMasker bases on query.  -1 for undefined"
    int    tNewR;       "Lineage specific repeat bases on target.  -1 for undefined"
    int    qNewR;       "Lineage specific repeat bases on query.  -1 for undefined"
    int    tOldR;       "Bases of ancient repeats on target.  -1 for undefined"
    int    qOldR;       "Bases of ancient repeats on query.  -1 for undefined"
    int    tTrf;        "Bases of tandem repeats on target.  -1 for undefined"
    int    qTrf;        "Bases of tandem repeats on query.  -1 for undefined"
    )
