table browserTable
"List of tables to be displayed in browser. Read by brower each hit."
(
	char[64] tableName; "Name of table in database to be queried."
	char[128] longLabel; "Long name to be displayed in center browser window."
	char[32] shortLabel; "Short name to be displaed on left of browser window."
	char[32] mapName; "Return name to associate on map."
	string version; "Versioning information about table."
	char[32] trackType; "Initially just 'bed' and 'psl' supported."
	ushort visibility; "tvHide=0, tvDense=1 or tvFull=2."
	ushort colorR; "red of main color."
	ushort colorG; "green of main color."
	ushort colorB; "blue of main color."
	ushort altColorR; "red of alternate color."
	ushort altColorG; "green of alternate color."
	ushort altColorB; "blue of alternate color."
	ushort private; "True(1) if private, false(0) otherwise."
	ushort useScore; "If True(1) use score information in table, only shades of gray color supported."
	ushort isSplit; "True(1) if table is split over different chromosomes. i.e. chrN_est"
	ushort isPlaced; "True(1) if the table has positional information."
	char[32] startName; "The name of the field with the start position."
	char[32] endName; "The name of the field with the end position."
	int priority; "Priority to load tracks in, i.e. order to load tracks in."
	lstring credit; "Who to credit/blame for information in table."
	lstring url; "Link to more information about track."
	lstring other; "Other track specific associated information."
)

