# cnpSebat.sql was originally generated by the autoSql program, which also 
# generated cnpSebat.c and cnpSebat.h.  This creates the database representation of
# an object which can be loaded and saved from RAM in a fairly 
# automatic way.

#CNP Data from the Sebat lab
CREATE TABLE cnpSebat (
    chrom varchar(255) not null,	# Chromosome
    chromStart int unsigned not null,	# Start position in chrom
    chromEnd int unsigned not null,	# End position in chrom
    name varchar(255) not null,		# Gain or Loss
    probes int unsigned not null,	# Number of probes
    individuals int unsigned not null	# Number of individuals
);
