table dbRIP
"Retrotransposon Insertion Polymorphisms in Humans"
    (
    string chrom;      "Chromosome (or contig, scaffold, etc.)"
    uint   chromStart; "Start position in chromosome"
    uint   chromEnd;   "End position in chromosome"
    string name;       "Database ID"
    uint   score;      "Score from 0-1000"
    char[1] strand;    "+ or -"
    string originalId; "original ID"
    string forwardPrimer;  "forward Primer"
    string reversePrimer;  "reverse Primer"
    string polyClass;  "Repeat Class"
    string polyFamily;  "Repeat Family"
    string polySubfamily;  "Repeat Sub-family"
    lstring polySeq;    "sequence"
    string polySource; "source"
    lstring reference;  "reference"
    string ascertainingMethod;  "Ascertaining Method"
    string remarks;    "remarks"
    float tm;          "temperature"
    int   filledSize;  "filled size"
    int   emptySize;   "empty size"
    string disease;    "disease"
    string genoRegion; "genome region"
    )
