# defaultDb.sql was originally generated by the autoSql program, which also 
# generated defaultDb.c and defaultDb.h.  This creates the database representation of
# an object which can be loaded and saved from RAM in a fairly 
# automatic way.

#Description of annotation database
CREATE TABLE defaultDb (
    genome varchar(255) not null,	# Unifying genome collection for which an assembly is the default
    name varchar(255) not null,	# Short name of database.  'hg8' or the like
              #Indices
    PRIMARY KEY(genome)
);
