# easyGene.sql was originally generated by the autoSql program, which also 
# generated easyGene.c and easyGene.h.  This creates the database representation of
# an object which can be loaded and saved from RAM in a fairly 
# automatic way.

#BED-style EasyGene format
CREATE TABLE easyGene (
    bin int unsigned not null,
    chrom varchar(255) not null,	# Chromosome or FPC contig
    chromStart int unsigned not null,	# Start position in chromosome
    chromEnd int unsigned not null,	# End position in chromosome
    name varchar(255) not null,	# Name of item
    score int unsigned not null,	# Score
    strand char(1) not null,	# Strand
    feat varchar(255) not null,	# Feature identifier
    R float not null,	# R value
    frame int unsigned not null,	# Frame
    orf varchar(255) not null,	# ORF identifier
    startCodon varchar(255) not null,	# Start Codon
    logOdds float not null,	# Log odds
    descriptor varchar(255) not null,	# EasyGene descriptor
    swissProt varchar(255) not null,	# Swiss-Prot match
    genbank char(1) not null	# Y or N this is the genbank one
);
