table encode4
"Bed 12+8 file with annotation source and values per sample in a html table."
    (
    string chrom;      "Chromosome (or contig, scaffold, etc.)"
    uint   chromStart; "Start position in chromosome"
    uint   chromEnd;   "End position in chromosome"
    string name;       "Name of item"
    uint   score;      "Score from 0-1000"
    char[1] strand;    "+ or -"
    uint thickStart;   "Start of where display should be thick (start codon)"
    uint thickEnd;     "End of where display should be thick (stop codon)"
    uint reserved;     "Used as itemRgb as of 2004-11-22"
    int blockCount;    "Number of blocks"
    int[blockCount] blockSizes; "Comma separated list of block sizes"
    int[blockCount] chromStarts; "Start positions relative to chromStart"
    string source;      "Annotation source"
    string gene_id;     "gene ID"	
    string gene_name;   "gene name"	
    string transcript_id;   "transcript ID"	
    string transcript_name;   "transcript name"	
    float maxScore;   "Highest expression score (counts per million)"
    lstring maxScoreHtml;   "Highest expression score and sample(s)"
    lstring expr_table; "Expression values per sample in TPM"
    )
