table ensTranscript
"This is the table transcript downloaded directly from Ensembl ftp site (18.34 release 11/04). Please refer to Ensembl site for details.  CAUTION: Ensembl sometimes changes its table definitions and some field may not contais data as its name indicates."
   (
   int id;			"internal system ID?"
   string db;			"unknown - check with Ensembl"
   string analysis;		"unknown - check with Ensembl"
   string type;			"unknown - check with Ensembl"
   int transcript_id;		"transcript ID"
   string transcript_name;	"transcript name"
   int transcript_version;	"transcript version"
   string chr_name;		"chromosome number"
   int chr_start;		"start position"
   int chr_end;			"end   position"
   int chr_strand;		"strand"
   int coding_start;		"coding start position"
   int coding_end;		"coding end   position"
   int translation_id;		"translation ID"
   string translation_name;	"translation Name"
   string translation_version;	"translation version"
   int gene_id;			"gene ID"
   string gene_name;		"gene name"
   int gene_version;		"gene version"
   lstring exon_structure;	"exon structure"
   lstring exon_ids;		"exon IDs"
   string external_db;		"external database"
   string external_name;	"external name"
   char[10] external_status;	"external status"
   )

