table gadAll
"Genetic Association Database (GAD) http://geneticassociationdb.nih.gov/"
    (
    string  id;               "ID"
    char[1] association;      "Association(Y/N)"
    string  broadPhen;        "Broad Phenotype"
    string  diseaseClass;     "Disease Class"
    string  diseaseClassCode; "Disease Class"
    lstring meshTerm;         "MeSH Disease Terms"
    string  chromosome;       "Chromosome"
    string  band;             "Chr-Band"
    string  geneSymbol;       "Gene"
    uint    chromStart;       "DNA Start"
    uint    chromEnd;         "DNA End"
    string  pValue;           "P Value"
    string  reference;        "Reference"
    string  pubMed;           "Pubmed ID"
    string  alleleAuthDes;    "Allele Author Discription"
    string  alleleFunEffect;  "Allele Functional Effects"
    string  polymClass;       "Polymophism Class"
    string  geneName;         "Gene Name"
    string  refSeq;           "RefSeq ID"
    string  population;       "Population"
    string  meshGeoloc;       "MeSH Geolocation"
    string  submitter;        "Submitter"
    string  locusNum;         "Locus Number"
    string  unigene;          "Unigene"
    string  narrowPhen;       "Narrow Phenotype"
    string  molePhenotype;    "Mole. Phenotype"
    string  journal;          "Journal"
    lstring title;            "Title"
    string  rsId;             "rs Number"
    string  omimId;           "OMIM ID"
    string  gadQ;             "GAD/CDC (unpopulated as of 2013)"
    string  gadCdc;           "GAD/CDC (unpopulated as of 2013)"
    string  year;             "Year"
    lstring conclusion;       "Conclusion"
    lstring studyInfo;        "Study Info"
    string  envFactor;        "Env. Factor"
    string  giGeneA;          "GI Gene A"
    string  giAlleleGeneA;    "GI Allele of Gene A"
    string  giGeneB;          "GI Gene B"
    string  giAlleleGeneB;    "GI Allele of Gene B"
    string  giGeneC;          "GI Gene C"
    string  giAlleleGeneC;    "GI Allele of Gene C"
    string  giAssociation;    "GI Association?"
    string  giEnv;            "GI combine Env. Factor"
    string  giDis;            "GI relevant to Disease"
    )
