"<!DOCTYPE html>\n"
"<html>\n"
"\n"
"<!-- NOTE: gbHeader.html is actually a format value for printf,\n"
"     so use \"%%\" not single percent when editing the html. -->\n"
"\n"
"  <head>\n"
"    %s"  
"    <meta http-equiv=\"Content-Type\" CONTENT=\"text/html;CHARSET=iso-8859-1\">\n"
"    <meta name=\"description\" content=\"UCSC Genome Browser\">\n"
"    <meta name=\"keywords\" content=\"genome, genome browser, human genome, genome assembly, Blat, UCSC, bioinformatics, gene prediction, SNP, SNPs, EST, mRNA, mouse genome, rat genome, chicken genome, chimp genome, dog genome, fruitfly genome, zebrafish genome, xenopus, frog genome, rhesus, opossum, danio rerio genome, drosophila, fugu, yeast, ciona,  comparative genomics, human variation, hapMap\">\n"
"    <title>UCSC %s</title>\n"
"    <link href='https://fonts.googleapis.com/css?family=Oswald:700|Lato:700,700italic,300,400,400italic' rel='stylesheet' type='text/css'>\n"
"    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css\">\n"
"    <link rel=\"stylesheet\" href=\"../style/bootstrap.min.css\">\n"
"  </head>\n"
"\n"
"  <body>\n"
