table genomicSuperDups
"Summary of large genomic Duplications (>1KB >90% similar)"
  (
  string chrom;       "Reference sequence chromosome or scaffold"
  uint chromStart;   "Start position in chromosome"
  uint chromEnd;     "End position in chromosome"
  string name;         "Other chromosome involved"
  uint score;        "Score from 900-1000.  1000 is best"
  char[1] strand;       "Value should be + or -"
  string otherChrom;   "Other chromosome or scaffold"
  uint otherStart;   "Start in other  sequence"
  uint otherEnd;     "End in other  sequence"
  uint otherSize;    "Total size of other sequence"
  uint uid;       "unique id"
  uint posBasesHit;       "HitPositive UnCovered"
  string testResult;       "HitPositive (yes or no) UnCovered (covered=0)"
  string verdict;       "Real or Allele"
  string alignfile;       "alignment file path"
  uint alignL;       "spaces/positions in alignment"
  uint indelN;       "number of indels"
  uint indelS;       "indel spaces"
  uint alignB;       "bases Aligned"
  uint matchB;       "aligned bases that match"
  uint mismatchB;    "aligned bases that do not match"
  uint transitionsB;    "number of transitions"
  uint transversionsB;    "number of transversions"
  float fracMatch;    "fraction of matching bases"
  float fracMatchIndel;    "fraction of matching bases with indels"
  float jcK;          "K-value calculated with Jukes-Cantor"
  float k2K;          "Kimura K"
  )
