table genomeData
"SQL table for NCBI assembly_summary data."
    (
    string assemblyAccession;	"assemblyAccession"
    string bioproject;	"bioproject"
    string biosample;	"biosample"
    string wgsMaster;	"wgsMaster"
    string refseqCategory;	"refseqCategory"
    uint taxId;	"taxId"
    uint speciesTaxid;	"speciesTaxid"
    string organismName;	"organismName"
    string infraspecificName;	"infraspecificName"
    string isolate;	"isolate"
    string versionStatus;	"versionStatus"
    string assemblyLevel;	"assemblyLevel"
    string releaseType;	"releaseType"
    string genomeRep;	"genomeRep"
    string seqRelDate;	"seqRelDate"
    string asmName;	"asmName"
    string asmSubmitter;	"asmSubmitter"
    string gbrsPairedAsm;	"gbrsPairedAsm"
    string pairedAsmComp;	"pairedAsmComp"
    string ftpPath;	"ftpPath"
    string excludedFromRefseq;	"excludedFromRefseq"
    string relationToTypeMaterial;	"relationToTypeMaterial"
    ubyte assemblyType;	"assemblyType"
    string phyloGroup;	"phyloGroup"
    bigint genomeSize;	"genomeSize"
    bigint genomeSizeUngapped;	"genomeSizeUngapped"
    float gcPercent;	"gcPercent"
    ushort repliconCount;	"repliconCount"
    uint scaffoldCount;	"scaffoldCount"
    uint contigCount;	"contigCount"
    string annotationProvider;	"annotationProvider"
    string annotationName;	"annotationName"
    string annotationDate;	"annotationDate"
    string totalGeneCount;	"totalGeneCount"
    uint proteinCodingGeneCount;	"proteinCodingGeneCount"
    string nonCodingGeneCount;	"nonCodingGeneCount"
    string pubmedId;	"pubmedId"
    )
