# gtexEqtl.sql was originally generated by the autoSql program, which also 
# generated gtexEqtl.c and gtexEqtl.h.  This creates the database representation of
# an object which can be loaded and saved from RAM in a fairly 
# automatic way.

#BED 9+ of eQTLs (variants affecting gene expression) with a target gene, effect size, p-value, and causal probability metric
CREATE TABLE gtexEqtl (
    bin smallint not null,		# Bin number for browser speedup
    chrom varchar(255) not null,	# Reference sequence chromosome or scaffold
    chromStart int unsigned not null,	# Start position in chromosome
    chromEnd int unsigned not null,	# End position in chromosome
    name varchar(255) not null,	# Name of variant (rsID or GTEx identifier if none)
    score int unsigned not null,	# Score from 0-1000 (highest probabiliity in cluster * 1000)
    strand char(1) not null,	# .
    thickStart int unsigned not null,	# Start position
    thickEnd int unsigned not null,	# End position
    reserved int unsigned not null,	# R,G,B color: red for up-regulated, blue for down. Bright for high, grayed for low.
    gene varchar(255) not null,	# Name of target gene
    distance int not null,	# Distance from TSS
    effectSize float not null,	# Effect size (FPKM). Regression slope calculated using quantile normalized expression
    pValue float not null,	# Nominal p-value
    causalProb float not null,	# Probability variant is in 95% credible set
              #Indices
    INDEX (chrom,bin),
    INDEX (name),
    INDEX (gene)
);
