table hgnc
"A cross-reference table between HUGO Gene Nomenclature Committee (HGNC) IDs and other database IDs."
    (
    string chrom;      "Chromosome (or contig, scaffold, etc.)"
    uint   chromStart; "Start position in chromosome"
    uint   chromEnd;   "End position in chromosome"
    string name;       "Name of item"
    uint   score;      "Score from 0-1000"
    char[1] strand;    "+ or -"
    uint thickStart;   "Start of where display should be thick (start codon)"
    uint thickEnd;     "End of where display should be thick (stop codon)"
    uint reserved;     "Used as itemRgb as of 2004-11-22"

    string symbol; "symbol"
    string geneName; "geneName"
    string locus_group; "locus_group"
    string locus_type; "locus_type"
    string status; "status"
    string location; "location"
    string location_sortable; "location_sortable"
    string alias_symbol; "alias_symbol"
    lstring alias_name; "alias_name"
    string prev_symbol; "prev_symbol"
    lstring prev_name; "prev_name"
    string gene_group; "gene_group"
    string gene_group_id; "gene_group_id"
    string date_approved_reserved; "date_approved_reserved"
    string date_symbol_changed; "date_symbol_changed"
    string date_name_changed; "date_name_changed"
    string date_modified; "date_modified"
    string entrez_id; "entrez_id"
    string ensembl_gene_id; "ensembl_gene_id"
    string vega_id; "vega_id"
    string ucsc_id; "ucsc_id"
    string ena; "ena"
    string refseq_accession; "refseq_accession"
    string ccds_id; "ccds_id"
    string uniprot_ids; "uniprot_ids"
    string pubmed_id; "pubmed_id"
    string mgd_id; "mgd_id"
    string rgd_id; "rgd_id"
    lstring lsdb; "lsdb"
    string cosmic; "cosmic"
    string omim_id; "omim_id"
    string mirbase; "mirbase"
    string homeodb; "homeodb"
    string snornabase; "snornabase"
    string bioparadigms_slc; "bioparadigms_slc"
    string orphanet; "orphanet"
    string pseudogeneOrg; "pseudogeneOrg"
    string horde_id; "horde_id"
    string merops; "merops"
    string imgt; "imgt"
    string iuphar; "iuphar"
    string kznf_gene_catalog; "kznf_gene_catalog"
    string mamitTrnadb; "mamitTrnadb"
    string cd; "cd"
    string lncrnadb; "lncrnadb"
    string enzyme_id; "enzyme_id"
    string intermediate_filament_db; "intermediate_filament_db"
    string rna_central_ids; "rna_central_ids"
    string lncipedia; "lncipedia"
    string gtrnadb; "gtrnadb"
    string agr; "agr"
    string mane_select; "mane_select"
    string gencc; "gencc"
    )
