table hgnc
"A cross-reference table between HUGO Gene Nomenclature Committee (HGNC) IDs and other database IDs."
	(
	string hgncId;	"HGNC ID"
	string symbol;	"Approved Symbol"
	string name;	"Approved Name"
	string status;	"Status"
	string locusType;	"Locus Type"
	string prvSymbols;	"Previous Symbols"
	string prvNames;	"Previous Names"
	string aliases;		"Aliases"
	string chrom;		"Reference sequence chromosome or scaffold"
	string dateApprv;	"Date Approved"
	string dateMod;		"Date Modified"
	string dateChange;	"Date Name Changed"
	string accession;	"Accession Numbers"
	string enzymeIds;	"Enzyme IDs"
	string entrezId;	"Entrez Gene ID"
	string MgdId;		"MGD ID"
	string miscIds;		"Misc IDs"
	string pubMed;		"Pubmed IDs"
	string refSeqIds;	"RefSeq IDs"
	string geneFamily;	"Gene Family Name"
	string gdbId;		"GDB ID (mapped data)"
	string entrezMapped;	"Entrez Gene ID (mapped data)"
	string omim;		"OMIM ID (mapped data)"
	string refSeqMapped;	"RefSeq (mapped data)"
	string uniProt;		"UniProt ID (mapped data)"
	)
