# jaxAllelePheno.sql was originally generated by the autoSql program, which also 
# generated jaxAllelePheno.c and jaxAllelePheno.h.  This creates the database representation of
# an object which can be loaded and saved from RAM in a fairly 
# automatic way.

#MGI Allele/Phenotype relationships.
CREATE TABLE jaxAllelePheno (
    allele varchar(255) not null,	# Allele transcript name.
    transcript varchar(255) not null,	# Transcript name (used by phenotype table).
    phenotypes longblob not null,	# Comma-separated list of phenotypes for this allele.
              #Indices
    # Not a primary key because there are case-sensitive differences...
    KEY(allele),
    INDEX(transcript)
);
