table knownMore
"Lots of auxiliary info about a known gene"
    (
    string name;        "The name displayed in the browser: OMIM, gbGeneName, or transId"
    string transId;     "Transcript id. Genie generated ID."
    string geneId;      "Gene (not transcript) Genie ID"
    uint gbGeneName;      "Connect to geneName table. Genbank gene name"
    uint gbProductName;   "Connects to productName table. Genbank product name"
    string gbProteinAcc;  "Genbank accession of protein"
    string gbNgi;         "Genbank gi of nucleotide seq."
    string gbPgi;         "Genbank gi of protein seq."
    uint omimId;          "OMIM ID or 0 if none"
    string omimName;	  "OMIM primary name"
    uint hugoId;          "HUGO Nomeclature Committee ID or 0 if none"
    string hugoSymbol;    "HUGO short name"
    string hugoName;	  "HUGO descriptive name"
    string hugoMap;       "HUGO Map position"
    uint pmId1;           "I have no idea - grabbed from a HUGO nomeids.txt"
    uint pmId2;           "Likewise, I have no idea"
    string refSeqAcc;	  "Accession of RefSeq mRNA"
    string aliases;	  "Aliases if any.  Comma and space separated list"
    uint locusLinkId;     "Locus link ID"
    string gdbId;	  "NCBI GDB database ID"
    )
