table myVariants
"An item in a myVariants type track."
    (
    uint bin;          "Bin for range index"
    string chrom;      "Reference sequence chromosome or scaffold"
    uint   chromStart; "Start position in chromosome"
    uint   chromEnd;   "End position in chromosome"
    string name;       "Name of item - up to 16 chars"
    uint  score;       "0-1000.  Higher numbers are darker."
    char[1] strand;    "+ or - for strand"
    uint   thickStart; "Start of thick part"
    uint   thickEnd;   "End position of thick part"
    uint itemRgb;      "RGB 8 bits each as in bed"
    uint blockCount;   "Number of blocks"
    int[blockCount] blockSizes; "Comma separated list of block sizes"
    int[blockCount] chromStarts; "Start positions relative to chromStart"
    lstring description; "Longer item description"
    string db;         "database name of this annotation"
    string ref;        "reference allele"
    string alt;        "alternate allele"
    string project;    "project name for grouping variants"
    string mouseover;  "short mouseover text for hover display"
    uint id;           "Unique ID for item"
    ) 