table netAlign
"alignment portion of net file"
(
string type;       "fill or gap"
string tName;       "Human Chrom"
uint level;         "level of alignment"
uint tStart;       "Start on Human"
uint tEnd;         "End on Human"
string qName;   "Mouse Chromosome"
char[1] strand; "+ direction matches - opposite"
uint qStart;       "Start on Mouse"
uint qEnd;         "End on Mouse"
uint score;        "score"
uint chainId;        "chain Id"
uint qOver;        "overlap with parent gap on query side(inverts)"
uint qFar;        "local or tandem"
uint qDup;        "two or more copies in query region"
uint tN;        "unsequenced bases on target"
uint qN;        "unsequenced bases on query"
uint tR;        "repeatMasker bases on target"
uint qR;        "repeatMasker bases on query"
uint tNewR;        "lineage specific repeats on target"
uint qNewR;        "lineage specific repeats on query"
uint tOldR;        "bases of ancient repeats on target"
uint qOldR;        "bases of ancient repeats on query"
uint tTrf;        "bases of Tandam repeats on target"
uint qTrf;        "bases of Tandam repeats on query"
)
