hgsql hg13 <regrp.sql
hgsql hg12 <regrp.sql
hgsql hg11 <regrp.sql
hgsql hg10 <regrp.sql
hgsql hg9 <regrp.sql
hgsql hg8 <regrp.sql
hgsql hg7 <regrp.sql
hgsql hg6 <regrp.sql
hgsql mm2 <regrp.sql
hgsql mm1 <regrp.sql
hgsql rn1 <regrp.sql
