table rgdGene2Raw
"Raw data GENES_RAT from RGD"
(
string 	GENE_RGD_ID;	"the RGD_ID of the gene"
string 	SYMBOL;	"official gene symbol"
string 	NAME;	"gene name"
string 	GENE_DESC;	"gene description (if available)"
string 	CHROMOSOME_CELERA;	"chromosome for Celera assembly"
string 	CHROMOSOME_OLD_REF;	"chromosome for the old reference assembly"
string 	CHROMOSOME_NEW_REF;	"chromosome for the current reference assembly"
string 	FISH_BAND;	"fish band information"
string 	START_POS_CELERA;	"start position for Celera assembly"
string 	STOP_POS_CELERA;	"stop position for Celera assembly"
string 	STRAND_CELERA;	"strand information for Celera assembly"
string 	START_POS_OLD_REF;	"start position for old reference assembly"
string 	STOP_POS_OLD_REF;	"stop position for old reference assembly"
string 	STRAND_OLD_REF;	"strand information for old reference assembly"
string 	START_POS_NEW_REF;	"start position for current reference assembly"
string 	STOP_POS_NEW_REF;	"stop position for current reference assembly"
string 	STRAND_NEW_REF;	"strand information for current reference assembly"
string 	CURATED_REF_RGD_ID;	"RGD_ID of paper(s) on gene"
string 	CURATED_REF_PUBMED_ID;	"PUBMED_ID of paper(s) on gene"
string 	UNCURATED_PUBMED_ID;	"other PUBMED ids"
string 	ENTREZ_GENE;	"EntrezGene id"
string 	UNIPROT_ID;	"UniProtKB id(s)"
string 	UNCURATED_REF_MEDLINE_ID;	"Uncurated Ref Medline ID"
string 	GENBANK_NUCLEOTIDE;	"GenBank Nucleotide ID(s)"
string 	TIGR_ID;	"TIGR ID(s)"
string 	GENBANK_PROTEIN;	"GenBank Protein ID(s)"
string 	UNIGENE_ID;	"UniGene ID(s)"
string 	SSLP_RGD_ID;	"RGD_ID(s) of SSLPS associated with given gene"
string 	SSLP_SYMBOL;	"SSLP symbol"
string 	OLD_SYMBOL;	"old symbol alias(es)"
string 	OLD_NAME;	"old name alias(es)"
string 	QTL_RGD_ID;	"RGD_ID(s) of QTLs associated with given gene"
string 	QTL_SYMBOL;	"QTL symbol"
string 	NOMENCLATURE_STATUS;	"nomenclature status"
string 	SPLICE_RGD_ID;	"RGD_IDs for gene splices"
string 	SPLICE_SYMBOL;	"Splice Symbol"
string 	GENE_TYPE;	"gene type"
string 	ENSEMBL_ID;	"Ensembl Gene ID"
)
