# raw data file downloaded from RGD for RGD Genes
CREATE TABLE rgdGene2Raw (
gene_rgd_id varchar(255),
symbol varchar(255),
name varchar(255),
gene_desc text,
chromosome_celera varchar(255),
chromosome_31 varchar(255),
chromosome_34 varchar(255),
fish_band varchar(255),
start_pos_celera varchar(255),
stop_pos_celera varchar(255),
strand_celera varchar(255),
start_pos_31 varchar(255),
stop_pos_31 varchar(255),
strand_31 varchar(255),
start_pos_34 varchar(255),
stop_pos_34 varchar(255),
strand_34 varchar(255),
curated_ref_rgd_id text,
curated_ref_pubmed_id text,
uncurated_pubmed_id text,
ratmap_id varchar(255),
entrez_gene varchar(255),
uniprot_id text,
rhdb_id text,
uncurated_ref_medline_id text,
genbank_nucleotide text,
tigr_id text,
genbank_protein text,
unigene_id text,
gdb_id text,
sslp_rgd_id text,
sslp_symbol text,
old_symbol text,
old_name text,
qtl_rgd_id text,
qtl_symbol text,
nomenclature_status text,
splice_rgd_id text,
splice_symbol text,
gene_type varchar(255),
ensembl_id text,
    KEY(gene_rgd_id),
    KEY(symbol)
);
