table rmskOut
"RepeatMasker .out record"
    (
    uint swScore;       "Smith Waterman alignment score"
    uint milliDiv;      "Base mismatches in parts per thousand"
    uint milliDel;      "Bases deleted in parts per thousand"
    uint milliIns;      "Bases inserted in parts per thousand"
    string genoName;    "Genomic sequence name"
    uint genoStart;     "Start in genomic sequence"
    uint genoEnd;       "End in genomic sequence"
    int  genoLeft;      "-#bases after match in genomic sequence"
    char[1] strand;     "Relative orientation + or -"
    string repName;     "Name of repeat"
    string repClass;    "Class of repeat"
    string repFamily;   "Family of repeat"
    int repStart;       "Start (if strand is +) or -#bases after match (if strand is -) in repeat sequence"
    uint repEnd;        "End in repeat sequence"
    int repLeft;        "-#bases after match (if strand is +) or start (if strand is -) in repeat sequence"
    char[1] id;         "First digit of id field in RepeatMasker .out file. Best ignored."
    )
