table rmskOut
"RepeatMasker .out record"
    (
    uint swScore;       "Smith Waterman alignment score"
    uint milliDiv;      "Base mismatches in parts per thousand"
    uint milliDel;      "Bases deleted in parts per thousand"
    uint milliIns;      "Bases inserted in parts per thousand"
    string genoName;    "Genomic sequence name"
    uint genoStart;     "Start in genomic sequence"
    uint genoEnd;       "End in genomic sequence"
    int  genoLeft;      "Size left in genomic sequence"
    char[1] strand;     "Relative orientation + or -"
    string repName;     "Name of repeat"
    string repClass;    "Class of repeat"
    string repFamily;   "Family of repeat"
    int repStart;       "Start in repeat sequence"
    uint repEnd;        "End in repeat sequence"
    int repLeft;        "Size left in repeat sequence"
    char[1] id;         "'*' or ' '.  I don't know what this means"
    )
