# sargassoSeaXra.sql was originally generated by the autoSql program, which also 
# generated sargassoSeaXra.c and sargassoSeaXra.h.  This creates the database representation of
# an object which can be loaded and saved from RAM in a fairly 
# automatic way.

#Table storing the codes and positional info for blast runs.
CREATE TABLE sargassoSeaXra (
    qName varchar(255) not null,	# Name of item
    code char(1) not null,	# Code
    evalue varchar(255) not null,	# evalue
    GI int unsigned not null,	# GI Number
    PI float not null,	# Percent Identity
    length int unsigned not null,	# Alignment length
    gap int unsigned not null,	# gap length
    score int unsigned not null,	# score from evalue
    queryseqstart int unsigned not null,	# Where alignment begins
    queryseqend int unsigned not null,	# Where alignment ends
    species char(255) not null,	# Code
    thisseqstart int unsigned not null,	# Where alignment in sSea begins
    thisseqend int unsigned not null,	# Where alignment in sSea ends
              #Indices
    INDEX(qName)
);
