# scopDes.sql was originally generated by the autoSql program, which also 
# generated scopDes.c and scopDes.h.  This creates the database representation of
# an object which can be loaded and saved from RAM in a fairly 
# automatic way.

#Structural Classification of Proteins Description. See Lo Conte, Brenner et al. NAR 2002
CREATE TABLE scopDes (
    sunid int not null,	# Unique integer
    type char(2) not null,	# Type.  sf=superfamily, fa = family, etc.
    sccs varchar(255) not null,	# Dense hierarchy info.
    sid varchar(255) not null,	# Older ID.
    description longblob not null,	# Descriptive text.
              #Indices
    PRIMARY KEY(sunid)
);
