table simpleRepeat
"Describes the Simple Tandem Repeats"
   (
   string chrom;      	"Human chromosome or FPC contig"
   uint   chromStart; 	"Start position in chromosome"
   uint   chromEnd;   	"End position in chromosome"
   string name;       	"Simple Repeats tag name"
   uint   period;     	"Length of repeat unit"
   float  copyNum;    	"Mean number of copies of repeat"
   uint   consensusSize;	"Length of consensus sequence"
   uint   perMatch;  	"Percentage Match"
   uint   perIndel;  	"Percentage Indel"
   uint   score; 	"Score between  and .  Best is ."
   uint   A;  	"Number of A's in repeat unit"
   uint   C;  	"Number of C's in repeat unit"
   uint   G;  	"Number of G's in repeat unit"
   uint   T;  	"Number of T's in repeat unit"
   float   entropy;  	"Entropy"
   lstring sequence;    	"Sequence of repeat unit element"
   )
