table simpleRepeat
"Describes the Simple Tandem Repeats"
   (
   string chrom;      	"Reference sequence chromosome or scaffold"
   uint   chromStart; 	"Start position in chromosome"
   uint   chromEnd;   	"End position in chromosome"
   string name;       	"Simple Repeats tag name"
   uint   period;     	"Length of repeat unit"
   float  copyNum;    	"Mean number of copies of repeat"
   uint   consensusSize;	"Length of consensus sequence"
   uint   perMatch;  	"Percentage Match"
   uint   perIndel;  	"Percentage Indel"
   uint   score; 	"Alignment Score = 2*match-7*mismatch-7*indel; minscore=50"
   uint   A;  	"Percent of A's in repeat unit"
   uint   C;  	"Percent of C's in repeat unit"
   uint   G;  	"Percent of G's in repeat unit"
   uint   T;  	"Percent of T's in repeat unit"
   float   entropy;  	"Entropy"
   lstring sequence;    	"Sequence of repeat unit element"
   )
