table snpOrthoPanTroRheMac
"Orthologous alleles in chimp and rhesus macaque"
    (
    string  chrom;         "Chromosome"
    uint    chromStart;    "Start position in chrom"
    uint    chromEnd;      "End position in chrom"
    string  name;          "Reference SNP identifier from dbSnp"
    string  humanObserved; "Observed alleles in human SNP"
    char[1] humanAllele;   "Reference allele for human SNP"
    char[1] humanStrand;   "Strand of human SNP annotation"
    string  chimpChrom;    "Chimp chromosome to which the human SNP is mapped"
    uint    chimpStart;    "Start position on chimpChrom"
    uint    chimpEnd;      "End position on chimpChrom"
    char[1] chimpAllele;   "Reference allele for chimp SNP"
    char[1] chimpStrand;   "Strand of chimp SNP annotation"
    string  macaqueChrom;  "Macaque chromosome to which the human SNP is mapped"
    uint    macaqueStart;  "Start position on macaqueChrom"
    uint    macaqueEnd;    "End position on macaqueChrom"
    char[1] macaqueAllele; "Reference allele for macaque SNP"
    char[1] macaqueStrand; "Strand of macaque SNP annotation"
    )
