table tigrCmrGene
"For TIGR CMR genes tracks"
    (
    string tigrLocus;      "TIGR locus"
    lstring tigrCommon;    "TIGR Common Name"
    string tigrGene;       "TIGR Gene Symbol"
    string tigrECN;        "TIGR Enzyme Commission Number"
    string primLocus;      "Primary Locus Name"
    uint tigr5p;           "TIGR 5' end"
    uint tigr3p;           "TIGR 3' end"
    uint tigrLength;       "TIGR sequence length"
    uint tigrPepLength;    "TIGR Protein length"
    lstring tigrMainRole;  "TIGR Main Role"
    lstring tigrSubRole;   "TIGR Sub Role"
    string swissProt;      "SwissProt TrEMBL Accession"
    string genbank;        "Genbank ID"
    float tigrMw;          "Molecular Weight"
    float tigrPi;          "Isoelectric point (I think)"
    float tigrGc;          "GC content"
    )
