LIST=\
wgEncodeHudsonalphaChipSeq.ra\
wgEncodeYaleChIPseq.ra\
wgEncodeBroadChipSeq.ra\
wgEncodeChromatinMap.ra\
wgEncodeUwChIPSeq.ra\
wgEncodeUwDGF.ra\
wgEncodeUwDnaseSeq.ra\
wgEncodeCaltechRnaSeq.ra\
wgEncodeReg.ra\
wgEncodeUwAffyExonArray.ra\
wgEncodeSunyalbanyRnaGeneChip.ra\
wgEncodeBuOrchid.ra\
wgEncodeGisPet.ra\
wgEncodeHudsonalphaMethyl27.ra\

include ../../../../makefile.metaDb
