all:
	cd fatont4 && ${MAKE}
	cd gbtofa && ${MAKE}
	cd geniegff && ${MAKE}
	cd gffgenes && ${MAKE}
	cd moresyn && ${MAKE}
	cd gb2cdi && ${MAKE}
	cd wabToSt && ${MAKE}

compile::
	cd fatont4 && ${MAKE} compile
	cd gbtofa && ${MAKE} compile
	cd geniegff && ${MAKE} compile
	cd gffgenes && ${MAKE} compile
	cd moresyn && ${MAKE} compile
	cd gb2cdi && ${MAKE} compile
	cd wabToSt && ${MAKE} compile

clean::
	cd fatont4 && ${MAKE} clean
	cd gbtofa && ${MAKE} clean
	cd geniegff && ${MAKE} clean
	cd gffgenes && ${MAKE} clean
	cd moresyn && ${MAKE} clean
	cd gb2cdi && ${MAKE} clean
	cd wabToSt && ${MAKE} clean
