#!/bin/sh

for T in hotnews chado shapes
do
    autoDtd test/${T}/in.xml test/${T}/out.dtd \
	test/${T}/out.stats -tree=test/${T}/out.tree -atree=test/${T}/out.atree
    diff test/${T}/expected.dtd test/${T}/out.dtd
    diff test/${T}/expected.stats test/${T}/out.stats
    diff test/${T}/expected.tree test/${T}/out.tree
    diff test/${T}/expected.atree test/${T}/out.atree
done

#	$Id: doTest,v 1.4 2005/12/20 17:55:27 kent Exp $
