#!/bin/csh -ef
mkdir -p nib
faToNib -softMask fa/mCreaGeno.fa nib/mCreaGeno.nib
faToNib -softMask fa/hCreaGeno.fa nib/hCreaGeno.nib
lavToAxt crea.lav nib nib crea.axt
cmp crea.axt expected/crea.axt
faToTwoBit fa/*.fa crea.2bit
lavToAxt crea.lav crea.2bit crea.2bit crea.axt
cmp crea.axt expected/crea.axt
echo looks good 
exit 0
