kentSrc = ../..
include ../../inc/common.mk

compile:
	rm -f ${DESTBINDIR}/trackDbIndexBb
	cp -p trackDbIndexBb ${DESTBINDIR}/trackDbIndexBb

clean:
	cd tests && ${MAKE} clean

test:
	cd tests && ${MAKE}
