
## makefile definitions for the 'zoonomia' assembly hubs

destDir=/hive/data/genomes/asmHubs/zoonomia
srcDir=${HOME}/kent/src/hg/makeDb/doc/zoonomiaAsmHub
orderList=$(CURDIR)/zoonomia.orderList.tsv

indexName=index
testIndexName=testIndex
statsName=asmStats
testStatsName=testAsmStats
dataName=trackData
testDataName=testTrackData
genomesTxt=genomes
hubFile=hub
testHubFile=testHub
hubTxtFile=hub.txt

# these names trigger special behavior in the index page creation scripts:
Name=Zoonomia
name=zoonomia

# Perigord truffle
defaultAssembly=GCF_000151645.1_ASM15164v1

include ../asmHubs/asmHubs.mk
