#!/bin/csh -f

# run on test file, diff with "golden" file

# check version, type, and direction fields of mrna table
# this test input should have EST in type field
${HOME}/bin/i386/hgLoadRna -test add -type=EST fr1 test.fa test.ra \
                         >& /dev/null

awk '{print $2, $4, $5}' < mrna.tab > mrna.out
diff mrna.out mrna.out.gold > /dev/null
set status1 = $status

# check name field of tissue table
# this test input has a trailing backslash
awk -F\\t '{print $2}' < tissue.tab > tissue.out
diff tissue.out tissue.out.gold > /dev/null
set status2 = $status

# test mRNA type -- should load descriptions
${HOME}/bin/i386/hgLoadRna -test add -type=mRNA fr1 test.fa test.ra >&/dev/null
awk -F\\t '{print $2}' < description.tab > description.out
diff description.out description.out.gold > /dev/null
set status3 = $status

# test that xenoMrna doesn't by default load descriptions
${HOME}/bin/i386/hgLoadRna -test add -type=xenoMrna fr1 test.fa test.ra \
                         >& /dev/null
awk -F\\t '{print $2}' < description.tab > description.out
diff description.out /dev/null > /dev/null
set status4 = $status

# test -xenoDescriptions option to load descriptions
${HOME}/bin/i386/hgLoadRna -test add -type=xenoRNA -xenoDescriptions fr1 \
                        test.fa test.ra >& /dev/null
awk -F\\t '{print $2}' < description.tab > description.out
diff description.out description.out.gold > /dev/null
set status4 = $status

if ($status1 || $status2 || $status3 || $status4) then
    echo '*** FAIL ***'
    exit 1
endif
rm -f *.tab *.out
exit 0
