table shortFrags
"BED6+21 A format used in wgEncodeCshlShortRnaSeq with many fields"
(
    string chrom;        "Reference sequence chromosome or scaffold"
    uint   chromStart;   "Start position in chromosome"
    uint   chromEnd;     "End position in chromosome"
    string name;	 "Name given to a region (preferably unique). Use . if no name is assigned"
    uint   score;        "Indicates how dark the peak will be displayed in the browser (0-1000) "
    char[1]  strand;     "+ or - or . for unknown"
    string exp1;        "expansion field 1"
    string exp2;        "expansion field 2"
    string exp3;        "expansion field 3"
    string exp4;        "expansion field 4"
    string exp5;        "expansion field 5"
    string exp6;        "expansion field 6"
    string exp7;        "expansion field 7"
    string exp8;        "expansion field 8"
    string exp9;        "expansion field 9"
    string exp10;        "expansion field 10"
    string exp11;        "expansion field 11"
    string exp12;        "expansion field 12"
    string exp13;        "expansion field 13"
    string exp14;        "expansion field 14"
    string exp15;        "expansion field 15"
    int arraySize;        "array size for next 4"
    lstring exp17;        "expansion field 17"
    lstring exp18;        "expansion field 18"
    lstring exp19;        "expansion field 19"
    lstring exp20;        "expansion field 20"
    string exp21;        "expansion field 21"
)
