table umdTp53
"UMD TP53 Variant Database (p53.fr) — one row per unique TP53 variant"
    (
    string  chrom;             "Chromosome"
    uint    chromStart;        "Start position"
    uint    chromEnd;          "End position"
    string  name;              "HGVS cDNA nomenclature (NM_000546.5)"
    uint    score;             "Unused"
    char[1] strand;            "Strand (TP53 is on minus strand)"
    uint    thickStart;        "Display thick start"
    uint    thickEnd;           "Display thick end"
    uint    reserved;          "RGB color reflecting pathogenicity"
    lstring cDnaFull;          "Full HGVS cDNA nomenclature (when the displayed name was shortened)"
    string  proteinChange;     "Protein change on canonical TP53 alpha (NP_000537.3)"
    string  pathogenicity;     "Curator pathogenicity classification"
    string  variantClassification; "Effect class (Missense / Nonsense / Synonymous / Frameshift / Splice / ...)"
    string  variantType;       "Variant type (SNP / DEL / INS / DNP / TNP / ONP)"
    string  domain;            "TP53 protein domain"
    string  structure;         "Structural motif (Cho et al. 1994)"
    string  ptm;               "Post-translational modification site, if any"
    string  umdId;             "UMD database identifier"
    string  cosmicId;          "COSMIC mutation ID"
    string  snpId;             "dbSNP rs ID"
    lstring activityComment;   "Residual transactivation activity summary (Kato et al. 8-promoter assay)"
    string  waf1Pct;           "WAF1 promoter activity (% of WT)"
    string  mdm2Pct;           "MDM2 promoter activity (% of WT)"
    string  baxPct;            "BAX promoter activity (% of WT)"
    string  p14333sPct;        "14-3-3-sigma promoter activity (% of WT)"
    string  aipPct;            "AIP promoter activity (% of WT)"
    string  gadd45Pct;         "GADD45 promoter activity (% of WT)"
    string  noxaPct;           "NOXA promoter activity (% of WT)"
    string  p53r2Pct;          "p53R2 promoter activity (% of WT)"
    float   tumorFreq;         "Frequency in tumors (%)"
    string  cellLineFreq;      "Frequency in cell lines (%)"
    string  somaticFreq;       "Frequency among somatic cases (%)"
    string  germlineFreq;      "Frequency among germline cases (%)"
    uint    recordsNumber;     "Total occurrences in the database"
    string  siftScore;         "SIFT score"
    string  siftPrediction;    "SIFT prediction"
    string  polyphenHumVar;    "Polyphen-2 HumVar prediction"
    string  polyphenHumDiv;    "Polyphen-2 HumDiv prediction"
    string  mutAssessorScore;  "MutationAssessor score"
    string  mutAssessorPrediction; "MutationAssessor prediction"
    string  proveanScore;      "PROVEAN score"
    string  proveanPrediction; "PROVEAN prediction"
    string  condel;            "Condel prediction"
    string  condelScore;       "Condel score"
    string  mutpredSpliceScore; "MutPred Splice general score"
    string  mutpredSplicePrediction; "MutPred Splice prediction label"
    lstring mutpredSpliceHypotheses; "MutPred Splice confident hypotheses"
    lstring commentFrequency;  "Curator note on variant frequency"
    lstring commentOutliers;   "Curator note on outlier publications"
    lstring commentSplicing;   "Curator note on splicing"
    lstring finalComment;      "Curator final summary"
    lstring _mouseOver;        "Pre-built hover text"
    )
