table akbariIdmr
"Imprinted differentially methylated regions compiled by Akbari et al. 2023"
    (
    string chrom;                 "Chromosome (or contig, scaffold, etc.)"
    uint   chromStart;            "Start position in chromosome"
    uint   chromEnd;              "End position in chromosome"
    string name;                  "Genes at or near the region"
    uint   score;                 "Score (unused, always 0)"
    char[1] strand;               "Strand, not applicable, always ."
    uint   thickStart;            "Start of thick display"
    uint   thickEnd;              "End of thick display"
    uint   reserved;              "Color, set from the methylated allele"
    string methylatedAllele;      "Methylated Allele|Parental copy that carries the methylation, so the silenced one"
    string gene;                  "First Gene|First gene listed for this region, used as the short label"
    string studies;               "Source Studies|Earlier genome-wide studies that reported this region"
    uint   studyCount;            "Number of Studies|How many of the five source studies reported this region"
    string evidence;              "Evidence|Reported by several studies, or by one study and confirmed against public methylomes"
    string indivExamined;         "Individuals Examined|Blood methylomes in which the region could be tested"
    string indivPartialMeth;      "Individuals Partially Methylated|Of those, how many showed partial methylation"
    string pctIndivPartialMeth;   "Percent Individuals|Percent of testable individuals with partial methylation"
    string tissuesExamined;       "Tissues Examined|Tissue methylomes in which the region could be tested"
    string tissuesPartialMeth;    "Tissues Partially Methylated|Of those, how many showed partial methylation"
    string pctTissuesPartialMeth; "Percent Tissues|Percent of testable tissues with partial methylation"
    )
