table kaplanParentalAsm
"Regions whose methylation follows the parent of origin rather than the DNA sequence (Rosenski et al. 2025)"
    (
    string  chrom;          "Reference sequence chromosome or scaffold"
    uint    chromStart;     "Start position in chromosome"
    uint    chromEnd;       "End position in chromosome"
    string  name;           "Control region name, or the imprinted gene the region sits next to"
    uint    score;          "Not used, always 0"
    char[1] strand;         "Not applicable, always ."
    uint    thickStart;     "Start of where display should be thick"
    uint    thickEnd;       "End of where display should be thick"
    uint    itemRgb;        "Colour by the gamete in which the methylation mark is laid down"
    string  regionType;     "Region type|a known imprinting control region, a new region beside a known imprinted gene, or a region reported for the first time here"
    string  icrType;        "Type|germline DMR methylated in the oocyte or in sperm, or a DMR that acquires its methylation after fertilisation"
    string  icrName;        "Control region|name of the known imprinting control region this region corresponds to"
    lstring icrGenes;       "Control region genes|imprinted genes linked to that control region in the literature"
    lstring imprintedGenes; "Imprinted genes nearby|known imprinted genes within 200 kb"
    lstring snps;           "ASM SNPs|dbSNP identifiers of the heterozygous SNPs used to phase the two alleles"
    uint    snpCount;       "SNP count|number of such SNPs in the region"
    lstring alleles;        "Alleles|the two alleles of each SNP"
    lstring cellTypes;      "Cell types|cell types in which allele-specific methylation was seen"
    uint    cellTypeCount;  "Cell type count|number of cell types supporting the region"
    string  minAdjP;        "Best adjusted p|smallest adjusted p-value over the SNPs and cell types of the region"
    string  methOocyte;     "Methylation in oocyte|mean methylation of the region in published oocyte methylomes"
    string  methSperm;      "Methylation in sperm|mean methylation of the region in published sperm methylomes"
    string  methIcm;        "Methylation in inner cell mass|mean methylation of the region in the inner cell mass"
    string  methBlastocyst; "Methylation in blastocyst|mean methylation of the region in the blastocyst"
    string  liftNote;      "Lifting note|set when hg38 inserted sequence inside the region, so that its boundaries no longer match the published hg19 ones"
    )
