char formQ[] =
"\n"
"<h1> Push Queue Form </h1>\n"
"\n"
"<p style=\"color:red\"><!msg></p>\n"
"\n"
"<form ACTION=\"/cgi-bin/qaPushQ\" NAME=\"mainForm\" METHOD=\"POST\">\n"
"\n"
"\n"
"<input TYPE=\"hidden\" NAME=\"action\"   VALUE=\"post\"  >\n"
"<input TYPE=\"hidden\" NAME=\"qid\"      VALUE=\"<!qid>\">\n"
"<input TYPE=\"hidden\" NAME=\"initdate\" VALUE=\"<!initdate>\">\n"
"<input TYPE=\"hidden\" NAME=\"cb\"       VALUE=\"<!cb>\">\n"
"\n"
"<table cellpadding=6>\n"
"\n"
"<tr><td align=\"right\">\n"
"&nbsp;\n"
"</td>\n"
"<td>\n"
"<!submitbutton>\n"
"<!delbutton>\n"
"<!pushbutton>\n"
"<!clonebutton>\n"
"<!bouncebutton>\n"
"<!lockbutton>\n"
"<!refreshlink>\n"
"<!cancellink>\n"
"<a href=\"/cgi-bin/qaPushQ?action=showEditHelp&qid=<!qid>&cb=<!cb>\" target=\"_blank\">HELP</a>\n"
"</td></tr>\n"
"\n"
"<tr><td align=\"right\">\n"
"Priority:\n"
"</td>\n"
"<td>\n"
"<select NAME=\"priority\" SIZE=1 <!DISABLED>>\n"
"<option <!sel-priority-A> value=\"A\">A</option>\n"
"<option <!sel-priority-B> value=\"B\">B</option>\n"
"<option <!sel-priority-C> value=\"C\">C</option>\n"
"<option <!sel-priority-D> value=\"D\">D</option>\n"
"<option <!sel-priority-L> value=\"L\">L</option>\n"
"</select>\n"
"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Queue Id: <!qid> \n"
"</td></tr>\n"
"\n"
"<tr><td align=\"right\">\n"
"Date Opened:\n"
"</td>\n"
"<td>\n"
"<input TYPE=\"text\" NAME=\"qadate\" SIZE=\"10\" VALUE=\"<!qadate>\" <!READONLY>>\n"
"&nbsp;&nbsp;&nbsp;&nbsp;Initial submission: <!initdate>\n"
"</td></tr>\n"
"\n"
"<tr><td align=\"right\">\n"
"New track?:\n"
"</td>\n"
"<td>\n"
"<select NAME=\"newYN\" SIZE=1 <!DISABLED>>\n"
"<option <!sel-newYN-N> value=\"N\">N</option>\n"
"<option <!sel-newYN-Y> value=\"Y\">Y</option>\n"
"</select>\n"
"</td></tr>\n"
"\n"
"<tr><td align=\"right\">\n"
"Track:\n"
"</td>\n"
"<td>\n"
"<input TYPE=\"text\" NAME=\"track\" SIZE=\"60\" VALUE=\"<!track>\" <!READONLY>>\n"
"(shortLabel)\n"
"</td></tr>\n"
"\n"
"<tr><td align=\"right\">\n"
"Release Log:\n"
"</td>\n"
"<td>\n"
"<TEXTAREA NAME=\"releaseLog\", ROWS=\"3\", COLS=\"60\" <!READONLY>><!releaseLog></TEXTAREA>\n"
"<br>\n"
"Put main identifier, usually short label followed by comments in parentheses if any.\n"
"Leave blank if release log entry not wanted. \n"
"This will typically become a single line in the Release Log.\n"
"</td></tr>\n"
"\n"
"<tr><td align=\"right\">\n"
"Databases:\n"
"</td>\n"
"<td>\n"
"<input TYPE=\"text\" NAME=\"dbs\" SIZE=\"60\" VALUE=\"<!dbs>\" <!READONLY>>\n"
"</td></tr>\n"
"\n"
"<tr><td align=\"right\">\n"
"Tables:\n"
"</td>\n"
"<td>\n"
"<TEXTAREA NAME=\"tbls\", ROWS=\"5\", COLS=\"60\" <!READONLY>><!tbls></TEXTAREA>\n"
"</td></tr>\n"
"\n"
"<tr><td align=\"right\">\n"
"CGIs:\n"
"</td>\n"
"<td>\n"
"<TEXTAREA NAME=\"cgis\", ROWS=\"5\", COLS=\"60\" <!READONLY>><!cgis></TEXTAREA>\n"
"</td></tr>\n"
"\n"
"<tr><td align=\"right\">\n"
"Files:\n"
"</td>\n"
"<td>\n"
"<TEXTAREA NAME=\"files\", ROWS=\"5\", COLS=\"60\" <!READONLY>><!files></TEXTAREA>\n"
"</td></tr>\n"
"\n"
"<tr><td align=\"right\">\n"
"Size(MB):\n"
"</td>\n"
"<td>\n"
"<input TYPE=\"text\" NAME=\"sizeMB\" SIZE=\"10\" VALUE=\"<!sizeMB>\" <!READONLY>>\n"
"<!sizesbutton>\n"
"</td></tr>\n"
"\n"
"<tr><td align=\"right\">\n"
"Current Location:\n"
"</td><td>\n"
"<select NAME=\"currLoc\" SIZE=1 <!DISABLED>>\n"
"<option <!sel-currLoc-hgwdev> value=\"hgwdev\">hgwdev</option>\n"
"<option <!sel-currLoc-hgwbeta> value=\"hgwbeta\">hgwbeta</option>\n"
"</select>\n"
"\n"
"</td></tr>\n"
"\n"
"<tr><td align=\"right\">\n"
"Makedoc verified?: </td>\n"
"<td>\n"
"<select NAME=\"makeDocYN\" SIZE=1 <!DISABLED>>\n"
"<option <!sel-makeDocYN-N> value=\"N\">N</option>\n"
"<option <!sel-makeDocYN-Y> value=\"Y\">Y</option>\n"
"</select>\n"
"</td></tr>\n"
"\n"
"<tr><td align=\"right\">\n"
"Online Help:\n"
"</td>\n"
"<td>\n"
"<input TYPE=\"text\" NAME=\"onlineHelp\" SIZE=\"60\" VALUE=\"<!onlineHelp>\" <!READONLY>>\n"
"</select>\n"
"\n"
"</td></tr>\n"
"\n"
"<tr><td align=\"right\">\n"
"Index verified?: </td>\n"
"<td>\n"
"<select NAME=\"ndxYN\" SIZE=1 <!DISABLED>>\n"
"<option <!sel-ndxYN-N> value=\"N\">N</option>\n"
"<option <!sel-ndxYN-Y> value=\"Y\">Y</option>\n"
"</select>\n"
"</td></tr>\n"
"\n"
"<tr><td align=\"right\">\n"
"All.Joiner verified?: </td>\n"
"<td>\n"
"<select NAME=\"joinerYN\" SIZE=1 <!DISABLED>>\n"
"<option <!sel-joinerYN-N> value=\"N\">N</option>\n"
"<option <!sel-joinerYN-Y> value=\"Y\">Y</option>\n"
"</select>\n"
"</td></tr>\n"
"\n"
"<tr><td align=\"right\">\n"
"Status:  \n"
"</td>\n"
"<td>\n"
"<TEXTAREA NAME=\"stat\", ROWS=\"5\", COLS=\"60\" <!READONLY>><!stat></TEXTAREA>\n"
"</td></tr>\n"
"\n"
"<tr><td align=\"right\">\n"
"Sponsor (local):\n"
"</td>\n"
"<td>\n"
"<input TYPE=\"text\" NAME=\"sponsor\" SIZE=\"60\" VALUE=\"<!sponsor>\" <!READONLY>>\n"
"</td></tr>\n"
"\n"
"<tr><td align=\"right\">\n"
"Reviewer:\n"
"</td>\n"
"<td>\n"
"<input TYPE=\"text\" NAME=\"reviewer\" SIZE=\"60\" VALUE=\"<!reviewer>\" <!READONLY>>\n"
"</td></tr>\n"
"\n"
"<tr><td align=\"right\">\n"
"External Source <br>or Collaborator:\n"
"</td>\n"
"<td>\n"
"<input TYPE=\"text\" NAME=\"extSource\" SIZE=\"60\" VALUE=\"<!extSource>\" <!READONLY>>\n"
"</td></tr>\n"
"\n"
"<tr><td align=\"right\">\n"
"Open Issues:\n"
"</td>\n"
"<td>\n"
"<TEXTAREA NAME=\"openIssues\", ROWS=\"5\", COLS=\"60\" <!READONLY>><!openIssues></TEXTAREA>\n"
"</td></tr>\n"
"\n"
"<tr><td align=\"right\">\n"
"Notes:\n"
"</td>\n"
"<td>\n"
"<TEXTAREA NAME=\"notes\", ROWS=\"5\", COLS=\"60\" <!READONLY>><!notes></TEXTAREA>\n"
"</td></tr>\n"
"\n"
"<tr><td align=\"right\">\n"
"&nbsp;\n"
"</td>\n"
"<td>\n"
"<!submitbutton>\n"
"<!delbutton>\n"
"<!pushbutton>\n"
"<!clonebutton>\n"
"<!bouncebutton>\n"
"<!lockbutton>\n"
"<!refreshlink>\n"
"<!cancellink>\n"
"<a href=\"/cgi-bin/qaPushQ?action=showEditHelp&qid=<!qid>&cb=<!cb>\" target=\"_blank\">HELP</a>\n"
"</td></tr>\n"
"\n"
"</table>\n"
"\n"
"</form>\n"
"\n"
;
