#!/usr/bin/perl -w
use strict;

my $fh;
open ($fh, "<", "listSpXref2.txt") or die "Couldn't open spXref dump, $!\n";
my %spIdToOmim;
while (<$fh>) {
   chomp;
   my @f = split(/\t/);
   #spId mimId
   push(@{$spIdToOmim{$f[0]}}, $f[1]);
}
close $fh or die "Couldn't close spXref dump, $!\n";

open ($fh, "<", "listSPconnections.txt") or die "Couldn't open SPconn, $!\n";
my %uniq;
while (<$fh>) {
   chomp;
   my @f = split(/\t/);
   #varId  spId    mrna    geneSymbol
   if (exists $spIdToOmim{$f[1]}) {
      #id attrType raKey acc displayVal
      foreach my $omim (@{$spIdToOmim{$f[1]}}) {
         $uniq{"$f[0]\tgeneVarsDis\tomimTitle2\t$omim\t\n"} = 1;
      }
   }
}
close $fh or die "Couldn't close SPconn, $!\n";

foreach (keys %uniq) { print; }
exit 0;
