table mpc
"MPC track for gnomad2 on hg19"
    (
    string chrom;      "Chromosome (or contig, scaffold, etc.)"
    uint   chromStart; "Start position in chromosome"
    uint   chromEnd;   "End position in chromosome"
    string name;       "Name of item"
    uint   score;      "Score from 0-1000"
    char[1] strand;    "+ or -"
    uint thickStart;   "Start of where display should be thick (start codon)"
    uint thickEnd;     "End of where display should be thick (stop codon)"
    uint reserved;     "Used as itemRgb as of 2004-11-22"
    string gene;     "Gene Symbol"
    string geneId;     "Gencode Gene"
    string trans;     "Gencode Transcript"
    string startAa;     "From Amino Acid"
    string stopAa;     "To Amino Acid"
    string obs;     "Observed Value"
    string exp;     "Expected Value"
    string oe;     "Obs/Exp"
    string chisq;     "Chi-Square"
    string pval;     "P-Value"
    )
