table pliMetricsV4_1_1
"bed12+9 for displaying gnomAD v4.1.1 haploinsufficiency (pLoF) constraint scores"
    (
    string chrom;      "Reference sequence chromosome or scaffold"
    uint   chromStart; "Start position in chromosome"
    uint   chromEnd;   "End position in chromosome"
    string name;       "ENST or ENSG Name"
    uint   score;      "pLI score between 0-1000, or -1 for NA"
    char[1] strand;    "strand of transcript"
    uint thickStart;   "Start of where display is thick"
    uint thickEnd;     "End of where display should be thick"
    uint itemRgb;      "Color of item"
    int blockCount;    "Number of exons"
    int[blockCount] blockSizes;  "Size of each exon"
    int[blockCount] chromStarts; "0-based start position of each exon"
    string _mouseOver;  "Mouseover label"
    float _loeuf;       "LOEUF value for filters"
    float _pli;         "pLI value for filters"
    string geneName;    "Gene symbol"
    string synonymous;  "Synonymous metrics"
    string pLoF;        "Predicted Loss of Function metrics"
    string constraintFlags; "Constraint outlier flags (e.g. outlier_lof, no_exp_lof)"
    string geneFlags;   "Gene quality flags (low_exome_coverage, low_exome_mapping_quality)"
    string qualityMetrics; "Exome quality metrics: prop bp AN90, mean AS MQ, prop segdup, prop LCR"
    )
