alpha:
	cp root/updateBrowser.sh /usr/local/apache/htdocs/gbib/
	echo you can now run gbibCoreUpdateBeta on any gbib to test the update script
	echo if you are OK with the result, request a push of /usr/local/apache/htdocs/gbib/updateBrowser.sh
	echo to hgdownload
	echo To make any other changes to the GBIB, add files under /usr/local/apache/htdocs/gbib/push/
	echo which is rsynced into the GBIB on every update into / '(the root directory)'
	echo You can modify ./usr/local/apache/cgi-bin/hg.conf and the copy it to 
	echo /usr/local/apache/htdocs/gbib/push/usr/local/apache/cgi-bin/hg.conf

