alpha:
	cp root/updateBrowser.sh /usr/local/apache/htdocs/gbib/
	echo you can now run gbibCoreUpdateBeta on any gbib to test the update script
	echo if you are OK with the result, request a push of /usr/local/apache/htdocs/gbib/updateBrowser.sh
	echo to hgdownload

