/* jshint maxlen: false, unused: false */
var dbDbTree = ["root", 1, null,
[ ["cellular organisms", 131567, null,
  [ ["Eukaryota", 2759, null,
    [ ["Opisthokonta", 33154, null,
      [ ["Metazoa", 33208, null,
        [ ["Eumetazoa", 6072, null,
          [ ["Bilateria", 33213, null,
            [ ["Deuterostomia", 33511, null,
              [ ["Chordata", 7711, null,
                [ ["Craniata", 89593, null,
                  [ ["Vertebrata", 7742, null,
                    [ ["Gnathostomata", 7776, null,
                      [ ["Teleostomi", 117570, null,
                        [ ["Euteleostomi", 117571, null,
                          [ ["Sarcopterygii", 8287, null,
                            [ ["Dipnotetrapodomorpha", 1338369, null,
                              [ ["Tetrapoda", 32523, null,
                                [ ["Amniota", 32524, null,
                                  [ ["Mammalia", 40674, null,
                                    [ ["Theria", 32525, null,
                                      [ ["Eutheria", 9347, null,
                                        [ ["Boreoeutheria", 1437010, null,
                                          [ ["Euarchontoglires", 314146, null,
                                            [ ["Primate", 9443, "Primates",
                                              [ ["Haplorrhini", 376913, null,
                                                [ ["Simiiformes", 314293, null,
                                                  [ ["Catarrhini", 9526, null,
                                                    [ ["Hominoidea", 314295, null,
                                                      [ ["Hominidae", 9604, "Hominidae",
                                                        [ ["Homininae", 207598, null,
                                                          [ ["Homo", 9605, null,
                                                            [ ["Human", 9606, "Homo sapiens" ] ] ],
                                                          ["Pan", 9596, null,
                                                            [ ["Chimp", 9598, "Pan troglodytes" ],
                                                            ["Bonobo", 9597, "Pan paniscus" ] ] ],
                                                          ["Gorilla", 9592, null,
                                                            [ ["Gorilla gorilla", 9593, null,
                                                              [ ["Gorilla", 9595, "Gorilla gorilla gorilla" ] ] ] ] ] ] ],
                                                        ["Ponginae", 607660, null,
                                                          [ ["Pongo", 9599, null,
                                                            [ ["Orangutan", 9601, "Pongo abelii" ] ] ] ] ] ] ],
                                                      ["Hylobatidae", 9577, null,
                                                        [ ["Nomascus", 325165, null,
                                                          [ ["Gibbon", 61853, "Nomascus leucogenys" ] ] ] ] ] ] ],
                                                    ["Cercopithecoidea", 314294, null,
                                                      [ ["Cercopithecidae", 9527, null,
                                                        [ ["Cercopithecinae", 9528, null,
                                                          [ ["Cercocebus", 9529, null,
                                                            [ ["Sooty mangabey", 9531, "Cercocebus atys" ] ] ],
                                                          ["Chlorocebus", 392815, null,
                                                            [ ["Green monkey", 60711, "Chlorocebus sabaeus" ] ] ],
                                                          ["Macaca", 9539, null,
                                                            [ ["Crab-eating macaque", 9541, "Macaca fascicularis" ],
                                                            ["Pig-tailed macaque", 9545, "Macaca nemestrina" ],
                                                            ["Rhesus", 9544, "Macaca mulatta" ] ] ],
                                                          ["Mandrillus", 9567, null,
                                                            [ ["Drill", 9568, "Mandrillus leucophaeus" ] ] ],
                                                          ["Papio", 9554, null,
                                                            [ ["Baboon (anubis)", 9555, "Papio anubis" ],
                                                            ["Papio hamadryas", 9557, null,
                                                              [ ["Baboon (hamadryas)", 9562, "Papio hamadryas hamadryas" ] ] ] ] ] ] ],
                                                        ["Colobinae", 9569, null,
                                                          [ ["Colobus", 9570, null,
                                                            [ ["Colobus angolensis", 54131, null,
                                                              [ ["Angolan colobus", 336983, "Colobus angolensis palliatus" ] ] ] ] ],
                                                          ["Nasalis", 43779, null,
                                                            [ ["Proboscis monkey", 43780, "Nasalis larvatus" ] ] ],
                                                          ["Rhinopithecus", 542827, null,
                                                            [ ["Black snub-nosed monkey", 61621, "Rhinopithecus bieti" ],
                                                            ["Golden snub-nosed monkey", 61622, "Rhinopithecus roxellana" ] ] ] ] ] ] ] ] ] ] ],
                                                  ["Platyrrhini", 9479, null,
                                                    [ ["Aotidae", 376918, null,
                                                      [ ["Aotus", 9504, null,
                                                        [ ["Ma's night monkey", 37293, "Aotus nancymaae" ] ] ] ] ],
                                                    ["Cebidae", 9498, null,
                                                      [ ["Callitrichinae", 9480, null,
                                                        [ ["Callithrix", 9481, null,
                                                          [ ["Callithrix", 1965096, null,
                                                            [ ["Marmoset", 9483, "Callithrix jacchus" ] ] ] ] ] ] ],
                                                      ["Cebinae", 38070, null,
                                                        [ ["Cebus", 9513, null,
                                                          [ ["Cebus capucinus", 9516, null,
                                                            [ ["White-faced sapajou", 1737458, "Cebus capucinus imitator" ] ] ] ] ] ] ],
                                                      ["Saimiriinae", 378850, null,
                                                        [ ["Saimiri", 9520, null,
                                                          [ ["Saimiri boliviensis", 27679, null,
                                                            [ ["Squirrel monkey", 39432, "Saimiri boliviensis boliviensis" ] ] ] ] ] ] ] ] ] ] ] ] ],
                                                ["Tarsiiformes", 376912, null,
                                                  [ ["Tarsiidae", 9475, null,
                                                    [ ["Carlito", 1868481, null,
                                                      [ ["Tarsier", 1868482, "Carlito syrichta" ] ] ] ] ] ] ] ] ],
                                              ["Strepsirrhini", 376911, null,
                                                [ ["Lemuriformes", 376915, null,
                                                  [ ["Cheirogaleidae", 30615, null,
                                                    [ ["Microcebus", 13149, null,
                                                      [ ["Mouse lemur", 30608, "Microcebus murinus" ] ] ] ] ],
                                                  ["Indriidae", 30599, null,
                                                    [ ["Propithecus", 30600, null,
                                                      [ ["Coquerel's sifaka", 379532, "Propithecus coquereli" ] ] ] ] ],
                                                  ["Lemuridae", 9445, null,
                                                    [ ["Eulemur", 13513, null,
                                                      [ ["Black lemur", 30602, "Eulemur macaco" ],
                                                      ["Sclater's lemur", 87288, "Eulemur flavifrons" ] ] ] ] ] ] ],
                                                ["Lorisiformes", 376917, null,
                                                  [ ["Galagidae", 40297, null,
                                                    [ ["Otolemur", 30610, null,
                                                      [ ["Bushbaby", 30611, "Otolemur garnettii" ] ] ] ] ] ] ] ] ] ] ],
                                            ["Glires", 314147, null,
                                              [ ["Rodentia", 9989, null,
                                                [ ["Myomorpha", 1963758, null,
                                                  [ ["Muroidea", 337687, null,
                                                    [ ["Muridae", 10066, null,
                                                      [ ["Murinae", 39107, null,
                                                        [ ["Mus", 10088, null,
                                                          [ ["Mus", 862507, null,
                                                            [ ["Mouse", 10090, "Mus musculus" ] ] ] ] ],
                                                        ["Rattus", 10114, null,
                                                          [ ["Rat", 10116, "Rattus norvegicus" ] ] ] ] ] ] ],
                                                    ["Cricetidae", 337677, null,
                                                      [ ["Arvicolinae", 39087, null,
                                                        [ ["Microtus", 10053, null,
                                                          [ ["Prairie vole", 79684, "Microtus ochrogaster" ] ] ] ] ],
                                                      ["Cricetinae", 10026, null,
                                                        [ ["Cricetulus", 10028, null,
                                                          [ ["Chinese hamster", 10029, "Cricetulus griseus" ] ] ],
                                                        ["Mesocricetus", 10035, null,
                                                          [ ["Golden hamster", 10036, "Mesocricetus auratus" ] ] ] ] ],
                                                      ["Neotominae", 337963, null,
                                                        [ ["Peromyscus", 10040, null,
                                                          [ ["Peromyscus maniculatus", 10042, null,
                                                            [ ["Prairie deer mouse", 230844, "Peromyscus maniculatus bairdii" ] ] ] ] ] ] ] ] ],
                                                    ["Spalacidae", 337664, null,
                                                      [ ["Spalacinae", 10061, null,
                                                        [ ["Nannospalax", 30636, null,
                                                          [ ["Upper Galilee mountains blind mole rat", 1026970, "Nannospalax galili" ] ] ] ] ] ] ] ] ],
                                                  ["Dipodoidea", 1963761, null,
                                                    [ ["Dipodidae", 30648, null,
                                                      [ ["Dipodinae", 35737, null,
                                                        [ ["Jaculus", 48867, null,
                                                          [ ["Lesser Egyptian jerboa", 51337, "Jaculus jaculus" ] ] ] ] ] ] ] ] ] ] ],
                                                ["Castorimorpha", 1963757, null,
                                                  [ ["Heteromyidae", 10015, null,
                                                    [ ["Dipodomyinae", 38662, null,
                                                      [ ["Dipodomys", 10016, null,
                                                        [ ["Kangaroo rat", 10020, "Dipodomys ordii" ] ] ] ] ] ] ] ] ],
                                                ["Hystricomorpha", 33550, null,
                                                  [ ["Bathyergidae", 10167, null,
                                                    [ ["Fukomys", 423606, null,
                                                      [ ["Damara mole rat", 885580, "Fukomys damarensis" ] ] ],
                                                    ["Heterocephalus", 10180, null,
                                                      [ ["Naked mole-rat", 10181, "Heterocephalus glaber" ] ] ] ] ],
                                                  ["Caviidae", 10139, null,
                                                    [ ["Cavia", 10140, null,
                                                      [ ["Brazilian guinea pig", 37548, "Cavia aperea" ],
                                                      ["Guinea pig", 10141, "Cavia porcellus" ] ] ] ] ],
                                                  ["Chinchillidae", 10150, null,
                                                    [ ["Chinchilla", 10151, null,
                                                      [ ["Chinchilla", 34839, "Chinchilla lanigera" ] ] ] ] ],
                                                  ["Octodontidae", 10158, null,
                                                    [ ["Octodon", 10159, null,
                                                      [ ["Brush-tailed rat", 10160, "Octodon degus" ] ] ] ] ] ] ],
                                                ["Sciuromorpha", 33553, null,
                                                  [ ["Sciuridae", 55153, null,
                                                    [ ["Xerinae", 337726, null,
                                                      [ ["Marmotini", 337730, null,
                                                        [ ["Ictidomys", 1141640, null,
                                                          [ ["Squirrel", 43179, "Ictidomys tridecemlineatus" ] ] ] ] ] ] ] ] ] ] ] ] ],
                                              ["Lagomorpha", 9975, null,
                                                [ ["Leporidae", 9979, null,
                                                  [ ["Oryctolagus", 9984, null,
                                                    [ ["Rabbit", 9986, "Oryctolagus cuniculus" ] ] ] ] ],
                                                ["Ochotonidae", 9976, null,
                                                  [ ["Ochotona", 9977, null,
                                                    [ ["Pika", 9978, "Ochotona princeps" ] ] ] ] ] ] ] ] ],
                                            ["Dermoptera", 30656, null,
                                              [ ["Cynocephalidae", 30657, null,
                                                [ ["Galeopterus", 482536, null,
                                                  [ ["Malayan flying lemur", 482537, "Galeopterus variegatus" ] ] ] ] ] ] ],
                                            ["Scandentia", 9392, null,
                                              [ ["Tupaiidae", 9393, null,
                                                [ ["Tupaia", 9394, null,
                                                  [ ["Chinese tree shrew", 246437, "Tupaia chinensis" ],
                                                  ["Tree shrew", 37347, "Tupaia belangeri" ] ] ] ] ] ] ] ] ],
                                          ["Laurasiatheria", 314145, null,
                                            [ ["Insectivora", 9362, null,
                                              [ ["Erinaceidae", 9363, null,
                                                [ ["Erinaceinae", 30577, null,
                                                  [ ["Erinaceus", 9364, null,
                                                    [ ["Hedgehog", 9365, "Erinaceus europaeus" ] ] ] ] ] ] ],
                                              ["Soricidae", 9376, null,
                                                [ ["Soricinae", 183663, null,
                                                  [ ["Sorex", 9379, null,
                                                    [ ["Shrew", 42254, "Sorex araneus" ] ] ] ] ] ] ],
                                              ["Talpidae", 9373, null,
                                                [ ["Condylura", 143301, null,
                                                  [ ["Star-nosed mole", 143302, "Condylura cristata" ] ] ] ] ] ] ],
                                            ["Cetartiodactyla", 91561, null,
                                              [ ["Suina", 35497, null,
                                                [ ["Suidae", 9821, null,
                                                  [ ["Sus", 9822, null,
                                                    [ ["Pig", 9823, "Sus scrofa" ] ] ] ] ] ] ],
                                              ["Ruminantia", 9845, null,
                                                [ ["Pecora", 35500, null,
                                                  [ ["Bovidae", 9895, null,
                                                    [ ["Bovinae", 27592, null,
                                                      [ ["Bos", 9903, null,
                                                        [ ["Cow", 9913, "Bos taurus" ],
                                                        ["Wild yak", 72004, "Bos mutus" ] ] ],
                                                      ["Bison", 9900, null,
                                                        [ ["Bison bison", 9901, null,
                                                          [ ["Bison", 43346, "Bison bison bison" ] ] ] ] ],
                                                      ["Bubalus", 9918, null,
                                                        [ ["Water buffalo", 89462, "Bubalus bubalis" ] ] ] ] ],
                                                    ["Antilopinae", 9948, null,
                                                      [ ["Pantholops", 59537, null,
                                                        [ ["Tibetan antelope", 59538, "Pantholops hodgsonii" ] ] ] ] ],
                                                    ["Caprinae", 9963, null,
                                                      [ ["Capra", 9922, null,
                                                        [ ["Domestic goat", 9925, "Capra hircus" ] ] ],
                                                      ["Ovis", 9935, null,
                                                        [ ["Sheep", 9940, "Ovis aries" ] ] ] ] ] ] ] ] ] ] ],
                                              ["Cetacea", 9721, null,
                                                [ ["Odontoceti", 9722, null,
                                                  [ ["Delphinidae", 9726, null,
                                                    [ ["Orcinus", 9732, null,
                                                      [ ["Killer whale", 9733, "Orcinus orca" ] ] ],
                                                    ["Tursiops", 9738, null,
                                                      [ ["Dolphin", 9739, "Tursiops truncatus" ] ] ] ] ],
                                                  ["Lipotidae", 119500, null,
                                                    [ ["Lipotes", 118796, null,
                                                      [ ["Yangtze river dolphin", 118797, "Lipotes vexillifer" ] ] ] ] ],
                                                  ["Physeteridae", 9750, null,
                                                    [ ["Physeter", 9753, null,
                                                      [ ["Sperm whale", 9755, "Physeter catodon" ] ] ] ] ] ] ],
                                                ["Mysticeti", 9761, null,
                                                  [ ["Balaenopteridae", 9765, null,
                                                    [ ["Balaenoptera", 9766, null,
                                                      [ ["Balaenoptera acutorostrata", 9767, null,
                                                        [ ["Minke whale", 310752, "Balaenoptera acutorostrata scammoni" ] ] ] ] ] ] ] ] ] ] ],
                                              ["Tylopoda", 9834, null,
                                                [ ["Camelidae", 9835, null,
                                                  [ ["Camelus", 9836, null,
                                                    [ ["Bactrian camel", 419612, "Camelus ferus" ] ] ],
                                                  ["Vicugna", 30539, null,
                                                    [ ["Alpaca", 30538, "Vicugna pacos" ] ] ] ] ] ] ] ] ],
                                            ["Perissodactyla", 9787, null,
                                              [ ["Equidae", 9788, null,
                                                [ ["Equus", 9789, null,
                                                  [ ["Equus", 35510, null,
                                                    [ ["Horse", 9796, "Equus caballus" ],
                                                    ["Przewalski horse", 9798, "Equus przewalskii" ] ] ] ] ] ] ],
                                              ["Rhinocerotidae", 9803, null,
                                                [ ["Ceratotherium", 9806, null,
                                                  [ ["Ceratotherium simum", 9807, null,
                                                    [ ["White rhinoceros", 73337, "Ceratotherium simum simum" ] ] ] ] ] ] ] ] ],
                                            ["Carnivora", 33554, null,
                                              [ ["Caniformia", 379584, null,
                                                [ ["Canidae", 9608, null,
                                                  [ ["Canis", 9611, null,
                                                    [ ["Canis lupus", 9612, null,
                                                      [ ["Dog", 9615, "Canis lupus familiaris" ] ] ] ] ] ] ],
                                                ["Odobenidae", 9705, null,
                                                  [ ["Odobenus", 9706, null,
                                                    [ ["Odobenus rosmarus", 9707, null,
                                                      [ ["Pacific walrus", 9708, "Odobenus rosmarus divergens" ] ] ] ] ] ] ],
                                                ["Mustelidae", 9655, null,
                                                  [ ["Mustelinae", 169418, null,
                                                    [ ["Mustela", 9665, null,
                                                      [ ["Mustela putorius", 9668, null,
                                                        [ ["Ferret", 9669, "Mustela putorius furo" ] ] ] ] ] ] ] ] ],
                                                ["Phocidae", 9709, null,
                                                  [ ["Leptonychotes", 9712, null,
                                                    [ ["Weddell seal", 9713, "Leptonychotes weddellii" ] ] ],
                                                  ["Neomonachus", 1907176, null,
                                                    [ ["Hawaiian monk seal", 29088, "Neomonachus schauinslandi" ] ] ] ] ],
                                                ["Ursidae", 9632, null,
                                                  [ ["Ailuropoda", 9645, null,
                                                    [ ["Panda", 9646, "Ailuropoda melanoleuca" ] ] ],
                                                  ["Ursus", 9639, null,
                                                    [ ["Polar bear", 29073, "Ursus maritimus" ] ] ] ] ] ] ],
                                              ["Feliformia", 379583, null,
                                                [ ["Felidae", 9681, null,
                                                  [ ["Felinae", 338152, null,
                                                    [ ["Felis", 9682, null,
                                                      [ ["Cat", 9685, "Felis catus" ] ] ] ] ],
                                                  ["Pantherinae", 338153, null,
                                                    [ ["Panthera", 9688, null,
                                                      [ ["Panthera tigris", 9694, null,
                                                        [ ["Amur tiger", 74533, "Panthera tigris altaica" ] ] ] ] ] ] ] ] ] ] ] ] ],
                                            ["Chiroptera", 9397, null,
                                              [ ["Megachiroptera", 30559, null,
                                                [ ["Pteropodidae", 9398, null,
                                                  [ ["Pteropodinae", 77225, null,
                                                    [ ["Pteropus", 9401, null,
                                                      [ ["Megabat", 132908, "Pteropus vampyrus" ],
                                                      ["Black flying-fox", 9402, "Pteropus alecto" ] ] ],
                                                    ["Eidolon", 58062, null,
                                                      [ ["Straw colored fruit bat", 77214, "Eidolon helvum" ] ] ],
                                                    ["Rousettus", 9406, null,
                                                      [ ["Egyptian rousette", 9407, "Rousettus aegyptiacus" ] ] ] ] ] ] ] ] ],
                                              ["Microchiroptera", 30560, null,
                                                [ ["Megadermatidae", 9409, null,
                                                  [ ["Megaderma", 9412, null,
                                                    [ ["Indian false vampire", 9413, "Megaderma lyra" ] ] ] ] ],
                                                ["Mormoopidae", 59445, null,
                                                  [ ["Pteronotus", 59475, null,
                                                    [ ["Parnell's mustached bat", 59476, "Pteronotus parnellii" ] ] ] ] ],
                                                ["Rhinolophidae", 58055, null,
                                                  [ ["Rhinolophinae", 186995, null,
                                                    [ ["Rhinolophus", 49442, null,
                                                      [ ["Greater horseshoe bat", 59479, "Rhinolophus ferrumequinum" ] ] ] ] ] ] ],
                                                ["Vespertilionidae", 9431, null,
                                                  [ ["Eptesicus", 29077, null,
                                                    [ ["Big brown bat", 29078, "Eptesicus fuscus" ] ] ],
                                                  ["Myotis", 9434, null,
                                                    [ ["Brandt's myotis (bat)", 109478, "Myotis brandtii" ],
                                                    ["David's myotis (bat)", 225400, "Myotis davidii" ],
                                                    ["Microbat", 59463, "Myotis lucifugus" ] ] ] ] ] ] ] ] ],
                                            ["Pholidota", 9971, null,
                                              [ ["Manidae", 9972, null,
                                                [ ["Manis", 9973, null,
                                                  [ ["Chinese pangolin", 143292, "Manis pentadactyla" ] ] ] ] ] ] ] ] ] ] ],
                                        ["Afrotheria", 311790, "Afrotheria",
                                          [ ["Proboscidea", 9779, null,
                                            [ ["Elephantidae", 9780, null,
                                              [ ["Loxodonta", 9784, null,
                                                [ ["Elephant", 9785, "Loxodonta africana" ] ] ] ] ] ] ],
                                          ["Sirenia", 9774, null,
                                            [ ["Trichechidae", 9775, null,
                                              [ ["Trichechus", 9776, null,
                                                [ ["Trichechus manatus", 9778, null,
                                                  [ ["Manatee", 127582, "Trichechus manatus latirostris" ] ] ] ] ] ] ] ] ],
                                          ["Chrysochloridae", 9389, null,
                                            [ ["Chrysochlorinae", 745257, null,
                                              [ ["Chrysochloris", 185452, null,
                                                [ ["Cape golden mole", 185453, "Chrysochloris asiatica" ] ] ] ] ] ] ],
                                          ["Hyracoidea", 9810, null,
                                            [ ["Procaviidae", 9811, null,
                                              [ ["Procavia", 9812, null,
                                                [ ["Rock hyrax", 9813, "Procavia capensis" ] ] ] ] ] ] ],
                                          ["Macroscelidea", 28734, null,
                                            [ ["Macroscelididae", 28735, null,
                                              [ ["Elephantulus", 28736, null,
                                                [ ["Cape elephant shrew", 28737, "Elephantulus edwardii" ] ] ] ] ] ] ],
                                          ["Tenrecidae", 9369, null,
                                            [ ["Tenrecinae", 176113, null,
                                              [ ["Echinops", 9370, null,
                                                [ ["Tenrec", 9371, "Echinops telfairi" ] ] ] ] ] ] ],
                                          ["Tubulidentata", 9815, null,
                                            [ ["Orycteropodidae", 9816, null,
                                              [ ["Orycteropus", 9817, null,
                                                [ ["Orycteropus afer", 9818, null,
                                                  [ ["Aardvark", 1230840, "Orycteropus afer afer" ] ] ] ] ] ] ] ] ] ] ],
                                        ["Xenarthra", 9348, null,
                                          [ ["Cingulata", 948951, null,
                                            [ ["Dasypodidae", 9359, null,
                                              [ ["Dasypus", 9360, null,
                                                [ ["Armadillo", 9361, "Dasypus novemcinctus" ] ] ] ] ] ] ],
                                          ["Pilosa", 948950, null,
                                            [ ["Folivora", 948953, null,
                                              [ ["Megalonychidae", 227508, null,
                                                [ ["Choloepus", 9357, null,
                                                  [ ["Sloth", 9358, "Choloepus hoffmanni" ] ] ] ] ] ] ] ] ] ] ] ] ],
                                      ["Metatheria", 9263, null,
                                        [ ["Diprotodontia", 38609, null,
                                          [ ["Macropodidae", 9307, null,
                                            [ ["Notamacropus", 1960649, null,
                                              [ ["Wallaby", 9315, "Notamacropus eugenii" ] ] ] ] ] ] ],
                                        ["Dasyuromorphia", 38608, null,
                                          [ ["Dasyuridae", 9277, null,
                                            [ ["Sarcophilus", 9304, null,
                                              [ ["Tasmanian devil", 9305, "Sarcophilus harrisii" ] ] ] ] ] ] ],
                                        ["Didelphimorphia", 38605, null,
                                          [ ["Didelphidae", 9265, null,
                                            [ ["Didelphinae", 126287, null,
                                              [ ["Monodelphis", 13615, null,
                                                [ ["Opossum", 13616, "Monodelphis domestica" ] ] ] ] ] ] ] ] ] ] ] ] ],
                                    ["Prototheria", 9254, null,
                                      [ ["Monotremata", 9255, null,
                                        [ ["Ornithorhynchidae", 9256, null,
                                          [ ["Ornithorhynchus", 9257, null,
                                            [ ["Platypus", 9258, "Ornithorhynchus anatinus" ] ] ] ] ] ] ] ] ] ] ],
                                  ["Sauropsida", 8457, null,
                                    [ ["Sauria", 32561, null,
                                      [ ["Archelosauria", 1329799, null,
                                        [ ["Archosauria", 8492, null,
                                          [ ["Dinosauria", 436486, null,
                                            [ ["Saurischia", 436489, null,
                                              [ ["Theropoda", 436491, null,
                                                [ ["Coelurosauria", 436492, null,
                                                  [ ["Aves", 8782, null,
                                                    [ ["Neognathae", 8825, null,
                                                      [ ["Galloanserae", 1549675, null,
                                                        [ ["Galliformes", 8976, null,
                                                          [ ["Phasianidae", 9005, null,
                                                            [ ["Phasianinae", 9072, null,
                                                              [ ["Gallus", 9030, null,
                                                                [ ["Chicken", 9031, "Gallus gallus" ] ] ] ] ],
                                                            ["Meleagridinae", 466552, null,
                                                              [ ["Meleagris", 9102, null,
                                                                [ ["Turkey", 9103, "Meleagris gallopavo" ] ] ] ] ],
                                                            ["Perdicinae", 466544, null,
                                                              [ ["Coturnix", 9090, null,
                                                                [ ["Japanese quail", 93934, "Coturnix japonica" ] ] ] ] ] ] ] ] ],
                                                        ["Anseriformes", 8826, null,
                                                          [ ["Anatidae", 8830, null,
                                                            [ ["Anatinae", 2068716, null,
                                                              [ ["Anas", 8835, null,
                                                                [ ["Mallard duck", 8839, "Anas platyrhynchos" ] ] ] ] ] ] ] ] ] ] ],
                                                      ["Bucerotiformes", 57379, null,
                                                        [ ["Bucerotidae", 57380, null,
                                                          [ ["Buceros", 175829, null,
                                                            [ ["Buceros rhinoceros", 175835, null,
                                                              [ ["Rhinoceros hornbill", 175836, "Buceros rhinoceros silvestris" ] ] ] ] ] ] ] ] ],
                                                      ["Caprimulgiformes", 8902, null,
                                                        [ ["Caprimulgidae", 48283, null,
                                                          [ ["Antrostomus", 1854010, null,
                                                            [ ["Chuck-will's-widow", 279965, "Antrostomus carolinensis" ] ] ] ] ] ] ],
                                                      ["Cariamiformes", 1956187, null,
                                                        [ ["Cariamidae", 54378, null,
                                                          [ ["Cariama", 54379, null,
                                                            [ ["Red-legged seriema", 54380, "Cariama cristata" ] ] ] ] ] ] ],
                                                      ["Charadriiformes", 8906, null,
                                                        [ ["Charadriidae", 8907, null,
                                                          [ ["Charadrius", 50391, null,
                                                            [ ["Killdeer", 50402, "Charadrius vociferus" ] ] ] ] ] ] ],
                                                      ["Ciconiiformes", 8920, null,
                                                        [ ["Pteroclidae", 56295, null,
                                                          [ ["Pterocles", 56296, null,
                                                            [ ["Yellow-throated sandgrouse", 240206, "Pterocles gutturalis" ] ] ] ] ] ] ],
                                                      ["Coliiformes", 57384, null,
                                                        [ ["Coliidae", 57385, null,
                                                          [ ["Colius", 57409, null,
                                                            [ ["Speckled mousebird", 57412, "Colius striatus" ] ] ] ] ] ] ],
                                                      ["Columbiformes", 8929, null,
                                                        [ ["Columbidae", 8930, null,
                                                          [ ["Columba", 8931, null,
                                                            [ ["Rock pigeon", 8932, "Columba livia" ] ] ] ] ] ] ],
                                                      ["Coraciiformes", 8936, null,
                                                        [ ["Leptosomidae", 188342, null,
                                                          [ ["Leptosomus", 188343, null,
                                                            [ ["Cuckoo roller", 188344, "Leptosomus discolor" ] ] ] ] ],
                                                        ["Meropidae", 57386, null,
                                                          [ ["Merops", 57420, null,
                                                            [ ["Northern carmine bee-eater", 57421, "Merops nubicus" ] ] ] ] ] ] ],
                                                      ["Cuculiformes", 8940, null,
                                                        [ ["Cuculidae", 8941, null,
                                                          [ ["Cuculus", 33592, null,
                                                            [ ["Common cuckoo", 55661, "Cuculus canorus" ] ] ] ] ] ] ],
                                                      ["Falconiformes", 8948, null,
                                                        [ ["Accipitridae", 56259, null,
                                                          [ ["Accipitrinae", 8955, null,
                                                            [ ["Aquila", 8960, null,
                                                              [ ["Aquila chrysaetos", 8962, null,
                                                                [ ["Golden eagle", 216574, "Aquila chrysaetos canadensis" ] ] ] ] ],
                                                            ["Haliaeetus", 8968, null,
                                                              [ ["Bald eagle", 52644, "Haliaeetus leucocephalus" ],
                                                              ["White-tailed eagle", 8969, "Haliaeetus albicilla" ] ] ] ] ] ] ],
                                                        ["Falconidae", 8949, null,
                                                          [ ["Falco", 8952, null,
                                                            [ ["Peregrine falcon", 8954, "Falco peregrinus" ],
                                                            ["Saker falcon", 345164, "Falco cherrug" ] ] ] ] ] ] ],
                                                      ["Gaviiformes", 30411, null,
                                                        [ ["Gaviidae", 30412, null,
                                                          [ ["Gavia", 37038, null,
                                                            [ ["Red-throated loon", 37040, "Gavia stellata" ] ] ] ] ] ] ],
                                                      ["Gruiformes", 9108, null,
                                                        [ ["Eurypygidae", 54381, null,
                                                          [ ["Eurypyga", 54382, null,
                                                            [ ["Sunbittern", 54383, "Eurypyga helias" ] ] ] ] ],
                                                        ["Gruidae", 9109, null,
                                                          [ ["Balearica", 30413, null,
                                                            [ ["Balearica regulorum", 925459, null,
                                                              [ ["Crowned crain", 100784, "Balearica regulorum gibbericeps" ] ] ] ] ] ] ],
                                                        ["Mesitornithidae", 54372, null,
                                                          [ ["Mesitornis", 54373, null,
                                                            [ ["Brown roatelo", 54374, "Mesitornis unicolor" ] ] ] ] ],
                                                        ["Otididae", 54375, null,
                                                          [ ["Chlamydotis", 172679, null,
                                                            [ ["Houbara bustard", 187382, "Chlamydotis macqueenii" ] ] ] ] ] ] ],
                                                      ["Musophagiformes", 56301, null,
                                                        [ ["Musophagidae", 56302, null,
                                                          [ ["Tauraco", 56303, null,
                                                            [ ["Red crested turaco", 121530, "Tauraco erythrolophus" ] ] ] ] ] ] ],
                                                      ["Opisthocomiformes", 30416, null,
                                                        [ ["Opisthocomidae", 30417, null,
                                                          [ ["Opisthocomus", 30418, null,
                                                            [ ["Hoatzin", 30419, "Opisthocomus hoazin" ] ] ] ] ] ] ],
                                                      ["Passeriformes", 9126, null,
                                                        [ ["Acanthisittidae", 38633, null,
                                                          [ ["Acanthisitta", 57067, null,
                                                            [ ["Rifleman", 57068, "Acanthisitta chloris" ] ] ] ] ],
                                                        ["Corvoidea", 192204, null,
                                                          [ ["Corvidae", 28725, null,
                                                            [ ["Corvus", 30420, null,
                                                              [ ["American crow", 85066, "Corvus brachyrhynchos" ],
                                                              ["Corvus cornix", 181096, null,
                                                                [ ["Hooded crow", 932674, "Corvus cornix cornix" ] ] ] ] ] ] ] ] ],
                                                        ["Muscicapidae", 36291, null,
                                                          [ ["Ficedula", 36292, null,
                                                            [ ["Collared flycatcher", 59894, "Ficedula albicollis" ] ] ] ] ],
                                                        ["Paridae", 9153, null,
                                                          [ ["Pseudopodoces", 181118, null,
                                                            [ ["Tibetan ground jay", 181119, "Pseudopodoces humilis" ] ] ] ] ],
                                                        ["Passerellidae", 1729112, null,
                                                          [ ["Zonotrichia", 44387, null,
                                                            [ ["White-throated sparrow", 44394, "Zonotrichia albicollis" ] ] ] ] ],
                                                        ["Passeroidea", 175121, null,
                                                          [ ["Estrildidae", 37611, null,
                                                            [ ["Estrildinae", 40155, null,
                                                              [ ["Taeniopygia", 59728, null,
                                                                [ ["Zebra finch", 59729, "Taeniopygia guttata" ] ] ] ] ] ] ],
                                                          ["Fringillidae", 9133, null,
                                                            [ ["Carduelinae", 37599, null,
                                                              [ ["Serinus", 9134, null,
                                                                [ ["Canary", 9135, "Serinus canaria" ] ] ] ] ] ] ] ] ],
                                                        ["Pipridae", 114313, null,
                                                          [ ["Manacus", 196036, null,
                                                            [ ["Golden-collared manakin", 328815, "Manacus vitellinus" ] ] ] ] ],
                                                        ["Thraupidae", 400783, null,
                                                          [ ["Geospiza", 48881, null,
                                                            [ ["Medium ground finch", 48883, "Geospiza fortis" ] ] ] ] ] ] ],
                                                      ["Pelecaniformes", 9205, null,
                                                        [ ["Ardeidae", 8899, null,
                                                          [ ["Egretta", 56073, null,
                                                            [ ["Little egret", 188379, "Egretta garzetta" ] ] ] ] ],
                                                        ["Pelecanidae", 30444, null,
                                                          [ ["Pelecanus", 33617, null,
                                                            [ ["Dalmatian pelican", 36300, "Pelecanus crispus" ] ] ] ] ],
                                                        ["Phaethontidae", 30445, null,
                                                          [ ["Phaethon", 37044, null,
                                                            [ ["White-tailed tropicbird", 97097, "Phaethon lepturus" ] ] ] ] ],
                                                        ["Phalacrocoracidae", 9206, null,
                                                          [ ["Phalacrocorax", 9207, null,
                                                            [ ["Great cormorant", 9209, "Phalacrocorax carbo" ] ] ] ] ],
                                                        ["Threskiornithidae", 33574, null,
                                                          [ ["Nipponia", 128389, null,
                                                            [ ["Crested ibis", 128390, "Nipponia nippon" ] ] ] ] ] ] ],
                                                      ["Phoenicopteriformes", 9214, null,
                                                        [ ["Phoenicopteridae", 9215, null,
                                                          [ ["Phoenicopterus", 9216, null,
                                                            [ ["Phoenicopterus ruber", 9217, null,
                                                              [ ["American flamingo", 9218, "Phoenicopterus ruber ruber" ] ] ] ] ] ] ] ] ],
                                                      ["Piciformes", 9219, null,
                                                        [ ["Picidae", 9220, null,
                                                          [ ["Picoides", 36302, null,
                                                            [ ["Downy woodpecker", 118200, "Picoides pubescens" ] ] ] ] ] ] ],
                                                      ["Procellariiformes", 30449, null,
                                                        [ ["Procellariidae", 30451, null,
                                                          [ ["Fulmarus", 30454, null,
                                                            [ ["Northern fulmar", 30455, "Fulmarus glacialis" ] ] ] ] ] ] ],
                                                      ["Psittaciformes", 9223, null,
                                                        [ ["Psittacidae", 9224, null,
                                                          [ ["Amazona", 12929, null,
                                                            [ ["Parrot", 241585, "Amazona vittata" ] ] ],
                                                          ["Ara", 9225, null,
                                                            [ ["Scarlet macaw", 176014, "Ara macao" ] ] ] ] ],
                                                        ["Psittaculidae", 1545690, null,
                                                          [ ["Melopsittacus", 13145, null,
                                                            [ ["Budgerigar", 13146, "Melopsittacus undulatus" ] ] ] ] ] ] ],
                                                      ["Sphenisciformes", 9230, null,
                                                        [ ["Spheniscidae", 9231, null,
                                                          [ ["Aptenodytes", 9232, null,
                                                            [ ["Emperor penguin", 9233, "Aptenodytes forsteri" ] ] ],
                                                          ["Pygoscelis", 9237, null,
                                                            [ ["Adelie penguin", 9238, "Pygoscelis adeliae" ] ] ] ] ] ] ],
                                                      ["Strigiformes", 30458, null,
                                                        [ ["Tytonidae", 30462, null,
                                                          [ ["Tyto", 56312, null,
                                                            [ ["Barn owl", 56313, "Tyto alba" ] ] ] ] ] ] ],
                                                      ["Trochiliformes", 9241, null,
                                                        [ ["Trochilidae", 9242, null,
                                                          [ ["Calypte", 9243, null,
                                                            [ ["Anna's hummingbird", 9244, "Calypte anna" ] ] ] ] ] ] ],
                                                      ["Trogoniformes", 56308, null,
                                                        [ ["Trogonidae", 56309, null,
                                                          [ ["Apaloderma", 57396, null,
                                                            [ ["Bar tailed trogon", 57397, "Apaloderma vittatum" ] ] ] ] ] ] ] ] ],
                                                    ["Palaeognathae", 8783, null,
                                                      [ ["Apterygiformes", 8819, null,
                                                        [ ["Apterygidae", 8820, null,
                                                          [ ["Apteryx", 8821, null,
                                                            [ ["Apteryx australis", 8822, null,
                                                              [ ["Brown kiwi", 202946, "Apteryx australis mantelli" ] ] ] ] ] ] ] ] ],
                                                      ["Struthioniformes", 8798, null,
                                                        [ ["Struthionidae", 8799, null,
                                                          [ ["Struthio", 8800, null,
                                                            [ ["Struthio camelus", 8801, null,
                                                              [ ["Ostrich", 441894, "Struthio camelus australis" ] ] ] ] ] ] ] ] ],
                                                      ["Tinamiformes", 8802, null,
                                                        [ ["Tinamidae", 8803, null,
                                                          [ ["Tinamus", 30467, null,
                                                            [ ["White throated tinamou", 94827, "Tinamus guttatus" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
                                          ["Crocodylia", 1294634, null,
                                            [ ["Alligatoridae", 1294636, null,
                                              [ ["Alligatorinae", 34915, null,
                                                [ ["Alligator", 8495, null,
                                                  [ ["American alligator", 8496, "Alligator mississippiensis" ],
                                                  ["Chinese alligator", 38654, "Alligator sinensis" ] ] ] ] ] ] ],
                                            ["Longirostres", 1298654, null,
                                              [ ["Crocodylidae", 8493, null,
                                                [ ["Crocodylus", 8500, null,
                                                  [ ["Saltwater crocodile", 8502, "Crocodylus porosus" ] ] ] ] ],
                                              ["Gavialidae", 1294635, null,
                                                [ ["Gavialinae", 94833, null,
                                                  [ ["Gavialis", 94834, null,
                                                    [ ["Gharial", 94835, "Gavialis gangeticus" ] ] ] ] ] ] ] ] ] ] ] ] ],
                                        ["Testudines", 8459, null,
                                          [ ["Cryptodira", 8464, null,
                                            [ ["Durocryptodira", 1579337, null,
                                              [ ["Americhelydia", 1579336, null,
                                                [ ["Chelonioidea", 27791, null,
                                                  [ ["Cheloniidae", 8465, null,
                                                    [ ["Chelonia", 8468, null,
                                                      [ ["Green seaturtle", 8469, "Chelonia mydas" ] ] ] ] ] ] ] ] ],
                                              ["Testudinoidea", 8486, null,
                                                [ ["Emydidae", 8476, null,
                                                  [ ["Chrysemys", 8477, null,
                                                    [ ["Chrysemys picta", 8479, null,
                                                      [ ["Painted turtle", 8478, "Chrysemys picta bellii" ] ] ] ] ] ] ] ] ] ] ],
                                            ["Trionychia", 1579275, null,
                                              [ ["Trionychidae", 34907, null,
                                                [ ["Apalone", 55533, null,
                                                  [ ["Spiny softshell turtle", 55534, "Apalone spinifera" ] ] ],
                                                ["Pelodiscus", 204969, null,
                                                  [ ["Chinese softshell turtle", 13735, "Pelodiscus sinensis" ] ] ] ] ] ] ] ] ] ] ] ] ],
                                      ["Lepidosauria", 8504, null,
                                        [ ["Squamata", 8509, null,
                                          [ ["Bifurcata", 1329961, null,
                                            [ ["Unidentata", 1329950, null,
                                              [ ["Episquamata", 1329912, null,
                                                [ ["Toxicofera", 1329911, null,
                                                  [ ["Iguania", 8511, null,
                                                    [ ["Dactyloidae", 2024747, null,
                                                      [ ["Anolis", 28376, null,
                                                        [ ["Lizard", 28377, "Anolis carolinensis" ] ] ] ] ] ] ],
                                                  ["Serpentes", 8570, null,
                                                    [ ["Colubroidea", 34989, null,
                                                      [ ["Colubridae", 8578, null,
                                                        [ ["Natricinae", 169862, null,
                                                          [ ["Thamnophis", 34999, null,
                                                            [ ["Garter snake", 35019, "Thamnophis sirtalis" ] ] ] ] ] ] ] ] ],
                                                    ["Henophidia", 34979, null,
                                                      [ ["Pythonidae", 34984, null,
                                                        [ ["Python", 37579, null,
                                                          [ ["Burmese python", 176946, "Python bivittatus" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
                                ["Amphibia", 8292, null,
                                  [ ["Batrachia", 41666, null,
                                    [ ["Anura", 8342, null,
                                      [ ["Pipoidea", 30319, null,
                                        [ ["Pipidae", 8352, null,
                                          [ ["Xenopodinae", 8360, null,
                                            [ ["Xenopus", 8353, null,
                                              [ ["Silurana", 8363, null,
                                                [ ["X. tropicalis", 8364, "Xenopus tropicalis" ] ] ],
                                              ["Xenopus", 262014, null,
                                                [ ["African clawed frog", 8355, "Xenopus laevis" ] ] ] ] ] ] ] ] ] ] ],
                                      ["Neobatrachia", 8416, null,
                                        [ ["Ranoidea", 30352, null,
                                          [ ["Dicroglossidae", 685122, null,
                                            [ ["Dicroglossinae", 1191378, null,
                                              [ ["Nanorana", 120497, null,
                                                [ ["Tibetan frog", 125878, "Nanorana parkeri" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
                            ["Coelacanthimorpha", 118072, null,
                              [ ["Coelacanthiformes", 7894, null,
                                [ ["Coelacanthidae", 7895, null,
                                  [ ["Latimeria", 7896, null,
                                    [ ["Coelacanth", 7897, "Latimeria chalumnae" ] ] ] ] ] ] ] ] ] ] ],
                          ["Actinopterygii", 7898, null,
                            [ ["Actinopteri", 186623, null,
                              [ ["Neopterygii", 41665, null,
                                [ ["Teleostei", 32443, null,
                                  [ ["Osteoglossocephalai", 1489341, null,
                                    [ ["Clupeocephala", 186625, null,
                                      [ ["Otomorpha", 186634, null,
                                        [ ["Ostariophysi", 32519, null,
                                          [ ["Otophysi", 186626, null,
                                            [ ["Cypriniphysae", 186627, null,
                                              [ ["Cypriniformes", 7952, null,
                                                [ ["Cyprinoidea", 30727, null,
                                                  [ ["Cyprinidae", 7953, null,
                                                    [ ["Danio", 7954, null,
                                                      [ ["Zebrafish", 7955, "Danio rerio" ] ] ] ] ] ] ] ] ] ] ],
                                            ["Characiphysae", 186628, null,
                                              [ ["Characiformes", 7991, null,
                                                [ ["Characoidei", 1489739, null,
                                                  [ ["Characidae", 7992, null,
                                                    [ ["Characidae incertae sedis", 533331, null,
                                                      [ ["Astyanax clade", 883878, null,
                                                        [ ["Astyanax", 7993, null,
                                                          [ ["Mexican tetra (cavefish)", 7994, "Astyanax mexicanus" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
                                      ["Euteleosteomorpha", 1489388, null,
                                        [ ["Neoteleostei", 123365, null,
                                          [ ["Eurypterygia", 123366, null,
                                            [ ["Ctenosquamata", 123367, null,
                                              [ ["Acanthomorphata", 123368, null,
                                                [ ["Euacanthomorphacea", 123369, null,
                                                  [ ["Percomorphaceae", 1489872, null,
                                                    [ ["Carangaria", 1489904, null,
                                                      [ ["Pleuronectiformes", 8252, null,
                                                        [ ["Pleuronectoidei", 30942, null,
                                                          [ ["Cynoglossidae", 30947, null,
                                                            [ ["Cynoglossinae", 603456, null,
                                                              [ ["Cynoglossus", 106173, null,
                                                                [ ["Tongue sole", 244447, "Cynoglossus semilaevis" ] ] ] ] ] ] ] ] ] ] ] ] ],
                                                    ["Eupercaria", 1489922, null,
                                                      [ ["Eupercaria incertae sedis", 1489923, null,
                                                        [ ["Moronidae", 42148, null,
                                                          [ ["Dicentrarchus", 13488, null,
                                                            [ ["European sea bass", 13489, "Dicentrarchus labrax" ] ] ] ] ] ] ],
                                                      ["Perciformes", 8111, null,
                                                        [ ["Cottioidei", 8100, null,
                                                          [ ["Gasterosteales", 1490020, null,
                                                            [ ["Gasterosteidae", 69291, null,
                                                              [ ["Gasterosteus", 69292, null,
                                                                [ ["Stickleback", 69293, "Gasterosteus aculeatus" ] ] ] ] ] ] ] ] ],
                                                        ["Notothenioidei", 8205, null,
                                                          [ ["Nototheniidae", 8206, null,
                                                            [ ["Notothenia", 8207, null,
                                                              [ ["Black rockcod", 8208, "Notothenia coriiceps" ] ] ] ] ] ] ],
                                                        ["Scorpaenoidei", 8107, null,
                                                          [ ["Sebastidae", 274692, null,
                                                            [ ["Sebastinae", 274705, null,
                                                              [ ["Sebastes", 34820, null,
                                                                [ ["Flag rockfish", 72099, "Sebastes rubrivinctus" ],
                                                                ["Tiger rockfish", 72089, "Sebastes nigrocinctus" ] ] ] ] ] ] ] ] ] ] ],
                                                      ["Tetraodontiformes", 31022, null,
                                                        [ ["Tetraodontoidei", 31028, null,
                                                          [ ["Tetradontoidea", 32517, null,
                                                            [ ["Tetraodontidae", 31031, null,
                                                              [ ["Takifugu", 31032, null,
                                                                [ ["Fugu", 31033, "Takifugu rubripes" ],
                                                                ["Yellowbelly pufferfish", 433684, "Takifugu flavidus" ] ] ],
                                                              ["Tetraodon", 47144, null,
                                                                [ ["Tetraodon", 99883, "Tetraodon nigroviridis" ] ] ] ] ] ] ] ] ] ] ] ] ],
                                                    ["Ovalentaria", 1489908, null,
                                                      [ ["Atherinomorphae", 1489913, null,
                                                        [ ["Beloniformes", 76071, null,
                                                          [ ["Adrianichthyoidei", 28781, null,
                                                            [ ["Adrianichthyidae", 47757, null,
                                                              [ ["Oryziinae", 8088, null,
                                                                [ ["Oryzias", 8089, null,
                                                                  [ ["Medaka", 8090, "Oryzias latipes" ] ] ] ] ] ] ] ] ] ] ],
                                                        ["Cyprinodontiformes", 28738, null,
                                                          [ ["Cyprinodontoidei", 8087, null,
                                                            [ ["Cyprinodontidae", 8076, null,
                                                              [ ["Cyprinodontinae", 136836, null,
                                                                [ ["Cyprinodontini", 136838, null,
                                                                  [ ["Cyprinodon", 28741, null,
                                                                    [ ["Sheepshead minnow", 28743, "Cyprinodon variegatus" ] ] ] ] ] ] ] ] ],
                                                            ["Poeciliidae", 8079, null,
                                                              [ ["Poeciliinae", 586240, null,
                                                                [ ["Poecilia", 8080, null,
                                                                  [ ["Amazon molly", 48698, "Poecilia formosa" ],
                                                                  ["Guppy", 8081, "Poecilia reticulata" ] ] ],
                                                                ["Xiphophorus", 8082, null,
                                                                  [ ["Southern platyfish", 8083, "Xiphophorus maculatus" ] ] ] ] ] ] ] ] ] ] ] ] ],
                                                      ["Cichlomorphae", 1489910, null,
                                                        [ ["Cichliformes", 1489911, null,
                                                          [ ["Cichlidae", 8113, null,
                                                            [ ["African cichlids", 319095, null,
                                                              [ ["Pseudocrenilabrinae", 318546, null,
                                                                [ ["Haplochromini", 319058, null,
                                                                  [ ["Haplochromis", 8121, null,
                                                                    [ ["Burton's mouthbreeder", 8153, "Haplochromis burtoni" ] ] ],
                                                                  ["Maylandia", 143623, null,
                                                                    [ ["Maylandia zebra complex", 57445, null,
                                                                      [ ["Zebra mbuna", 106582, "Maylandia zebra" ] ] ] ] ],
                                                                  ["Pundamilia", 195936, null,
                                                                    [ ["Pundamilia nyererei", 303518, "Pundamilia nyererei" ] ] ] ] ],
                                                                ["Lamprologini", 319069, null,
                                                                  [ ["Neolamprologus", 32506, null,
                                                                    [ ["Princess of Burundi", 32507, "Neolamprologus brichardi" ] ] ] ] ],
                                                                ["Oreochromini", 1315725, null,
                                                                  [ ["Oreochromis", 8139, null,
                                                                    [ ["Nile tilapia", 8128, "Oreochromis niloticus" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
                                                      ["Ovalentaria incertae sedis", 1489909, null,
                                                        [ ["Pomacentridae", 30863, null,
                                                          [ ["Stegastes", 80992, null,
                                                            [ ["Bicolor damselfish", 144197, "Stegastes partitus" ] ] ] ] ] ] ] ] ] ] ] ] ],
                                                ["Paracanthomorphacea", 1489838, null,
                                                  [ ["Zeiogadaria", 1489841, null,
                                                    [ ["Gadariae", 1489843, null,
                                                      [ ["Gadiformes", 8043, null,
                                                        [ ["Gadoidei", 1489845, null,
                                                          [ ["Gadidae", 8045, null,
                                                            [ ["Gadus", 8048, null,
                                                              [ ["Atlantic cod", 8049, "Gadus morhua" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
                                        ["Protacanthopterygii", 41705, null,
                                          [ ["Esociformes", 8007, null,
                                            [ ["Esocidae", 8008, null,
                                              [ ["Esox", 8009, null,
                                                [ ["Northern pike", 8010, "Esox lucius" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
                                  ["Elopocephalai", 1489340, null,
                                    [ ["Elopocephala", 186624, null,
                                      [ ["Elopomorpha", 32521, null,
                                        [ ["Anguilliformes", 7933, null,
                                          [ ["Anguillidae", 7934, null,
                                            [ ["Anguilla", 7935, null,
                                              [ ["Japanese eel", 7937, "Anguilla japonica" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
                                ["Holostei", 1489100, null,
                                  [ ["Semionotiformes", 7914, null,
                                    [ ["Lepisosteidae", 7915, null,
                                      [ ["Lepisosteus", 7916, null,
                                        [ ["Spotted gar", 7918, "Lepisosteus oculatus" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
                      ["Chondrichthyes", 7777, null,
                        [ ["Holocephali", 7863, null,
                          [ ["Chimaeriformes", 7864, null,
                            [ ["Callorhinchidae", 7865, null,
                              [ ["Callorhinchus", 7866, null,
                                [ ["Elephant shark", 7868, "Callorhinchus milii" ] ] ] ] ] ] ] ] ] ] ] ] ],
                    ["Cyclostomata", 1476529, null,
                      [ ["Hyperoartia", 117569, null,
                        [ ["Petromyzontiformes", 7745, null,
                          [ ["Petromyzontidae", 7746, null,
                            [ ["Lethenteron", 94988, null,
                              [ ["Arctic lamprey", 980415, "Lethenteron camtschaticum" ] ] ],
                            ["Petromyzon", 7756, null,
                              [ ["Lamprey", 7757, "Petromyzon marinus" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
                ["Cephalochordata", 7735, null,
                  [ ["Branchiostomidae", 7736, null,
                    [ ["Branchiostoma", 7737, null,
                      [ ["Lancelet", 7739, "Branchiostoma floridae" ] ] ] ] ] ] ],
                ["Tunicata", 7712, null,
                  [ ["Ascidiacea", 7713, null,
                    [ ["Enterogona", 183770, null,
                      [ ["Phlebobranchia", 7716, null,
                        [ ["Cionidae", 7717, null,
                          [ ["Ciona", 7718, null,
                            [ ["C. intestinalis", 7719, "Ciona intestinalis" ],
                            ["C. savignyi", 51511, "Ciona savignyi" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
              ["Echinodermata", 7586, null,
                [ ["Eleutherozoa", 133551, null,
                  [ ["Echinozoa", 7624, null,
                    [ ["Echinoidea", 7625, null,
                      [ ["Euechinoidea", 7638, null,
                        [ ["Echinacea", 7674, null,
                          [ ["Echinoida", 7675, null,
                            [ ["Strongylocentrotidae", 31181, null,
                              [ ["Strongylocentrotus", 7664, null,
                                [ ["S. purpuratus", 7668, "Strongylocentrotus purpuratus" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
            ["Protostomia", 33317, null,
              [ ["Ecdysozoa", 1206794, null,
                [ ["Panarthropoda", 88770, null,
                  [ ["Arthropoda", 6656, null,
                    [ ["Mandibulata", 197563, null,
                      [ ["Pancrustacea", 197562, null,
                        [ ["Hexapoda", 6960, null,
                          [ ["Insecta", 50557, null,
                            [ ["Dicondylia", 85512, null,
                              [ ["Pterygota", 7496, null,
                                [ ["Neoptera", 33340, null,
                                  [ ["Holometabola", 33392, null,
                                    [ ["Diptera", 7147, null,
                                      [ ["Brachycera", 7203, null,
                                        [ ["Muscomorpha", 43733, null,
                                          [ ["Eremoneura", 480118, null,
                                            [ ["Cyclorrhapha", 480117, null,
                                              [ ["Schizophora", 43738, null,
                                                [ ["Acalyptratae", 43741, null,
                                                  [ ["Ephydroidea", 43746, null,
                                                    [ ["Drosophilidae", 7214, null,
                                                      [ ["Drosophilinae", 43845, null,
                                                        [ ["Drosophilini", 46877, null,
                                                          [ ["Drosophila", 7215, null,
                                                            [ ["Sophophora", 32341, null,
                                                              [ ["melanogaster group", 32346, null,
                                                                [ ["melanogaster subgroup", 32351, null,
                                                                  [ ["D. melanogaster", 7227, "Drosophila melanogaster" ],
                                                                  ["D. erecta", 7220, "Drosophila erecta" ],
                                                                  ["D. sechellia", 7238, "Drosophila sechellia" ],
                                                                  ["D. simulans", 7240, "Drosophila simulans" ],
                                                                  ["D. yakuba", 7245, "Drosophila yakuba" ] ] ],
                                                                ["ananassae subgroup", 32347, null,
                                                                  [ ["ananassae species complex", 545632, null,
                                                                    [ ["D. ananassae", 7217, "Drosophila ananassae" ] ] ],
                                                                  ["bipectinata species complex", 186282, null,
                                                                    [ ["D. bipectinata", 42026, "Drosophila bipectinata" ] ] ] ] ],
                                                                ["elegans subgroup", 32348, null,
                                                                  [ ["D. elegans", 30023, "Drosophila elegans" ] ] ],
                                                                ["eugracilis subgroup", 32349, null,
                                                                  [ ["D. eugracilis", 29029, "Drosophila eugracilis" ] ] ],
                                                                ["ficusphila subgroup", 32350, null,
                                                                  [ ["D. ficusphila", 30025, "Drosophila ficusphila" ] ] ],
                                                                ["montium subgroup", 32352, null,
                                                                  [ ["D. kikkawai", 30033, "Drosophila kikkawai" ] ] ],
                                                                ["rhopaloa subgroup", 65962, null,
                                                                  [ ["D. rhopaloa", 1041015, "Drosophila rhopaloa" ] ] ],
                                                                ["suzukii subgroup", 32353, null,
                                                                  [ ["D. biarmipes", 125945, "Drosophila biarmipes" ],
                                                                  ["D. suzukii", 28584, "Drosophila suzukii" ] ] ],
                                                                ["takahashii subgroup", 32354, null,
                                                                  [ ["D. takahashii", 29030, "Drosophila takahashii" ] ] ] ] ],
                                                              ["obscura group", 32355, null,
                                                                [ ["pseudoobscura subgroup", 32358, null,
                                                                  [ ["D. miranda", 7229, "Drosophila miranda" ],
                                                                  ["D. persimilis", 7234, "Drosophila persimilis" ],
                                                                  ["D. pseudoobscura", 7237, "Drosophila pseudoobscura",
                                                                    [ ["D. pseudoobscura", 46245, "Drosophila pseudoobscura pseudoobscura" ] ] ] ] ] ] ],
                                                              ["willistoni group", 32365, null,
                                                                [ ["willistoni subgroup", 32367, null,
                                                                  [ ["D. willistoni", 7260, "Drosophila willistoni" ] ] ] ] ] ] ],
                                                            ["Drosophila", 32281, null,
                                                              [ ["immigrans group", 32304, null,
                                                                [ ["nasuta subgroup", 32307, null,
                                                                  [ ["D. albomicans", 7291, "Drosophila albomicans" ] ] ] ] ],
                                                              ["repleta group", 32321, null,
                                                                [ ["mulleri subgroup", 32324, null,
                                                                  [ ["mojavensis species complex", 198037, null,
                                                                    [ ["D. mojavensis", 7230, "Drosophila mojavensis" ] ] ] ] ] ] ],
                                                              ["virilis group", 32335, null,
                                                                [ ["D. virilis", 7244, "Drosophila virilis" ] ] ] ] ],
                                                            ["Hawaiian Drosophila", 504493, null,
                                                              [ ["picture wing clade", 48384, null,
                                                                [ ["grimshawi clade", 48301, null,
                                                                  [ ["grimshawi group", 48302, null,
                                                                    [ ["grimshawi subgroup", 32378, null,
                                                                      [ ["D. grimshawi", 7222, "Drosophila grimshawi" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
                                                ["Calyptratae", 43742, null,
                                                  [ ["Muscoidea", 43754, null,
                                                    [ ["Muscidae", 7366, null,
                                                      [ ["Muscinae", 43910, null,
                                                        [ ["Muscini", 57894, null,
                                                          [ ["Musca", 7369, null,
                                                            [ ["Musca", 44052, null,
                                                              [ ["M. domestica", 7370, "Musca domestica" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
                                      ["Nematocera", 7148, null,
                                        [ ["Culicomorpha", 43786, null,
                                          [ ["Culicoidea", 41827, null,
                                            [ ["Culicidae", 7157, null,
                                              [ ["Anophelinae", 43816, null,
                                                [ ["Anopheles", 7164, null,
                                                  [ ["Cellia", 44534, null,
                                                    [ ["Pyretophorus", 44537, null,
                                                      [ ["gambiae species complex", 44542, null,
                                                        [ ["A. gambiae", 7165, "Anopheles gambiae",
                                                          [ ["A. gambiae", 180454, "Anopheles gambiae str. PEST" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
                                    ["Coleoptera", 7041, null,
                                      [ ["Polyphaga", 41084, null,
                                        [ ["Cucujiformia", 41088, null,
                                          [ ["Tenebrionoidea", 71527, null,
                                            [ ["Tenebrionidae", 7065, null,
                                              [ ["Tenebrionidae incertae sedis", 1304792, null,
                                                [ ["Tribolium", 7069, null,
                                                  [ ["T. castaneum", 7070, "Tribolium castaneum" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
                                    ["Hymenoptera", 7399, null,
                                      [ ["Apocrita", 7400, null,
                                        [ ["Aculeata", 7434, null,
                                          [ ["Apoidea", 34735, null,
                                            [ ["Apidae", 7458, null,
                                              [ ["Apinae", 70987, null,
                                                [ ["Apini", 83321, null,
                                                  [ ["Apis", 7459, null,
                                                    [ ["A. mellifera", 7460, "Apis mellifera" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
                ["Nematoda", 6231, null,
                  [ ["Chromadorea", 119089, null,
                    [ ["Rhabditida", 6236, null,
                      [ ["Rhabditoidea", 55879, null,
                        [ ["Rhabditidae", 6243, null,
                          [ ["Peloderinae", 55885, null,
                            [ ["Caenorhabditis", 6237, null,
                              [ ["C. elegans", 6239, "Caenorhabditis elegans" ],
                              ["C. angaria", 860376, "Caenorhabditis angaria" ],
                              ["C. brenneri", 135651, "Caenorhabditis brenneri" ],
                              ["C. briggsae", 6238, "Caenorhabditis briggsae" ],
                              ["C. japonica", 281687, "Caenorhabditis japonica" ],
                              ["C. remanei", 31234, "Caenorhabditis remanei" ],
                              ["C. sp. 5 ju800", 1550068, "Caenorhabditis sinica" ],
                              ["C. sp. 7 ju1286", 1094335, "Caenorhabditis afra" ],
                              ["C. sp. 9 ju1422", 1611254, "Caenorhabditis nigoni" ],
                              ["C. tropicalis", 1561998, "Caenorhabditis tropicalis" ] ] ] ] ] ] ],
                        ["Heterorhabditidae", 33254, null,
                          [ ["Heterorhabditis", 37861, null,
                            [ ["H. bacteriophora/m31e", 37862, "Heterorhabditis bacteriophora" ] ] ] ] ] ] ],
                      ["Panagrolaimoidea", 55746, null,
                        [ ["Panagrolaimidae", 114848, null,
                          [ ["Panagrellus", 6232, null,
                            [ ["Microworm", 6233, "Panagrellus redivivus" ] ] ] ] ],
                        ["Strongyloididae", 6246, null,
                          [ ["Strongyloides", 6247, null,
                            [ ["Threadworm", 34506, "Strongyloides ratti" ] ] ] ] ] ] ],
                      ["Strongylida", 6308, null,
                        [ ["Ancylostomatoidea", 33277, null,
                          [ ["Ancylostomatidae", 33278, null,
                            [ ["Ancylostomatinae", 53469, null,
                              [ ["Ancylostoma", 29169, null,
                                [ ["A. ceylanicum", 53326, "Ancylostoma ceylanicum" ] ] ] ] ],
                            ["Bunostominae", 53477, null,
                              [ ["Necator", 51030, null,
                                [ ["N. americanus", 51031, "Necator americanus" ] ] ] ] ] ] ] ] ],
                        ["Trichostrongyloidea", 6314, null,
                          [ ["Haemonchidae", 126387, null,
                            [ ["Haemonchinae", 33260, null,
                              [ ["Haemonchus", 6288, null,
                                [ ["Barber pole worm", 6289, "Haemonchus contortus" ] ] ] ] ] ] ] ] ] ] ] ] ],
                    ["Ascaridida", 6249, null,
                      [ ["Ascaridoidea", 33256, null,
                        [ ["Ascarididae", 6250, null,
                          [ ["Ascaris", 6251, null,
                            [ ["Pig roundworm", 6253, "Ascaris suum" ] ] ] ] ] ] ] ] ],
                    ["Diplogasterida", 50827, null,
                      [ ["Neodiplogasteridae", 54124, null,
                        [ ["Pristionchus", 54125, null,
                          [ ["P. exspectatus", 1195656, "Pristionchus exspectatus" ],
                          ["P. pacificus", 54126, "Pristionchus pacificus" ] ] ] ] ] ] ],
                    ["Spirurida", 6274, null,
                      [ ["Filarioidea", 6295, null,
                        [ ["Onchocercidae", 6296, null,
                          [ ["Brugia", 6278, null,
                            [ ["Filarial worm", 6279, "Brugia malayi" ] ] ],
                          ["Dirofilaria", 6286, null,
                            [ ["Dog heartworm", 6287, "Dirofilaria immitis" ] ] ],
                          ["Loa", 7208, null,
                            [ ["Eye worm", 7209, "Loa loa" ] ] ],
                          ["Onchocerca", 6281, null,
                            [ ["O. volvulus", 6282, "Onchocerca volvulus" ] ] ] ] ] ] ] ] ],
                    ["Tylenchida", 6300, null,
                      [ ["Aphelenchina", 1182516, null,
                        [ ["Aphelenchoidea", 120862, null,
                          [ ["Aphelenchoididae", 33823, null,
                            [ ["Bursaphelenchus", 6324, null,
                              [ ["Pine wood nematode", 6326, "Bursaphelenchus xylophilus" ] ] ] ] ] ] ] ] ],
                      ["Tylenchina", 33283, null,
                        [ ["Tylenchoidea", 33284, null,
                          [ ["Meloidogynidae", 315429, null,
                            [ ["Meloidogyninae", 33285, null,
                              [ ["Meloidogyne", 189290, null,
                                [ ["M. hapla", 6305, "Meloidogyne hapla" ],
                                ["Meloidogyne incognita group", 654580, null,
                                  [ ["M. incognita", 6306, "Meloidogyne incognita" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
                  ["Enoplea", 119088, null,
                    [ ["Dorylaimia", 1457286, null,
                      [ ["Trichinellida", 6329, null,
                        [ ["Trichinellidae", 6332, null,
                          [ ["Trichinella", 6333, null,
                            [ ["Trichinella", 6334, "Trichinella spiralis" ] ] ] ] ],
                        ["Trichuridae", 119093, null,
                          [ ["Trichuris", 36086, null,
                            [ ["Whipworm", 68888, "Trichuris suis" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
              ["Lophotrochozoa", 1206795, null,
                [ ["Mollusca", 6447, null,
                  [ ["Gastropoda", 6448, null,
                    [ ["Heterobranchia", 216305, null,
                      [ ["Euthyneura", 216307, null,
                        [ ["Euopisthobranchia", 6496, null,
                          [ ["Aplysiomorpha", 6497, null,
                            [ ["Aplysioidea", 216318, null,
                              [ ["Aplysiidae", 6498, null,
                                [ ["Aplysia", 6499, null,
                                  [ ["Sea hare", 6500, "Aplysia californica" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
          ["Cnidaria", 6073, null,
            [ ["Anthozoa", 6101, null,
              [ ["Hexacorallia", 6102, null,
                [ ["Actiniaria", 6103, null,
                  [ ["Edwardsiidae", 45349, null,
                    [ ["Nematostella", 45350, null,
                      [ ["Starlet sea anemone", 45351, "Nematostella vectensis" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
      ["Fungi", 4751, null,
        [ ["Dikarya", 451864, null,
          [ ["Ascomycota", 4890, null,
            [ ["saccharomyceta", 716545, null,
              [ ["Saccharomycotina", 147537, null,
                [ ["Saccharomycetes", 4891, null,
                  [ ["Saccharomycetales", 4892, null,
                    [ ["Saccharomycetaceae", 4893, null,
                      [ ["Saccharomyces", 4930, null,
                        [ ["S. cerevisiae", 4932, "Saccharomyces cerevisiae",
                          [ ["S. cerevisiae", 559292, "Saccharomyces cerevisiae S288C" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
    ["Alveolata", 33630, null,
      [ ["Apicomplexa", 5794, null,
        [ ["Aconoidasida", 422676, null,
          [ ["Haemosporida", 5819, null,
            [ ["Plasmodiidae", 1639119, null,
              [ ["Plasmodium", 5820, null,
                [ ["Plasmodium (Laverania)", 418107, null,
                  [ ["P. falciparum", 5833, "Plasmodium falciparum",
                    [ ["Plasmodium falciparum 3d7", 36329, "Plasmodium falciparum 3D7" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
      ["Ciliophora", 5878, null,
        [ ["Intramacronucleata", 431838, null,
          [ ["Spirotrichea", 33829, null,
            [ ["Stichotrichia", 194286, null,
              [ ["Sporadotrichida", 693921, null,
                [ ["Oxytrichidae", 57506, null,
                  [ ["Oxytrichinae", 1001750, null,
                    [ ["Oxytricha", 5943, null,
                      [ ["Oxytricha trifallax", 1172189, "Oxytricha trifallax" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
  ["Bacteria", 2, null,
    [ ["Proteobacteria", 1224, null,
      [ ["Gammaproteobacteria", 1236, null,
        [ ["Pseudomonadales", 72274, null,
          [ ["Moraxellaceae", 468, null,
            [ ["Acinetobacter", 469, null,
              [ ["Acinetobacter calcoaceticus/baumannii complex", 909768, null,
                [ ["Acinetobacter baumannii", 470, null,
                  [ ["Acinetobacter baumannii", 1100841, "Acinetobacter baumannii TYTH-1" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
    ["Terrabacteria group", 1783272, null,
      [ ["Firmicutes", 1239, null,
        [ ["Bacilli", 91061, null,
          [ ["Bacillales", 1385, null,
            [ ["Staphylococcaceae", 90964, null,
              [ ["Staphylococcus", 1279, null,
                [ ["Staphylococcus aureus", 1280, null,
                  [ ["Staphylococcus aureus subsp. aureus", 46170, null,
                    [ ["Staph", 93061, "Staphylococcus aureus subsp. aureus NCTC 8325" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
["Viruses", 10239, null,
  [ ["ssRNA viruses", 439488, null,
    [ ["ssRNA negative-strand viruses", 35301, null,
      [ ["Mononegavirales", 11157, null,
        [ ["Filoviridae", 11266, null,
          [ ["Ebolavirus", 186536, null,
            [ ["Ebola virus", 186538, "Zaire ebolavirus" ],
            ["Bundibugyo ebolavirus", 565995, "Bundibugyo ebolavirus" ],
            ["Reston ebolavirus", 186539, "Reston ebolavirus" ],
            ["Sudan ebolavirus", 186540, "Sudan ebolavirus" ],
            ["Tai forest ebolavirus", 186541, "Tai Forest ebolavirus" ] ] ],
          ["Marburgvirus", 186537, null,
            [ ["Marburg virus", 11269, "Marburg marburgvirus" ] ] ] ] ] ] ] ] ],
    ["ssRNA positive-strand viruses, no DNA stage", 35278, null,
      [ ["Nidovirales", 76804, null,
        [ ["Coronaviridae", 11118, null,
          [ ["Coronavirinae", 693995, null,
            [ ["Betacoronavirus", 694002, null,
              [ ["Severe acute respiratory syndrome-related coronavirus", 694009, null,
                [ ["SARS coronavirus", 227859, "SARS coronavirus" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
  ["Retro-transcribing viruses", 35268, null,
    [ ["Hepadnaviridae", 10404, null,
      [ ["Orthohepadnavirus", 10405, null,
        [ ["Hbv", 10407, "Hepatitis B virus" ] ] ] ] ],
    ["Retroviridae", 11632, null,
      [ ["Orthoretrovirinae", 327045, null,
        [ ["Betaretrovirus", 140052, null,
          [ ["MMTV", 11757, "Mouse mammary tumor virus" ] ] ] ] ] ] ] ] ],
  ["dsDNA viruses, no RNA stage", 35237, null,
    [ ["Papillomaviridae", 151340, null,
      [ ["Alphapapillomavirus", 333750, null,
        [ ["Alphapapillomavirus 14", 931244, null,
          [ ["Hpv", 333769, "Human papillomavirus type 90" ] ] ] ] ] ] ] ] ] ] ] ] ];
