/* jshint maxlen: false, unused: false */
var dbDbTree = ["root", 1, null,
[ ["cellular organisms", 131567, null,
  [ ["Eukaryota", 2759, null,
    [ ["Opisthokonta", 33154, null,
      [ ["Metazoa", 33208, null,
        [ ["Eumetazoa", 6072, null,
          [ ["Bilateria", 33213, null,
            [ ["Deuterostomia", 33511, null,
              [ ["Chordata", 7711, null,
                [ ["Craniata", 89593, null,
                  [ ["Vertebrata", 7742, null,
                    [ ["Gnathostomata", 7776, null,
                      [ ["Teleostomi", 117570, null,
                        [ ["Euteleostomi", 117571, null,
                          [ ["Sarcopterygii", 8287, null,
                            [ ["Dipnotetrapodomorpha", 1338369, null,
                              [ ["Tetrapoda", 32523, null,
                                [ ["Amniota", 32524, null,
                                  [ ["Mammalia", 40674, null,
                                    [ ["Theria", 32525, null,
                                      [ ["Eutheria", 9347, null,
                                        [ ["Boreoeutheria", 1437010, null,
                                          [ ["Euarchontoglires", 314146, null,
                                            [ ["Primates", 9443, null,
                                              [ ["Haplorrhini", 376913, null,
                                                [ ["Simiiformes", 314293, null,
                                                  [ ["Catarrhini", 9526, null,
                                                    [ ["Hominoidea", 314295, null,
                                                      [ ["Hominidae", 9604, null,
                                                        [ ["Homininae", 207598, null,
                                                          [ ["Homo", 9605, null,
                                                            [ ["Human", 9606, "Homo sapiens" ] ] ],
                                                          ["Pan", 9596, null,
                                                            [ ["Chimp", 9598, "Pan troglodytes" ],
                                                            ["Bonobo", 9597, "Pan paniscus" ] ] ],
                                                          ["Gorilla", 9592, null,
                                                            [ ["Gorilla gorilla", 9593, null,
                                                              [ ["Gorilla", 9595, "Gorilla gorilla gorilla" ] ] ] ] ] ] ],
                                                        ["Ponginae", 607660, null,
                                                          [ ["Pongo", 9599, null,
                                                            [ ["Orangutan", 9601, "Pongo abelii" ] ] ] ] ] ] ],
                                                      ["Hylobatidae", 9577, null,
                                                        [ ["Nomascus", 325165, null,
                                                          [ ["Gibbon", 61853, "Nomascus leucogenys" ] ] ] ] ] ] ],
                                                    ["Cercopithecoidea", 314294, null,
                                                      [ ["Cercopithecidae", 9527, null,
                                                        [ ["Cercopithecinae", 9528, null,
                                                          [ ["Macaca", 9539, null,
                                                            [ ["Crab-eating macaque", 9541, "Macaca fascicularis" ],
                                                            ["Rhesus", 9544, "Macaca mulatta" ] ] ],
                                                          ["Papio", 9554, null,
                                                            [ ["Baboon (anubis)", 9555, "Papio anubis" ],
                                                            ["Papio hamadryas", 9557, null,
                                                              [ ["Baboon (hamadryas)", 9562, "Papio hamadryas hamadryas" ] ] ] ] ] ] ] ] ] ] ] ] ],
                                                  ["Platyrrhini", 9479, null,
                                                    [ ["Cebidae", 9498, null,
                                                      [ ["Callitrichinae", 9480, null,
                                                        [ ["Callithrix", 9481, null,
                                                          [ ["Marmoset", 9483, "Callithrix jacchus" ] ] ] ] ],
                                                      ["Saimiriinae", 378850, null,
                                                        [ ["Saimiri", 9520, null,
                                                          [ ["Saimiri boliviensis", 27679, null,
                                                            [ ["Squirrel monkey", 39432, "Saimiri boliviensis boliviensis" ] ] ] ] ] ] ] ] ] ] ] ] ],
                                                ["Tarsiiformes", 376912, null,
                                                  [ ["Tarsiidae", 9475, null,
                                                    [ ["Tarsius", 9476, null,
                                                      [ ["Tarsier", 9478, "Tarsius syrichta" ] ] ] ] ] ] ] ] ],
                                              ["Strepsirrhini", 376911, null,
                                                [ ["Lemuriformes", 376915, null,
                                                  [ ["Cheirogaleidae", 30615, null,
                                                    [ ["Microcebus", 13149, null,
                                                      [ ["Mouse lemur", 30608, "Microcebus murinus" ] ] ] ] ] ] ],
                                                ["Lorisiformes", 376917, null,
                                                  [ ["Galagidae", 40297, null,
                                                    [ ["Otolemur", 30610, null,
                                                      [ ["Bushbaby", 30611, "Otolemur garnettii" ] ] ] ] ] ] ] ] ] ] ],
                                            ["Glires", 314147, null,
                                              [ ["Rodentia", 9989, null,
                                                [ ["Sciurognathi", 33553, null,
                                                  [ ["Muroidea", 337687, null,
                                                    [ ["Muridae", 10066, null,
                                                      [ ["Murinae", 39107, null,
                                                        [ ["Mus", 10088, null,
                                                          [ ["Mus", 862507, null,
                                                            [ ["Mouse", 10090, "Mus musculus" ] ] ] ] ],
                                                        ["Rattus", 10114, null,
                                                          [ ["Rat", 10116, "Rattus norvegicus" ] ] ] ] ] ] ],
                                                    ["Cricetidae", 337677, null,
                                                      [ ["Cricetinae", 10026, null,
                                                        [ ["Cricetulus", 10028, null,
                                                          [ ["Chinese hamster", 10029, "Cricetulus griseus" ] ] ] ] ] ] ] ] ],
                                                  ["Heteromyidae", 10015, null,
                                                    [ ["Dipodomyinae", 38662, null,
                                                      [ ["Dipodomys", 10016, null,
                                                        [ ["Kangaroo rat", 10020, "Dipodomys ordii" ] ] ] ] ] ] ],
                                                  ["Sciuridae", 55153, null,
                                                    [ ["Xerinae", 337726, null,
                                                      [ ["Marmotini", 337730, null,
                                                        [ ["Ictidomys", 1141640, null,
                                                          [ ["Squirrel", 43179, "Ictidomys tridecemlineatus" ] ] ] ] ] ] ] ] ] ] ],
                                                ["Hystricognathi", 33550, null,
                                                  [ ["Bathyergidae", 10167, null,
                                                    [ ["Heterocephalus", 10180, null,
                                                      [ ["Naked mole-rat", 10181, "Heterocephalus glaber" ] ] ] ] ],
                                                  ["Caviidae", 10139, null,
                                                    [ ["Cavia", 10140, null,
                                                      [ ["Guinea pig", 10141, "Cavia porcellus" ] ] ] ] ] ] ] ] ],
                                              ["Lagomorpha", 9975, null,
                                                [ ["Leporidae", 9979, null,
                                                  [ ["Oryctolagus", 9984, null,
                                                    [ ["Rabbit", 9986, "Oryctolagus cuniculus" ] ] ] ] ],
                                                ["Ochotonidae", 9976, null,
                                                  [ ["Ochotona", 9977, null,
                                                    [ ["Pika", 9978, "Ochotona princeps" ] ] ] ] ] ] ] ] ],
                                            ["Scandentia", 9392, null,
                                              [ ["Tupaiidae", 9393, null,
                                                [ ["Tupaia", 9394, null,
                                                  [ ["Tree shrew", 37347, "Tupaia belangeri" ] ] ] ] ] ] ] ] ],
                                          ["Laurasiatheria", 314145, null,
                                            [ ["Insectivora", 9362, null,
                                              [ ["Erinaceidae", 9363, null,
                                                [ ["Erinaceinae", 30577, null,
                                                  [ ["Erinaceus", 9364, null,
                                                    [ ["Hedgehog", 9365, "Erinaceus europaeus" ] ] ] ] ] ] ],
                                              ["Soricidae", 9376, null,
                                                [ ["Soricinae", 183663, null,
                                                  [ ["Sorex", 9379, null,
                                                    [ ["Shrew", 42254, "Sorex araneus" ] ] ] ] ] ] ] ] ],
                                            ["Cetartiodactyla", 91561, null,
                                              [ ["Suina", 35497, null,
                                                [ ["Suidae", 9821, null,
                                                  [ ["Sus", 9822, null,
                                                    [ ["Pig", 9823, "Sus scrofa" ] ] ] ] ] ] ],
                                              ["Ruminantia", 9845, null,
                                                [ ["Pecora", 35500, null,
                                                  [ ["Bovidae", 9895, null,
                                                    [ ["Bovinae", 27592, null,
                                                      [ ["Bos", 9903, null,
                                                        [ ["Cow", 9913, "Bos taurus" ] ] ] ] ],
                                                    ["Caprinae", 9963, null,
                                                      [ ["Ovis", 9935, null,
                                                        [ ["Sheep", 9940, "Ovis aries" ] ] ] ] ] ] ] ] ] ] ],
                                              ["Cetacea", 9721, null,
                                                [ ["Mysticeti", 9761, null,
                                                  [ ["Balaenopteridae", 9765, null,
                                                    [ ["Balaenoptera", 9766, null,
                                                      [ ["Balaenoptera acutorostrata", 9767, null,
                                                        [ ["Minke whale", 310752, "Balaenoptera acutorostrata scammoni" ] ] ] ] ] ] ] ] ],
                                                ["Odontoceti", 9722, null,
                                                  [ ["Delphinidae", 9726, null,
                                                    [ ["Tursiops", 9738, null,
                                                      [ ["Dolphin", 9739, "Tursiops truncatus" ] ] ] ] ] ] ] ] ],
                                              ["Tylopoda", 9834, null,
                                                [ ["Camelidae", 9835, null,
                                                  [ ["Vicugna", 30539, null,
                                                    [ ["Alpaca", 30538, "Vicugna pacos" ] ] ] ] ] ] ] ] ],
                                            ["Perissodactyla", 9787, null,
                                              [ ["Equidae", 9788, null,
                                                [ ["Equus", 9789, null,
                                                  [ ["Equus", 35510, null,
                                                    [ ["Horse", 9796, "Equus caballus" ] ] ] ] ] ] ],
                                              ["Rhinocerotidae", 9803, null,
                                                [ ["Ceratotherium", 9806, null,
                                                  [ ["Ceratotherium simum", 9807, null,
                                                    [ ["White rhinoceros", 73337, "Ceratotherium simum simum" ] ] ] ] ] ] ] ] ],
                                            ["Carnivora", 33554, null,
                                              [ ["Caniformia", 379584, null,
                                                [ ["Canidae", 9608, null,
                                                  [ ["Canis", 9611, null,
                                                    [ ["Canis lupus", 9612, null,
                                                      [ ["Dog", 9615, "Canis lupus familiaris" ] ] ] ] ] ] ],
                                                ["Mustelidae", 9655, null,
                                                  [ ["Mustelinae", 169418, null,
                                                    [ ["Mustela", 9665, null,
                                                      [ ["Mustela putorius", 9668, null,
                                                        [ ["Ferret ", 9669, "Mustela putorius furo" ] ] ] ] ] ] ] ] ],
                                                ["Ursidae", 9632, null,
                                                  [ ["Ailuropoda", 9645, null,
                                                    [ ["Panda", 9646, "Ailuropoda melanoleuca" ] ] ] ] ] ] ],
                                              ["Feliformia", 379583, null,
                                                [ ["Felidae", 9681, null,
                                                  [ ["Felinae", 338152, null,
                                                    [ ["Felis", 9682, null,
                                                      [ ["Cat", 9685, "Felis catus" ] ] ] ] ] ] ] ] ] ] ],
                                            ["Chiroptera", 9397, null,
                                              [ ["Megachiroptera", 30559, null,
                                                [ ["Pteropodidae", 9398, null,
                                                  [ ["Pteropodinae", 77225, null,
                                                    [ ["Pteropus", 9401, null,
                                                      [ ["Megabat", 132908, "Pteropus vampyrus" ] ] ] ] ] ] ] ] ],
                                              ["Microchiroptera", 30560, null,
                                                [ ["Vespertilionidae", 9431, null,
                                                  [ ["Myotis", 9434, null,
                                                    [ ["Microbat", 59463, "Myotis lucifugus" ] ] ] ] ] ] ] ] ] ] ] ] ],
                                        ["Afrotheria", 311790, null,
                                          [ ["Proboscidea", 9779, null,
                                            [ ["Elephantidae", 9780, null,
                                              [ ["Loxodonta", 9784, null,
                                                [ ["Elephant", 9785, "Loxodonta africana" ] ] ] ] ] ] ],
                                          ["Sirenia", 9774, null,
                                            [ ["Trichechidae", 9775, null,
                                              [ ["Trichechus", 9776, null,
                                                [ ["Trichechus manatus", 9778, null,
                                                  [ ["Manatee", 127582, "Trichechus manatus latirostris" ] ] ] ] ] ] ] ] ],
                                          ["Hyracoidea", 9810, null,
                                            [ ["Procaviidae", 9811, null,
                                              [ ["Procavia", 9812, null,
                                                [ ["Rock hyrax", 9813, "Procavia capensis" ] ] ] ] ] ] ],
                                          ["Tenrecidae", 9369, null,
                                            [ ["Tenrecinae", 176113, null,
                                              [ ["Echinops", 9370, null,
                                                [ ["Tenrec", 9371, "Echinops telfairi" ] ] ] ] ] ] ] ] ],
                                        ["Xenarthra", 9348, null,
                                          [ ["Cingulata", 948951, null,
                                            [ ["Dasypodidae", 9359, null,
                                              [ ["Dasypus", 9360, null,
                                                [ ["Armadillo", 9361, "Dasypus novemcinctus" ] ] ] ] ] ] ],
                                          ["Pilosa", 948950, null,
                                            [ ["Folivora", 948953, null,
                                              [ ["Megalonychidae", 227508, null,
                                                [ ["Choloepus", 9357, null,
                                                  [ ["Sloth", 9358, "Choloepus hoffmanni" ] ] ] ] ] ] ] ] ] ] ] ] ],
                                      ["Metatheria", 9263, null,
                                        [ ["Diprotodontia", 38609, null,
                                          [ ["Macropodidae", 9307, null,
                                            [ ["Macropus", 9312, null,
                                              [ ["Wallaby", 9315, "Macropus eugenii" ] ] ] ] ] ] ],
                                        ["Dasyuromorphia", 38608, null,
                                          [ ["Dasyuridae", 9277, null,
                                            [ ["Sarcophilus", 9304, null,
                                              [ ["Tasmanian devil", 9305, "Sarcophilus harrisii" ] ] ] ] ] ] ],
                                        ["Didelphimorphia", 38605, null,
                                          [ ["Didelphidae", 9265, null,
                                            [ ["Didelphinae", 126287, null,
                                              [ ["Monodelphis", 13615, null,
                                                [ ["Opossum", 13616, "Monodelphis domestica" ] ] ] ] ] ] ] ] ] ] ] ] ],
                                    ["Prototheria", 9254, null,
                                      [ ["Monotremata", 9255, null,
                                        [ ["Ornithorhynchidae", 9256, null,
                                          [ ["Ornithorhynchus", 9257, null,
                                            [ ["Platypus", 9258, "Ornithorhynchus anatinus" ] ] ] ] ] ] ] ] ] ] ],
                                  ["Sauropsida", 8457, null,
                                    [ ["Sauria", 32561, null,
                                      [ ["Archelosauria", 1329799, null,
                                        [ ["Archosauria", 8492, null,
                                          [ ["Dinosauria", 436486, null,
                                            [ ["Saurischia", 436489, null,
                                              [ ["Theropoda", 436491, null,
                                                [ ["Coelurosauria", 436492, null,
                                                  [ ["Aves", 8782, null,
                                                    [ ["Neognathae", 8825, null,
                                                      [ ["Galloanserae", 1549675, null,
                                                        [ ["Galliformes", 8976, null,
                                                          [ ["Phasianidae", 9005, null,
                                                            [ ["Phasianinae", 9072, null,
                                                              [ ["Gallus", 9030, null,
                                                                [ ["Chicken", 9031, "Gallus gallus" ] ] ] ] ],
                                                            ["Meleagridinae", 466552, null,
                                                              [ ["Meleagris", 9102, null,
                                                                [ ["Turkey", 9103, "Meleagris gallopavo" ] ] ] ] ] ] ] ] ] ] ],
                                                      ["Passeriformes", 9126, null,
                                                        [ ["Passeroidea", 175121, null,
                                                          [ ["Estrildidae", 37611, null,
                                                            [ ["Estrildinae", 40155, null,
                                                              [ ["Taeniopygia", 59728, null,
                                                                [ ["Zebra finch", 59729, "Taeniopygia guttata" ] ] ] ] ] ] ] ] ],
                                                        ["Thraupidae", 400783, null,
                                                          [ ["Geospiza", 48881, null,
                                                            [ ["Medium ground finch", 48883, "Geospiza fortis" ] ] ] ] ] ] ],
                                                      ["Psittaciformes", 9223, null,
                                                        [ ["Psittaculidae", 1545690, null,
                                                          [ ["Melopsittacus", 13145, null,
                                                            [ ["Budgerigar", 13146, "Melopsittacus undulatus" ] ] ] ] ] ] ] ] ],
                                                    ["Palaeognathae", 8783, null,
                                                      [ ["Apterygiformes", 8819, null,
                                                        [ ["Apterygidae", 8820, null,
                                                          [ ["Apteryx", 8821, null,
                                                            [ ["Apteryx australis", 8822, null,
                                                              [ ["Brown kiwi", 202946, "Apteryx australis mantelli" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
                                          ["Crocodylia", 1294634, null,
                                            [ ["Alligatoridae", 1294636, null,
                                              [ ["Alligatorinae", 34915, null,
                                                [ ["Alligator", 8495, null,
                                                  [ ["American alligator", 8496, "Alligator mississippiensis" ] ] ] ] ] ] ] ] ] ] ],
                                        ["Testudines", 8459, null,
                                          [ ["Cryptodira", 8464, null,
                                            [ ["Durocryptodira", 1579337, null,
                                              [ ["Testudinoidea", 8486, null,
                                                [ ["Emydidae", 8476, null,
                                                  [ ["Chrysemys", 8477, null,
                                                    [ ["Chrysemys picta", 8479, null,
                                                      [ ["Painted turtle", 8478, "Chrysemys picta bellii" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
                                      ["Lepidosauria", 8504, null,
                                        [ ["Squamata", 8509, null,
                                          [ ["Bifurcata", 1329961, null,
                                            [ ["Unidentata", 1329950, null,
                                              [ ["Episquamata", 1329912, null,
                                                [ ["Toxicofera", 1329911, null,
                                                  [ ["Iguania", 8511, null,
                                                    [ ["Iguanidae", 8515, null,
                                                      [ ["Polychrotinae", 81957, null,
                                                        [ ["Anolis", 28376, null,
                                                          [ ["Lizard", 28377, "Anolis carolinensis" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
                                ["Amphibia", 8292, null,
                                  [ ["Batrachia", 41666, null,
                                    [ ["Anura", 8342, null,
                                      [ ["Pipoidea", 30319, null,
                                        [ ["Pipidae", 8352, null,
                                          [ ["Xenopodinae", 8360, null,
                                            [ ["Xenopus", 8353, null,
                                              [ ["Silurana", 8363, null,
                                                [ ["X. tropicalis", 8364, "Xenopus tropicalis" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
                            ["Coelacanthimorpha", 118072, null,
                              [ ["Coelacanthiformes", 7894, null,
                                [ ["Coelacanthidae", 7895, null,
                                  [ ["Latimeria", 7896, null,
                                    [ ["Coelacanth", 7897, "Latimeria chalumnae" ] ] ] ] ] ] ] ] ] ] ],
                          ["Actinopterygii", 7898, null,
                            [ ["Actinopteri", 186623, null,
                              [ ["Neopterygii", 41665, null,
                                [ ["Teleostei", 32443, null,
                                  [ ["Osteoglossocephalai", 1489341, null,
                                    [ ["Clupeocephala", 186625, null,
                                      [ ["Otomorpha", 186634, null,
                                        [ ["Ostariophysi", 32519, null,
                                          [ ["Otophysa", 186626, null,
                                            [ ["Cypriniphysae", 186627, null,
                                              [ ["Cypriniformes", 7952, null,
                                                [ ["Cyprinoidea", 30727, null,
                                                  [ ["Cyprinidae", 7953, null,
                                                    [ ["Danio", 7954, null,
                                                      [ ["Zebrafish", 7955, "Danio rerio" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
                                      ["Euteleosteomorpha", 1489388, null,
                                        [ ["Neoteleostei", 123365, null,
                                          [ ["Eurypterygia", 123366, null,
                                            [ ["Ctenosquamata", 123367, null,
                                              [ ["Acanthomorphata", 123368, null,
                                                [ ["Euacanthomorphacea", 123369, null,
                                                  [ ["Percomorphaceae", 1489872, null,
                                                    [ ["Eupercaria", 1489922, null,
                                                      [ ["Perciformes", 8111, null,
                                                        [ ["Cottioidei", 8100, null,
                                                          [ ["Gasterosteales", 1490020, null,
                                                            [ ["Gasterosteidae", 69291, null,
                                                              [ ["Gasterosteus", 69292, null,
                                                                [ ["Stickleback", 69293, "Gasterosteus aculeatus" ] ] ] ] ] ] ] ] ] ] ],
                                                      ["Tetraodontiformes", 31022, null,
                                                        [ ["Tetraodontoidei", 31028, null,
                                                          [ ["Tetradontoidea", 32517, null,
                                                            [ ["Tetraodontidae", 31031, null,
                                                              [ ["Takifugu", 31032, null,
                                                                [ ["Fugu", 31033, "Takifugu rubripes" ] ] ],
                                                              ["Tetraodon", 47144, null,
                                                                [ ["Tetraodon", 99883, "Tetraodon nigroviridis" ] ] ] ] ] ] ] ] ] ] ] ] ],
                                                    ["Ovalentaria", 1489908, null,
                                                      [ ["Atherinomorphae", 1489913, null,
                                                        [ ["Beloniformes", 76071, null,
                                                          [ ["Adrianichthyoidei", 28781, null,
                                                            [ ["Adrianichthyidae", 47757, null,
                                                              [ ["Oryziinae", 8088, null,
                                                                [ ["Oryzias", 8089, null,
                                                                  [ ["Medaka", 8090, "Oryzias latipes" ] ] ] ] ] ] ] ] ] ] ] ] ],
                                                      ["Cichlomorphae", 1489910, null,
                                                        [ ["Cichliformes", 1489911, null,
                                                          [ ["Cichlidae", 8113, null,
                                                            [ ["African cichlids", 319095, null,
                                                              [ ["Pseudocrenilabrinae", 318546, null,
                                                                [ ["Oreochromini", 1315725, null,
                                                                  [ ["Oreochromis", 8139, null,
                                                                    [ ["Nile tilapia", 8128, "Oreochromis niloticus" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
                                                ["Paracanthomorphacea", 1489838, null,
                                                  [ ["Zeiogadaria", 1489841, null,
                                                    [ ["Gadariae", 1489843, null,
                                                      [ ["Gadiformes", 8043, null,
                                                        [ ["Gadoidei", 1489845, null,
                                                          [ ["Gadidae", 8045, null,
                                                            [ ["Gadus", 8048, null,
                                                              [ ["Atlantic cod", 8049, "Gadus morhua" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
                      ["Chondrichthyes", 7777, null,
                        [ ["Holocephali", 7863, null,
                          [ ["Chimaeriformes", 7864, null,
                            [ ["Callorhinchidae", 7865, null,
                              [ ["Callorhinchus", 7866, null,
                                [ ["Elephant shark", 7868, "Callorhinchus milii" ] ] ] ] ] ] ] ] ] ] ] ] ],
                    ["Cyclostomata", 1476529, null,
                      [ ["Hyperoartia", 117569, null,
                        [ ["Petromyzontiformes", 7745, null,
                          [ ["Petromyzontidae", 7746, null,
                            [ ["Petromyzon", 7756, null,
                              [ ["Lamprey", 7757, "Petromyzon marinus" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
                ["Cephalochordata", 7735, null,
                  [ ["Branchiostomidae", 7736, null,
                    [ ["Branchiostoma", 7737, null,
                      [ ["Lancelet", 7739, "Branchiostoma floridae" ] ] ] ] ] ] ],
                ["Tunicata", 7712, null,
                  [ ["Ascidiacea", 7713, null,
                    [ ["Enterogona", 183770, null,
                      [ ["Phlebobranchia", 7716, null,
                        [ ["Cionidae", 7717, null,
                          [ ["Ciona", 7718, null,
                            [ ["C. intestinalis", 7719, "Ciona intestinalis" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
              ["Echinodermata", 7586, null,
                [ ["Eleutherozoa", 133551, null,
                  [ ["Echinozoa", 7624, null,
                    [ ["Echinoidea", 7625, null,
                      [ ["Euechinoidea", 7638, null,
                        [ ["Echinacea", 7674, null,
                          [ ["Echinoida", 7675, null,
                            [ ["Strongylocentrotidae", 31181, null,
                              [ ["Strongylocentrotus", 7664, null,
                                [ ["S. purpuratus", 7668, "Strongylocentrotus purpuratus" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
            ["Protostomia", 33317, null,
              [ ["Ecdysozoa", 1206794, null,
                [ ["Panarthropoda", 88770, null,
                  [ ["Arthropoda", 6656, null,
                    [ ["Mandibulata", 197563, null,
                      [ ["Pancrustacea", 197562, null,
                        [ ["Hexapoda", 6960, null,
                          [ ["Insecta", 50557, null,
                            [ ["Dicondylia", 85512, null,
                              [ ["Pterygota", 7496, null,
                                [ ["Neoptera", 33340, null,
                                  [ ["Endopterygota", 33392, null,
                                    [ ["Diptera", 7147, null,
                                      [ ["Brachycera", 7203, null,
                                        [ ["Muscomorpha", 43733, null,
                                          [ ["Eremoneura", 480118, null,
                                            [ ["Cyclorrhapha", 480117, null,
                                              [ ["Schizophora", 43738, null,
                                                [ ["Acalyptratae", 43741, null,
                                                  [ ["Ephydroidea", 43746, null,
                                                    [ ["Drosophilidae", 7214, null,
                                                      [ ["Drosophilinae", 43845, null,
                                                        [ ["Drosophilini", 46877, null,
                                                          [ ["Drosophilina", 46879, null,
                                                            [ ["Drosophiliti", 186285, null,
                                                              [ ["Drosophila", 7215, null,
                                                                [ ["Sophophora", 32341, null,
                                                                  [ ["melanogaster group", 32346, null,
                                                                    [ ["melanogaster subgroup", 32351, null,
                                                                      [ ["D. melanogaster", 7227, "Drosophila melanogaster" ],
                                                                      ["D. erecta", 7220, "Drosophila erecta" ],
                                                                      ["D. sechellia", 7238, "Drosophila sechellia" ],
                                                                      ["D. simulans", 7240, "Drosophila simulans" ],
                                                                      ["D. yakuba", 7245, "Drosophila yakuba" ] ] ],
                                                                    ["ananassae subgroup", 32347, null,
                                                                      [ ["ananassae species complex", 545632, null,
                                                                        [ ["D. ananassae", 7217, "Drosophila ananassae" ] ] ] ] ] ] ],
                                                                  ["obscura group", 32355, null,
                                                                    [ ["pseudoobscura subgroup", 32358, null,
                                                                      [ ["D. persimilis", 7234, "Drosophila persimilis" ],
                                                                      ["D. pseudoobscura", 7237, "Drosophila pseudoobscura" ] ] ] ] ] ] ],
                                                                ["Drosophila", 32281, null,
                                                                  [ ["repleta group", 32321, null,
                                                                    [ ["mulleri subgroup", 32324, null,
                                                                      [ ["mojavensis species complex", 198037, null,
                                                                        [ ["D. mojavensis", 7230, "Drosophila mojavensis" ] ] ] ] ] ] ],
                                                                  ["virilis group", 32335, null,
                                                                    [ ["D. virilis", 7244, "Drosophila virilis" ] ] ] ] ],
                                                                ["Hawaiian Drosophila", 504493, null,
                                                                  [ ["picture wing clade", 48384, null,
                                                                    [ ["grimshawi clade", 48301, null,
                                                                      [ ["grimshawi group", 48302, null,
                                                                        [ ["grimshawi subgroup", 32378, null,
                                                                          [ ["D. grimshawi", 7222, "Drosophila grimshawi" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
                                      ["Nematocera", 7148, null,
                                        [ ["Culicomorpha", 43786, null,
                                          [ ["Culicoidea", 41827, null,
                                            [ ["Culicidae", 7157, null,
                                              [ ["Anophelinae", 43816, null,
                                                [ ["Anopheles", 7164, null,
                                                  [ ["Cellia", 44534, null,
                                                    [ ["Pyretophorus", 44537, null,
                                                      [ ["gambiae species complex", 44542, null,
                                                        [ ["A. gambiae", 7165, "Anopheles gambiae" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
                                    ["Hymenoptera", 7399, null,
                                      [ ["Apocrita", 7400, null,
                                        [ ["Aculeata", 7434, null,
                                          [ ["Apoidea", 34735, null,
                                            [ ["Apidae", 7458, null,
                                              [ ["Apinae", 70987, null,
                                                [ ["Apini", 83321, null,
                                                  [ ["Apis", 7459, null,
                                                    [ ["A. mellifera", 7460, "Apis mellifera" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
                ["Nematoda", 6231, null,
                  [ ["Chromadorea", 119089, null,
                    [ ["Rhabditida", 6236, null,
                      [ ["Rhabditoidea", 55879, null,
                        [ ["Rhabditidae", 6243, null,
                          [ ["Peloderinae", 55885, null,
                            [ ["Caenorhabditis", 6237, null,
                              [ ["C. elegans", 6239, "Caenorhabditis elegans" ],
                              ["C. brenneri", 135651, "Caenorhabditis brenneri" ],
                              ["C. briggsae", 6238, "Caenorhabditis briggsae" ],
                              ["C. japonica", 281687, "Caenorhabditis japonica" ],
                              ["C. remanei", 31234, "Caenorhabditis remanei" ] ] ] ] ] ] ] ] ] ] ],
                    ["Diplogasterida", 50827, null,
                      [ ["Neodiplogasteridae", 54124, null,
                        [ ["Pristionchus", 54125, null,
                          [ ["P. pacificus", 54126, "Pristionchus pacificus" ] ] ] ] ] ] ] ] ] ] ] ] ],
              ["Lophotrochozoa", 1206795, null,
                [ ["Mollusca", 6447, null,
                  [ ["Gastropoda", 6448, null,
                    [ ["Heterobranchia", 216305, null,
                      [ ["Euthyneura", 216307, null,
                        [ ["Euopisthobranchia", 6496, null,
                          [ ["Aplysiomorpha", 6497, null,
                            [ ["Aplysioidea", 216318, null,
                              [ ["Aplysiidae", 6498, null,
                                [ ["Aplysia", 6499, null,
                                  [ ["Sea hare", 6500, "Aplysia californica" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
      ["Fungi", 4751, null,
        [ ["Dikarya", 451864, null,
          [ ["Ascomycota", 4890, null,
            [ ["saccharomyceta", 716545, null,
              [ ["Saccharomycotina", 147537, null,
                [ ["Saccharomycetes", 4891, null,
                  [ ["Saccharomycetales", 4892, null,
                    [ ["Saccharomycetaceae", 4893, null,
                      [ ["Saccharomyces", 4930, null,
                        [ ["S. cerevisiae", 4932, "Saccharomyces cerevisiae",
                          [ ["S. cerevisiae", 559292, "Saccharomyces cerevisiae S288c" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ],
["Viruses", 10239, null,
  [ ["ssRNA viruses", 439488, null,
    [ ["ssRNA negative-strand viruses", 35301, null,
      [ ["Mononegavirales", 11157, null,
        [ ["Filoviridae", 11266, null,
          [ ["Ebolavirus", 186536, null,
            [ ["Ebola virus", 186538, "Zaire ebolavirus" ] ] ] ] ] ] ] ] ] ] ] ] ] ] ];
