kentSrc = ../../../..
A = eapDaemon
preMyLibs += ../lib/$(MACHTYPE)/eaplib.a ../../encodeDataWarehouse/lib/$(MACHTYPE)/edwlib.a ../../../../parasol/lib/$(MACHTYPE)/paralib.a
include $(kentSrc)/inc/userApp.mk
