table bedHeatmapEve
"Browser extensible data (12 fields) plus heatmap fields for EVE missense scores."
    (
    string chrom;      "Chromosome (or contig, scaffold, etc.)"
    uint   chromStart; "Start position in chromosome"
    uint   chromEnd;   "End position in chromosome"
    string name;       "Protein name (gene symbol from UniProt file name)"
    uint   score;      "Score from 0-1000 (maximum EVE score x 1000)"
    char[1] strand;    "+ or -"
    uint thickStart;   "Same as chromStart (whole protein span)"
    uint thickEnd;     "Same as chromEnd (whole protein span)"
    uint reserved;     "Unused (always 0)"
    int blockCount;    "Number of amino acid positions covered (heatmap columns)"
    int[blockCount] blockSizes;   "Comma-separated list of block sizes (always 3 per codon)"
    int[blockCount] chromStarts;  "Start positions relative to chromStart"
    int _rowCount;    "Number of heatmap rows (20 standard amino acids)"
    string[_rowCount] _labels; "Row labels|Single-letter amino acid codes (A C D E F G H I K L M N P Q R S T V W Y)"
    lstring _colorBounds; "Comma-separated EVE score thresholds for color interpolation"
    lstring _colorValues; "Comma-separated colors for each threshold score"
    lstring _scoreArray; "Row-major EVE scores; empty cell = wildtype or no data"
    lstring _labelArray; "Row-major mouseover labels (wildtype, variant, EVE score, Class25 prediction)"
    lstring legend; "Legend"
    string uniprotId; "UniProt accession number"
    )
