
LIST=\
wgEncodeMapability.ra \
wgEncodeGencode.ra \
wgEncodeGisDnaPet.ra \
wgEncodeGisRnaSeq.ra \
wgEncodeCshlShortRnaSeq.ra \
wgEncodeAffyRnaChip.ra \
wgEncodeUwDnase.ra \
wgEncodeUwDgf.ra \
wgEncodeHaibMethylRrbs.ra \
wgEncodeAffyRnaChip.ra \
wgEncodeCaltechRnaSeq.ra \
wgEncodeBroadHistone.ra \
wgEncodeRikenCage.ra \
wgEncodeUwHistone.ra \
wgEncodeSunyAlbanyTiling.ra \

include ../../../../makefile.metaDb

