table giabSv 
"Genome In a Bottle Structural Variants (dbVar nstd175)"
    (
    string chrom;      "Reference sequence chromosome or scaffold"
    uint   chromStart; "Start position in chromosome"
    uint   chromEnd;   "End position in chromosome"
    string name;       "Short Name of item"
    uint   score;      "Score from 0-1000"
    char[1] strand;    "+ or -"
    uint thickStart;   "Start of where display should be thick (start codon)"
    uint thickEnd;     "End of where display should be thick (stop codon)"
    uint reserved;     "Used as itemRgb as of 2004-11-22"
    int size;          "Size of variant"
    string varType;    "Type of structural variant"
    string varRegion;     "Variant Region"
    string dbVarUrl ;  "dbVar Region Link"
    string sample_name; "Sample Name"
    string sampleset_name; "Sampleset Name"
    string phenotype;  "Phenotype"
    lstring _mouseOver; "mouseover string"
    )
