
## makefile definitions for the 'birds' assembly hubs

destDir=/hive/data/genomes/asmHubs/birds
srcDir=${HOME}/kent/src/hg/makeDb/doc/birdsAsmHub
orderList=$(CURDIR)/birds.orderList.tsv

indexName=index
testIndexName=testIndex
statsName=asmStats
testStatsName=testAsmStats
dataName=trackData
testDataName=testTrackData
genomesTxt=genomes
hubFile=hub
testHubFile=testHub
hubTxtFile=hub.txt

# these names trigger special behavior in the index page creation scripts:

Name=Birds
name=birds

# Okarito brown kiwi
# defaultAssembly=GCF_003343035.1_aptRow1
defaultAssembly=GCF_003343035.1

include ../asmHubs/asmHubs.mk
