table bed12UniProtMut
"Browser extensible data (12 fields) plus information about uniProt mutation"
    (
    string chrom;      "Chromosome (or contig, scaffold, etc.)"
    uint   chromStart; "Start position in chromosome"
    uint   chromEnd;   "End position in chromosome"
    string name;       "Name of item"
    uint   score;      "Score from 0-1000"
    char[1] strand;    "+ or -"
    uint thickStart;   "Start of where display should be thick (start codon)"
    uint thickEnd;     "End of where display should be thick (stop codon)"
    uint reserved;     "Used as itemRgb as of 2004-11-22"
    int blockCount;    "Number of blocks"
    int[blockCount] blockSizes; "Comma separated list of block sizes"
    int[blockCount] chromStarts; "Start positions relative to chromStart"
    lstring varType;        "Variant Type"
    lstring diseases;       "Diseases"
    lstring mutation;       "Coding seq. mutation"
    lstring comments;       "Comment"
    lstring variationId;       "UniProt variant"
    lstring dbSnpId;       "dbSNP"
    lstring uniProtId;       "UniProt record"
    lstring pmids;       "Source articles"
    )
