
LIST=\
wgEncodeSydhHistone.ra \
wgEncodeSydhTfbs.ra \
wgEncodeUwDnase.ra \
wgEncodeLicrHistone.ra \
wgEncodePsuTfbs.ra \
wgEncodeLicrTfbs.ra \
wgEncodePsuHistone.ra \
wgEncodeSydhRnaSeq.ra \
wgEncodeLicrRnaSeq.ra \
wgEncodeUwRnaSeq.ra
include ../../../../makefile.metaDb
