
LIST=\
wgEncodeAffyRnaChip.ra \
wgEncodeBroadHistone.ra \
wgEncodeBuOrchid.ra \
wgEncodeGencode.ra \
wgEncodeHaibMethylRrbs.ra \
wgEncodeHaibTfbs.ra \
wgEncodeOpenChromChip.ra \
wgEncodeOpenChromDnase.ra \
wgEncodeOpenChromFaire.ra \
wgEncodeOpenChromSynth.ra \
wgEncodeSunyAlbanyTiling.ra \
wgEncodeSunyGeneST.ra \
wgEncodeSunySwitchgear.ra \
wgEncodeSydhHistone.ra \
wgEncodeSydhTfbs.ra \
wgEncodeUncBsuProt.ra \
wgEncodeUwAffyExonArray.ra \
wgEncodeUwHistone.ra \
wgEncodeUwDnase.ra \
wgEncodeCaltechRnaSeq.ra \
wgEncodeCshlLongRnaSeq.ra \
wgEncodeCshlShortRnaSeq.ra \
wgEncodeRikenCage.ra \
wgEncodeHaibMethylSeq.ra \
wgEncodeGisRnaSeq.ra \
wgEncodeGisDnaPet.ra \
wgEncodeUwTfbs.ra \
wgEncodeGisRnaPet.ra \
wgEncodeYaleRnaSeq.ra \
wgEncodeMapability.ra \
wgEncodeUwDgf.ra \
wgEncodeDukeAffyExon.ra 

include ../../../../makefile.metaDb

