table fusionGdbTx
"FusionGDB fusion genes, the part of each partner transcript kept in the fusion"
   (
   string chrom;       "Chromosome"
   uint   chromStart;  "Start position in chromosome"
   uint   chromEnd;    "End position in chromosome"
   string name;        "Feature ID|Fusion gene, number of the breakpoint pair, 5p or 3p partner"
   uint score;         "Not used, always 0"
   char[1] strand;     "Strand of the transcript"
   uint thickStart;    "Start of the kept coding region"
   uint thickEnd;      "End of the kept coding region"
   uint reserved;       "Color, by reading frame"
   int blockCount;     "Number of exons"
   int[blockCount] blockSizes; "Comma separated list of exon sizes"
   int[blockCount] chromStarts; "Exon start positions relative to chromStart"
   string name2;       "Gene of this partner"
   string cdsStartStat; "Status of CDS start annotation|incmpl if the CDS start is cut off at the breakpoint"
   string cdsEndStat;   "Status of CDS end annotation|incmpl if the CDS end is cut off at the breakpoint"
   int[blockCount] exonFrames; "Reading frame of the first coding base of each exon, in the frame of the original transcript"
   string type;        "GENCODE transcript type"
   string geneName;    "Fusion gene, 5' partner::3' partner"
   string geneName2;   "GENCODE V19 transcript|Empty if no transcript contains the breakpoint"
   string geneType;    "Not used"
   string side;           "This feature is the|5' or 3' partner of the fusion"
   string partnerPos;     "Fused to|Link to the fusion partner, the kept part of the other gene's transcript"
   string gene5;          "5' partner gene"
   string pos5;           "5' partner breakpoint"
   string gene3;          "3' partner gene"
   string pos3;           "3' partner breakpoint"
   string frame;          "Reading frame|In-frame or Frame-shift if both breakpoints are in coding exons of at least one transcript pair, Outside CDS if not, Not annotated if FusionGDB has no ORF data"
   string orientation;    "Orientation|Set if a partner gene is on the other strand than the fusion sequence in FusionGDB"
   lstring orfClasses;    "Breakpoint locations|All combinations of breakpoint locations over GENCODE V19 transcript pairs"
   string sources;        "Sources|Data sets in FusionGDB that contain this fusion"
   lstring cancerTypes;   "TCGA cancer types"
   uint   sampleCount;    "Number of TCGA samples"
   lstring samples;       "TCGA samples"
   lstring accessions;    "GenBank transcripts|ESTs and mRNAs in ChiTaRS that support this fusion"
   lstring _mouseOver;    "Mouseover text"
   )
