table fusionGdb
"FusionGDB fusion gene breakpoints, one feature per partner gene"
    (
    string chrom;          "Chromosome"
    uint   chromStart;     "Breakpoint position, 0-based"
    uint   chromEnd;       "Breakpoint position, 1-based"
    string name;           "Feature ID|Fusion gene, number of the breakpoint pair, 5p or 3p partner"
    uint   score;          "Not used, always 0"
    char[1] strand;        "Strand of the partner gene at this breakpoint"
    uint   thickStart;     "Same as chromStart"
    uint   thickEnd;       "Same as chromEnd"
    uint   reserved;       "Color, by reading frame"
    string fusion;         "Fusion gene, 5' partner::3' partner"
    string side;           "This feature is the|5' or 3' partner of the fusion"
    string partnerPos;     "Partner breakpoint|Link to a 10 kbp window around the breakpoint in the other gene"
    string gene5;          "5' partner gene"
    string pos5;           "5' partner breakpoint"
    string gene3;          "3' partner gene"
    string pos3;           "3' partner breakpoint"
    string frame;          "Reading frame|In-frame or Frame-shift if both breakpoints are in coding exons of at least one transcript pair, Outside CDS if not, Not annotated if FusionGDB has no ORF data"
    lstring orfClasses;    "Breakpoint locations|All combinations of breakpoint locations over GENCODE V19 transcript pairs"
    lstring inFrameTx;     "In-frame transcripts|GENCODE V19 transcript pairs, 5'::3', that keep the reading frame"
    string sources;        "Sources|Data sets in FusionGDB that contain this fusion"
    lstring cancerTypes;   "TCGA cancer types"
    uint   sampleCount;    "Number of TCGA samples"
    lstring samples;       "TCGA samples"
    lstring accessions;    "GenBank transcripts|ESTs and mRNAs in ChiTaRS that support this fusion"
    lstring _mouseOver;    "Mouseover text"
    )
