<link type="text/css" rel="stylesheet" media="all" href="http://hgwdev-greg.cse.ucsc.edu/style/nice_menu.css">

<div id="main-menu-whole">

		<div id="main-menu"><div id="block-nice_menus-1" class="clear-block block block-nice_menus">

	<div class="upcorner"></div>
	<div class="blockbg">
		<div class="blockcontent">
						<div class="content">

<ul class="nice-menu nice-menu-down sf-js-enabled" id="nice-menu-1">

<li class="first even"><a href="/index.html" ><span id="home-link">Home</span></a></li> 

<li><a href="/cgi-bin/hgGateway">Genomes</a></li>
<li><a href="/cgi-bin/hgTracks">Genome Browser</a></li>

<li class="menuparent"><span>Tools</span><ul style="display: none; visibility: hidden;">
<li class="first"><a href="/cgi-bin/hgBlat?command=start">Blat</a></li>
<li><a href="/cgi-bin/hgTables">Table Browser</a></li>
<li><a href="/cgi-bin/hgNear">Gene Sorter</a></li>
<li><a href="/cgi-bin/hgGenome">Genome Graphs</a></li>
<li><a href="/cgi-bin/hgPcr">In-Silico PCR</a></li>
<li><a href="/cgi-bin/hgLiftOver">LiftOver</a></li>
<li><a href="/cgi-bin/hgVisiGene">VisiGene</a></li>
<li class="last"><a href="utilities">Other Utilities</a></li>
</ul>
</li>
<li class="menuparent"><span>Mirrors</span><ul style="display: none; visibility: hidden;">
<li class="first"><a href="#">US Server</a></li>
<li><a href="#">Euro Server</a></li>
<li><a href="#">Other Mirrors</a></li>
<li class="last"><a href="#">Mirroring Instructions</a></li>
</ul>
</li>
<li class="menuparent"><span>Downloads</span><ul style="display: none; visibility: hidden;">
<li class="first"><a href="../downloads.html">Genome Data</a></li>
<li><a href="../downloads.html">Source Code</a></li>
<li><a href="../downloads.html">Utilities</a></li>
<li><a href="ftp://hgdownload.cse.ucsc.edu/goldenPath">FTP/MySQL Access</a></li>
<li class="last"><a href="/cgi-bin/hgTables?command=start">Table Browser</a></li>
</ul>
</li>
<li class="menuparent"><span>My Data</span><ul style="display: none; visibility: hidden;">
<li class="first"><a href="http://genomewiki.ucsc.edu/index.php?title=Special:UserloginUCSC">Log in/out</a></li>
<li><a href="/cgi-bin/hgSession?hgS_doMainPage=1">Session</a></li>
<li><a href="/cgi-bin/hgHubConnect">Track Hubs</a></li>
<li class="last"><a href="/cgi-bin/hgCustom">Custom Tracks</a></li>
</ul>
</li>
<li class="menuparent"><span>About Us</span><ul style="display: none; visibility: hidden;">
<li class="first"><a href="news">News</a></li>
<li><a href="publications">Publications</a></li>
<li><a href="citing-ucsc-browser-publication-or-web-page">Cite Us</a></li>
<li><a href="ucsc-genome-browser-acknowledgments">Credits</a></li>
<li><a href="track-and-table-releases">Release Log</a></li>
<li><a href="ucsc-genome-browser-project-team">Staff</a></li>
<li><a href="contact-information-ucsc-genome-project">Contact Us</a></li>
<li><a href="conditions-use">Conditions of Use</a></li>
<li><a href="http://www.cbse.ucsc.edu/jobs">Jobs</a></li>
<li class="last"><a href="../license/">Licenses</a></li>
</ul>
</li>
<li class="menuparent"><span>View</span><ul style="display: none; visibility: hidden;">
<li class="first"><a href="#">as PDF/PS Image</a></li>
<li><a href="#">as DNA</a></li>
<li><a href="#">in other Genomes (UCSC)</a></li>
<li><a href="#">in Ensembl</a></li>
<li><a href="#">in NCBI</a></li>
<li><a href="#">in WormBase</a></li>
<li><a href="#">in FlyBase</a></li>
<li><a href="#">in MGI</a></li>
<li><a href="#">Configure Browser</a></li>
<li><a href="#">Default Tracks</a></li>
<li><a href="#">Default Track Order</a></li>
<li class="last "><a href="#">Reset all user settings</a></li>
</ul>
</li>
<li class="menuparent last"><span>Help</span><ul style="display: none; visibility: hidden;">
<li class="first"><a href="../FAQ/">FAQs</a></li>
<li><a href="../goldenPath/help/hgTracksHelp.html">Browser Documentation</a></li>
<li><a href="../training.html">Training</a></li>
<li><a href="contact-information-ucsc-genome-project">Mailing Lists</a></li>
<li><a href="../mirror.html">Browser Mirrors</a></li>
<li class="last"><a href="http://genomewiki.ucsc.edu/">GenomeWiki</a></li>
</ul>
</li>
</ul>
</div>
		</div>
	</div>
	<div class="downcorner"></div>

</div>
</div><!-- end main-menu -->
</div><!-- end main-menu-whole -->

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.js" type="text/javascript"></script>
<script type="text/javascript" src="NewNavBar2_files/jquery.plugins.js"></script>

<script type="text/javascript">
<!--//--><![CDATA[//><!--
jQuery.extend(Drupal.settings, { "basePath": "/", "nice_menus_options": { "delay": 800, "speed": 1 }, "thickbox": { "close": "Close", "next": "Next \x3e", "prev": "\x3c Prev", "esc_key": "or Esc Key", "next_close": "Next / Close on last", "image_count": "Image !current of !total" }, "custom_search": { "form_target": "_self", "solr": 0 } });
//--><!]]>
</script>