<div id="main-menu-whole">

		<div id="main-menu"><div id="block-nice_menus-1" class="clear-block block block-nice_menus">

	<div class="upcorner"></div>
	<div class="blockbg">
		<div class="blockcontent">
						<div class="content">

<ul class="nice-menu nice-menu-down sf-js-enabled" id="nice-menu-1">

<li class="first even" id="home"><a href="../index.html" ><span id="home-link">Home</span></a></li> 

<li class="menuparent" id="tools1"><a href="../cgi-bin/hgGateway">Genomes</a>
	<ul style="display: none; visibility: hidden;">
	<li class="first"><a href="../cgi-bin/hgTracks?db=hg38&amp;position=lastDbPos">Human GRCh38/hg38</a></li>
	<li><a href="../cgi-bin/hgTracks?db=hg19&amp;position=lastDbPos">Human GRCh37/hg19</a></li>
	<li><a href="../cgi-bin/hgTracks?db=mm10&amp;position=lastDbPos">Mouse GRCm38/mm10</a></li>
	<li><a href="../cgi-bin/hgTracks?db=mm9&amp;position=lastDbPos">Mouse NCBI37/mm9</a></li>
	<li class="last"><a href="../cgi-bin/hgGateway">Other</a></li>
        </ul>
</li>

<li class="menuparent" id="tools2"><a href="../cgi-bin/hgTracks">Genome Browser</a>
	<ul style="display: none; visibility: hidden;">
	<li class="first"><a id="configureMenuLink" href="../cgi-bin/hgTracks?hgTracksConfigPage=configure">Configure</a></li>
	<li><a id="trackSearchMenuLink" href="../cgi-bin/hgTracks?hgt_tSearch=track+search">Track Search</a></li>
	<li><a id="cartResetMenuLink" href="../cgi-bin/cartReset">Reset All User Settings</a></li>
        </ul>
</li>


<li class="menuparent" id="tools3"><span>Tools</span>
	<ul style="display: none; visibility: hidden;">
	<li class="first"><a id="blatMenuLink" href="../cgi-bin/hgBlat?command=start">Blat</a></li>
	<li><a id="tableBrowserMenuLink" href="../cgi-bin/hgTables">Table Browser</a></li>
	<li><a id="vaiMenuLink" href="../cgi-bin/hgVai">Variant Annotation Integrator</a></li>
	<li><a id="diMenuLink" href="../cgi-bin/hgIntegrator">Data Integrator</a></li>
	<!-- <li><a title="Explore gene/protein interactions and pathways" id="interactionMenuLink" href="../cgi-bin/hgGeneGraph">Gene Interactions</a></li> -->
	<li><a id="gsMenuLink" href="../cgi-bin/hgNear">Gene Sorter</a></li>
	<li><a id="ggMenuLink" href="../cgi-bin/hgGenome">Genome Graphs</a></li>
	<li><a id="ispMenuLink" href="../cgi-bin/hgPcr">In-Silico PCR</a></li>
	<li><a id="liftOverMenuLink" href="../cgi-bin/hgLiftOver">LiftOver</a></li>
	<li><a id="visiGeneMenuLink" href="../cgi-bin/hgVisiGene">VisiGene</a></li>
	<li class="last"><a href="../util.html">Other Utilities</a></li>
	</ul>
</li>
<li class="menuparent" id="mirrors"><span>Mirrors</span>
	<ul style="display: none; visibility: hidden;">
	<li class="first"><a href="../mirror.html">Third Party Mirrors</a></li>
	<li><a href="../goldenPath/help/mirror.html">Mirroring Instructions</a></li>
	<!-- OPTIONAL_MIRROR_MENU -->
	</ul>

</li>
<li class="menuparent" id="downloads"><span>Downloads</span>
	<ul style="display: none; visibility: hidden;">
	<li class="first"><a href="http://hgdownload.soe.ucsc.edu/downloads.html">Genome Data</a></li>
	<li><a href="http://hgdownload.soe.ucsc.edu/downloads.html#source_downloads">Source Code</a></li>
  <li><a href="https://genome-store.ucsc.edu">Genome Browser Store</a></li>
	<li><a href="http://hgdownload.soe.ucsc.edu/downloads.html#utilities_downloads">Utilities</a></li>
	<li class="last"><a href="../goldenPath/help/ftp.html">FTP</a></li>
	<li class="last"><a href="../goldenPath/help/mysql.html">MySQL Access</a></li>
	</ul>
</li>
<li class="menuparent" id="myData"><span>My Data</span>
	<ul style="display: none; visibility: hidden;">
	<li><a id="sessionsMenuLink" href="../cgi-bin/hgSession?hgS_doMainPage=1">My Sessions</a></li>
	<li><a id="publicSessionsMenuLink" href="../cgi-bin/hgPublicSessions">Public Sessions</a></li>
	<li><a id="trackHubsMenuLink" href="../cgi-bin/hgHubConnect">Track Hubs</a></li>
	<li class="last"><a id="customTracksMenuLink" href="../cgi-bin/hgCustom">Custom Tracks</a></li>
	</ul>
</li>

<!-- OPTIONAL_VIEW_MENU -->

<li class="menuparent" id="help"><span>Help</span><ul style="display: none; visibility: hidden;">
<!-- CONTEXT_SPECIFIC_HELP -->
<li><a href="../FAQ/">FAQs & Search</a></li>
<li><a href="../goldenPath/help/hgTracksHelp.html">Browser Documentation</a></li>
<li><a href="../training/index.html">Training</a></li>
<li><a href="../contacts.html">Mailing Lists</a></li>
<li class="last"><a href="http://genomewiki.ucsc.edu/" target="_blank">GenomeWiki</a></li>
</ul>
</li>

<li class="menuparent last" id="aboutUs"><span>About Us</span>
	<ul style="display: none; visibility: hidden;">
	<li class="first odd"><a href="../goldenPath/newsarch.html">News</a></li>
	<li class="even"><a href="../goldenPath/pubs.html">Publications</a></li>
	<li class="even"><a href="http://genome.ucsc.edu/blog/">Blog</a></li>
	<li class="odd"><a href="../cite.html">Cite Us</a></li>
	<li class="even"><a href="../goldenPath/credits.html">Credits</a></li>
	<li class="odd"><a href="../goldenPath/releaseLog.html">Release Log</a></li>
	<li class="even"><a href="../staff.html">Staff</a></li>
	<li class="odd"><a href="../contacts.html">Contact Us</a></li>
	<li class="even"><a href="../conditions.html">Conditions of Use</a></li>
	<li class="odd"><a href="https://ucscgenomics.soe.ucsc.edu/careers/" TARGET="_blank">Jobs</a></li>
	<li class="even last"><a href="../license/">Licenses</a></li>
</ul>
</li>

</ul>
</div>
		</div>
	</div>
	<div class="downcorner"></div>

</div>
</div><!-- end main-menu -->
</div><!-- end main-menu-whole -->
