table lrSvHgsvc2
"HGSVC2 long-read structural variants (32 haplotype-resolved genomes)"
    (
    string chrom;              "Chromosome"
    uint chromStart;           "Start position"
    uint chromEnd;             "End position"
    string name;               "Variant ID"
    uint score;                "Score"
    char[1] strand;            "Strand"
    uint thickStart;           "Thick start (same as chromStart)"
    uint thickEnd;             "Thick end (same as chromEnd)"
    uint reserved;             "Item color"
    string svType;             "SV Type|DEL, INS, or INV"
    int svLen;                 "SV Length|Length of the variant on the reference in base pairs"
    int insLen;                "Insertion Length|Length of inserted sequence, 0 for DEL/INV/CPX"
    int AC;                    "Allele Count|MERGE_AC - carrier-haplotype count from the callerset merge"
    uint sampleCount;          "Sample Count|Distinct samples carrying the variant (ignoring haplotype suffix)"
    string cytoband;           "Cytoband (BAND)"
    float refSd;               "Segmental Duplication|Fraction of variant overlapping reference segmental duplications"
    string refTrf;             "In Tandem Repeat|Whether the variant falls in a Tandem Repeat Finder region (True/False)"
    uint refseqCds;            "RefSeq CDS Overlap|Base pairs overlapping CDS"
    uint refseqUtr3;           "RefSeq 3' UTR Overlap"
    uint refseqUtr5;           "RefSeq 5' UTR Overlap"
    uint refseqIntron;         "RefSeq Intron Overlap"
    uint refseqNcrna;          "RefSeq ncRNA Overlap"
    uint refseqUp5k;           "RefSeq +/- 5kb Upstream"
    uint refseqDn5k;           "RefSeq +/- 5kb Downstream"
    string pliMax;             "Max gnomAD pLI|Max pLI of genes overlapping this SV"
    string loeufMin;           "Min gnomAD LOEUF|Minimum LOEUF upper bound of overlapping genes"
    string popAllAf;           "Allele Frequency (all)|Population-level AF (insdel only)"
    string popAfrAf;           "AF African (insdel only)"
    string popAmrAf;           "AF Admixed American (insdel only)"
    string popEasAf;           "AF East Asian (insdel only)"
    string popEurAf;           "AF European (insdel only)"
    string popSasAf;           "AF South Asian (insdel only)"
    string regionRefInner;     "Inner Inversion Region|Inner coordinate range of the inversion (INV only)"
    lstring mergeSamples;      "Carrier Haplotypes|Comma-separated haplotype IDs carrying this variant"
    string discClass;          "Discovery Class|SV discovery class from the HGSVC2 pipeline"
    string win500;             "Flanking +/- 500 bp"
    string win2k;              "Flanking +/- 2000 bp"
    )
