table lrSvNoyvert
"Multi-ancestry long-read structural variants (888 samples, Noyvert et al. 2025)"
    (
    string chrom;              "Chromosome"
    uint chromStart;           "Start position"
    uint chromEnd;             "End position"
    string name;               "Variant name"
    uint score;                "Score"
    char[1] strand;            "Strand"
    uint thickStart;           "Thick start (same as chromStart)"
    uint thickEnd;             "Thick end (same as chromEnd)"
    uint reserved;             "Item color"
    string svType;             "SV Type|DEL, INS, INV, DUP or BND"
    int svLen;                 "SV Length|Length of the variant on the reference in base pairs"
    int insLen;                "Insertion Length|Length of inserted sequence, 0 for non-insertions"
    int AC;                    "Allele Count|Approximate alternate allele count (AF times allele number)"
    int AN;                    "Allele Number|Approximate called alleles, 2 x 888 x (1 - missing rate)"
    float AF;                  "Allele Frequency|Overall allele frequency across all samples"
    float afAfr;               "AF African|Allele frequency in African samples (n=241)"
    float afAmr;               "AF Admixed American|Allele frequency in Admixed American samples (n=144)"
    float afEas;               "AF East Asian|Allele frequency in East Asian samples (n=168)"
    float afEur;               "AF European|Allele frequency in European samples (n=164)"
    float afSas;               "AF South Asian|Allele frequency in South Asian samples (n=171)"
    string secondBp;           "Second Breakpoint|Mate breakend locus and orientation, BND records only"
    float stdevLen;            "Length StdDev|Sniffles2 standard deviation of SV length across samples"
    float stdevPos;            "Position StdDev|Sniffles2 standard deviation of the breakpoint position"
    float missingRate;         "Genotype Missing Rate|Fraction of samples with a missing genotype"
    string hwe;                "HWE p-values|Hardy-Weinberg exact test p-value per superpopulation"
    float r2Loo;               "Imputation r2 (LOO)|Leave-one-out internal imputation accuracy"
    float concordanceLoo;      "Minor Allele Concordance (LOO)|Leave-one-out minor-allele genotype concordance"
    float afUkb;               "AF in UK Biobank|Imputed allele frequency in the UK Biobank cohort"
    float r2Ukb;               "Imputation r2 (UKB)|Imputation accuracy in the UK Biobank cohort"
    int nGwas;                 "GWAS Hit Count|Number of significant UK Biobank SV-WAS trait associations"
    lstring ukbGwas;           "UK Biobank GWAS|Significant SV-WAS associations (trait: info, log10 p-value)"
    )
