table lrSv1kgOnt
"Long-read structural variants from 1000 Genomes ONT"
    (
    string chrom;       "Chromosome"
    uint chromStart;    "Start position"
    uint chromEnd;      "End position"
    string name;        "Variant ID"
    uint score;         "Score"
    char[1] strand;     "Strand"
    uint thickStart;    "Thick start (same as chromStart)"
    uint thickEnd;      "Thick end (same as chromEnd)"
    uint reserved;      "Item color"
    string svType;      "SV Type|INS, DEL, or CPX"
    int svLen;          "SV Length|Length of the structural variant on the reference in base pairs"
    int insLen;         "Insertion Length|Length of inserted sequence, 0 for DEL/INV/CPX"
    int AC;             "Allele Count|Number of alternate alleles across all samples (-1 if unknown)"
    string insType;     "Insertion/Deletion Type|solo, partnered, orphan, VNTR, PSD, NUMT, DUP, etc."
    string family;      "Transposon Family|Alu, L1, SVA, HERVK, LTR5_Hs, etc."
    float percResolved; "Percent Resolved|Percentage of inserted sequence resolved by SVAN"
    int tsdLen;         "TSD Length|Target site duplication length in base pairs"
    int polyaLen;       "Poly-A Length|Poly-A tail length in base pairs"
    string conformation; "Conformation|Structural conformation of the insertion"
    int rtLen;          "Retrotransposon Length|Length of the retrotransposon portion of the insert"
    int nbMotifs;       "VNTR Motif Count|Number of tandem repeat motifs within a VNTR"
    string srcGene;     "Source Gene|Gene from which a processed pseudogene was retrotransposed"
    int nbExons;        "Retrotransposed Exons|Number of exons retrotransposed (processed pseudogenes)"
    string notCanonical; "Non-canonical MEI|Yes if the mobile element insertion is non-canonical"
    int alleleNumber;   "Allele Number|Total number of alleles genotyped (-1 if unknown)"
    float alleleFreq;   "Allele Frequency|Alternate allele frequency across all samples (-1 if unknown)"
    )
