table lrSvChirmade101
"Chirmade 2026 (GWAS SVatalog) long-read structural variants"
    (
    string chrom;              "Chromosome"
    uint chromStart;           "Start position"
    uint chromEnd;             "End position"
    string name;               "Variant ID"
    uint score;                "Score"
    char[1] strand;            "Strand"
    uint thickStart;           "Thick start (same as chromStart)"
    uint thickEnd;             "Thick end (same as chromEnd)"
    uint reserved;             "Item color"
    string svType;             "SV Type|DEL, INS, DUP, INV, or CPX"
    int svLen;                 "SV Length|Length of the variant on the reference in base pairs"
    int insLen;                "Insertion Length|Length of inserted sequence, 0 for DEL/INV/CPX"
    int AC;                    "Allele Count|Placeholder value (-1); Chirmade catalog is site-level without AC"
    uint gcPct;                "GC Content|Percent GC in the SV region"
    string cytoband;           "Cytoband"
    uint geneCount;            "Gene Count|Number of genes overlapping the SV"
    lstring geneNames;         "Overlapping Genes|Comma-separated gene symbols"
    string geneAtStart;        "Gene at Start|Gene at the left breakpoint"
    string geneAtEnd;          "Gene at End|Gene at the right breakpoint"
    lstring exonName;          "Overlapping Exons"
    lstring cdsName;           "Overlapping CDS"
    string darkOverlap;        "Dark Genes Overlap|Percent overlap with 'dark' (low-mappability) genes"
    lstring clinGenHi;         "ClinGen Haploinsufficient|Haploinsufficiency score/evidence per gene"
    lstring clinGenTs;         "ClinGen Triplosensitive|Triplosensitivity score/evidence per gene"
    lstring gnomadLoefUpper;   "gnomAD LOEUF|Observed/expected LoF upper bound per gene"
    lstring gnomadMisUpper;    "gnomAD Mis O/E|Observed/expected missense upper bound per gene"
    lstring gnomadPli;         "gnomAD pLI|Per-gene pLI"
    lstring gnomadPrec;        "gnomAD pRec|Per-gene pRec"
    string repeatPct;          "Repeat Overlap|Percent overlap with repetitive regions"
    string dirtyPct;           "Dirty Region Overlap|Percent overlap with 'dirty' / low-quality regions"
    lstring chrRegion;         "Chromosome Region"
    lstring cgd;               "CGD|Clinical Genomic Database gene annotation"
    lstring omimPheno;         "OMIM Phenotype"
    lstring omimInh;           "OMIM Inheritance"
    lstring clinGenRegion;     "ClinGen Region"
    lstring decipherRegion;    "Decipher Region"
    lstring clinvarVarId;      "ClinVar Variant ID"
    string gnomadAfMax;        "gnomAD AF Max (90% RO)|Max allele frequency across gnomAD populations for overlapping SV"
    string gnomadPopAfMax;     "gnomAD Population AF Max"
    string gnomadHomRefFreq;   "gnomAD Hom/Ref Freq"
    string gnomadHetFreq;      "gnomAD Het Freq"
    string gnomadHomAltFreq;   "gnomAD Hom/Alt Freq"
    string dgvPct;             "DGV Overlap|Percent overlap with Database of Genomic Variants"
    string dgv50ro;            "DGV 50% RO|Matched DGV variant at >=50% reciprocal overlap"
    )
