table lrSvAou1k
"All of Us long-read structural variants"
    (
    string chrom;           "Chromosome"
    uint chromStart;        "Start position"
    uint chromEnd;          "End position"
    string name;            "Variant Name"
    uint score;             "Score"
    char[1] strand;         "Strand"
    uint thickStart;        "Thick start (same as chromStart)"
    uint thickEnd;          "Thick end (same as chromEnd)"
    uint reserved;          "Item color"
    string svType;          "SV Type|DEL or INS"
    int svLen;              "SV Length|Length of the structural variant in base pairs"
    float afAfr;            "AF African|Allele frequency in African/African American samples"
    float afAmr;            "AF Admixed American|Allele frequency in Admixed American samples"
    float afEas;            "AF East Asian|Allele frequency in East Asian samples"
    float afEur;            "AF European|Allele frequency in European samples"
    float afSas;            "AF South Asian|Allele frequency in South Asian samples"
    string fst;             "Fst (AFR vs Non-AFR)|Fixation index between African and non-African populations"
    lstring omimGenes;      "OMIM Genes|OMIM genes intersected with pLI and LOEUF scores"
    lstring diseaseGenes;   "Disease Genes|Disease genes intersected with pLI and LOEUF scores"
    lstring cancerGenes;    "Cancer Genes|Cancer genes intersected with pLI and LOEUF scores"
    lstring acmgGenes;      "ACMG Genes|ACMG genes intersected with pLI and LOEUF scores"
    string regElement;      "Regulatory Element|Type of regulatory element intersected (e.g. enhancer, promoter)"
    string segDup;          "SegDup|Segmental duplication association (INS: within 1kb, DEL: intersect)"
    string tandemRepeat;    "Tandem Repeat|Tandem repeat intersected"
    string otherLrDatasets; "Other LR Datasets|Detected in other long-read datasets (HPRC, HGSVC, 1KG-ONT)"
    string detectedInSr;    "Detected in SR|Detected in matched AoU short-read data"
    lstring eqtls;          "eQTLs|eQTL associations: gene(qvalue)"
    lstring gwas;           "GWAS Associations|GWAS associations: trait(gene, rsID, pvalue, LD_r2)"
    lstring traitAssoc;     "SV-Trait Associations|SV-trait associations in AoU Phase I (Carrier%, Non-carrier%, OR, 95% CI, pvalue)"
    )
