table lrSv
"Long-read structural variants"
    (
    string chrom;       "Chromosome"
    uint chromStart;    "Start position"
    uint chromEnd;      "End position"
    string name;        "Variant ID"
    uint score;         "Score (quality)"
    char[1] strand;     "Strand"
    uint thickStart;    "Thick start (same as chromStart)"
    uint thickEnd;      "Thick end (same as chromEnd)"
    uint reserved;      "Item color"
    string svType;      "SV Type|DEL, INS, DUP, INV, or TRA"
    int svLen;          "SV Length|Length of the structural variant in base pairs (absolute value)"
    float alleleFreq;   "Allele Frequency|Fraction of samples carrying this variant"
    uint sampleCount;   "Sample Count|Number of samples supporting this variant"
    string ciPos;       "CI around Start|Confidence interval around start position"
    string ciEnd;       "CI around End|Confidence interval around end position"
    string chr2;        "Second Chromosome|Chromosome of second breakpoint (TRA only)"
    string end2;        "Second Position|Position of second breakpoint (TRA only)"
    lstring sampleList; "Supporting Samples|Comma-separated 1-based indices of supporting samples"
    )
