table lrSvColorsDbSv
"CoLoRSdb structural variants (pbsv + Jasmine, site-only)"
    (
    string chrom;        "Chromosome"
    uint   chromStart;   "Start position"
    uint   chromEnd;     "End position"
    string name;         "Canonical SV name: TYPE-LEN[:AC]"
    uint   score;        "Score 0-1000 (AF scaled)"
    char[1] strand;      "Strand (.)"
    uint   thickStart;   "Thick start"
    uint   thickEnd;     "Thick end"
    uint   itemRgb;      "Color by SV type"
    string svType;       "SV Type|DEL, INS, INV or DUP"
    int    svLen;        "SV Length on reference|chromEnd-chromStart"
    int    insLen;       "Insertion Length|Length of inserted sequence, 0 for DEL/INV/DUP"
    int    AC;           "Allele Count (AC)|alternate allele count across called genotypes"
    int    AN;           "Allele Number (AN)|total called alleles"
    int    NS;           "Number of samples with data (NS)"
    int    acHom;        "AC Hom|alt-allele count in homozygous genotypes"
    int    acHet;        "AC Het|alt-allele count in heterozygous genotypes"
    int    acHemi;       "AC Hemi|alt-allele count in hemizygous genotypes"
    int    nhomalt;      "nhomalt|number of individuals homozygous for the alt allele"
    float  AF;           "Allele Frequency (AF)|AC/AN"
    float  HWE;          "HWE|Hardy-Weinberg equilibrium test p-value (1=good, 0=bad)"
    float  ExcHet;       "ExcHet|excess-heterozygosity test p-value (1=good, 0=bad)"
    lstring ref;         "REF allele|reference sequence at the variant site"
    lstring alt;         "ALT allele|alternate sequence (or symbolic <INV>/<DUP>)"
    )
