table lrSvCard
"NIH CARD long-read structural variants (351 brain samples: 205 NABEC, 146 HBCC)"
    (
    string chrom;           "Chromosome"
    uint chromStart;        "Start position"
    uint chromEnd;          "End position"
    string name;            "Variant ID"
    uint score;             "Score"
    char[1] strand;         "Strand"
    uint thickStart;        "Thick start (same as chromStart)"
    uint thickEnd;          "Thick end (same as chromEnd)"
    uint reserved;          "Item color"
    string svType;          "SV Type|DEL, INS, INV or DUP"
    int svLen;              "SV Length|Length of the variant on the reference in base pairs"
    int insLen;             "Insertion Length|Length of inserted sequence, 0 for DEL/INV/DUP"
    int AC;                 "Allele Count|Number of samples carrying this variant (genotyped carrier count)"
    float alleleFreq;       "Allele Frequency|Fraction of samples carrying this variant (source VCF AF)"
    uint nabecCount;        "NABEC Carriers|Carrier samples of European ancestry (NABEC cohort)"
    uint hbccCount;         "HBCC Carriers|Carrier samples of African/African-admixed ancestry (HBCC cohort)"
    )
