table lrSvHgsvc3
"HGSVC3 long-read structural variants (65 samples)"
    (
    string chrom;            "Chromosome"
    uint chromStart;         "Start position"
    uint chromEnd;           "End position"
    string name;             "Variant ID"
    uint score;              "Score"
    char[1] strand;          "Strand"
    uint thickStart;         "Thick start (same as chromStart)"
    uint thickEnd;           "Thick end (same as chromEnd)"
    uint reserved;           "Item color"
    string svType;           "SV Type|DEL, INS, or INV"
    int svLen;               "SV Length|Length of the variant on the reference in base pairs"
    int insLen;              "Insertion Length|Length of inserted sequence, 0 for DEL/INV/CPX"
    int AC;                  "Allele Count|Number of haplotypes carrying the variant across 65 diploid samples"
    uint sampleCount;        "Sample Count|Number of distinct samples carrying the variant (ignoring haplotype suffix)"
    string homRef;           "Reference Homology|Homology (bp) at breakpoints in the reference (5',3'), insdel only"
    string homTig;           "Contig Homology|Homology (bp) at breakpoints in the assembly contig (5',3'), insdel only"
    string regionRefInner;   "Inversion Inner Region|Inner coordinate range of the inversion, INV only"
    string te;               "Transposable Element|TE class of the inserted/deleted sequence, insdel only"
    string refTrf;           "In Tandem Repeat|Variant falls in a reference Tandem Repeat Finder region (True/False)"
    float refSd;             "Segmental Duplication Overlap|Fraction of the variant overlapping reference segmental duplications (0-1)"
    lstring mergeSamples;    "Carrier Haplotypes|Comma-separated list of haplotype IDs carrying this variant"
    string win500;           "Flanking +/- 500 bp|Genomic window around the variant"
    string win2k;            "Flanking +/- 2000 bp|Genomic window around the variant"
    )
