table lrSvKwanho
"Kim 2026 Parkinson's disease brain long-read structural variants"
    (
    string chrom;               "Chromosome"
    uint chromStart;            "Start position"
    uint chromEnd;              "End position"
    string name;                "Variant ID"
    uint score;                 "Score"
    char[1] strand;             "Strand"
    uint thickStart;            "Thick start (same as chromStart)"
    uint thickEnd;              "Thick end (same as chromEnd)"
    uint reserved;              "Item color"
    string svType;              "SV Type|DEL, INS, DUP or INV"
    int svLen;                  "SV Length|Length of the variant on the reference in base pairs"
    int insLen;                 "Insertion Length|Length of inserted sequence, 0 for DEL/INV/CPX"
    int AC;                     "Allele Count|Total AC across PD+HC+ILBD cohorts"
    string sizeBin;             "Size Bin|Length category used in the paper (e.g. [50,100))"
    uint qual;                  "Quality|Variant quality score from the joint callset"
    uint supp;                  "Caller Support|Number of SV callers supporting this variant"
    string suppVec;             "Cohort Support Vector|Bitmask indicating which cohorts carry the variant (PD/ILBD/HC)"
    float missingRate;          "Missing-genotype Rate|Fraction of samples with missing genotype at this site"
    float caseRate;             "Case Carrier Rate|Fraction of PD+ILBD cases carrying the variant"
    float controlRate;          "Control Carrier Rate|Fraction of HC controls carrying the variant"
    float differentialRate;     "Case-Control Differential|caseRate - controlRate (negative: enriched in controls)"
    float afPd;                 "Allele Frequency (PD)|Alternate allele frequency in Parkinson's disease samples"
    float afHc;                 "Allele Frequency (HC)|Alternate allele frequency in healthy-control samples"
    float afIlbd;               "Allele Frequency (ILBD)|Alternate allele frequency in incidental Lewy body disease samples"
    uint acPd;                  "Allele Count (PD)|Alternate allele count in PD samples"
    uint acHc;                  "Allele Count (HC)|Alternate allele count in HC samples"
    uint acIlbd;                "Allele Count (ILBD)|Alternate allele count in ILBD samples"
    uint anPd;                  "Allele Number (PD)|Total called alleles in PD samples"
    uint anHc;                  "Allele Number (HC)|Total called alleles in HC samples"
    uint anIlbd;                "Allele Number (ILBD)|Total called alleles in ILBD samples"
    uint nCarriersPd;           "Carrier Count (PD)"
    uint nCarriersHc;           "Carrier Count (HC)"
    uint nCarriersIlbd;         "Carrier Count (ILBD)"
    uint ldSnpsCount;           "LD SNPs|Number of nearby SNPs in linkage disequilibrium with this SV"
    uint totalSnpsNearby;       "Nearby SNPs|Total number of SNPs in the surrounding window"
    float avgMapQuality;        "Avg Mapping Quality|Average read mapping quality at the SV"
    float avgReadsPerSample;    "Avg Reads / Sample|Average supporting reads per sample"
    lstring pdCarriers;         "PD Carriers|Sample IDs of PD carriers"
    lstring hcCarriers;         "HC Carriers|Sample IDs of HC carriers"
    lstring ilbdCarriers;       "ILBD Carriers|Sample IDs of ILBD carriers"
    )
