table lrSv1kLin1218
"1000 Genomes linear long-read structural variants (1,218 samples)"
    (
    string chrom;              "Chromosome"
    uint chromStart;           "Start position"
    uint chromEnd;             "End position"
    string name;               "Variant name"
    uint score;                "Score"
    char[1] strand;            "Strand"
    uint thickStart;           "Thick start (same as chromStart)"
    uint thickEnd;             "Thick end (same as chromEnd)"
    uint reserved;             "Item color"
    string svType;             "SV Type|DEL or INS"
    int svLen;                 "SV Length|Length of the variant on the reference in base pairs"
    int insLen;                "Insertion Length|Length of inserted sequence, 0 for DEL"
    int AC;                    "Allele Count|Number of alternate alleles observed"
    int AN;                    "Allele Number|Total number of alleles in called genotypes"
    float AF;                  "Allele Frequency|Overall allele frequency across all samples"
    float afAfr;               "AF African|Allele frequency in African samples"
    float afAmr;               "AF Admixed American|Allele frequency in Admixed American samples"
    float afEas;               "AF East Asian|Allele frequency in East Asian samples"
    float afEur;               "AF European|Allele frequency in European samples"
    float afSas;               "AF South Asian|Allele frequency in South Asian samples"
    int NS;                    "Sample Count|Number of samples with genotype data"
    int numConsolidated;       "Consolidated Samples|Number of samples consolidated into this call by Truvari"
    )
