table lrSvHprc2
"HPRC release-2 pangenome structural variants (233 samples, wave-decomposed)"
    (
    string chrom;           "Chromosome"
    uint chromStart;        "Start position"
    uint chromEnd;          "End position"
    string name;            "Variant ID"
    uint score;             "Score"
    char[1] strand;         "Strand"
    uint thickStart;        "Thick start (same as chromStart)"
    uint thickEnd;          "Thick end (same as chromEnd)"
    uint reserved;          "Item color"
    string svType;          "SV Type|INS, DEL, COMPLEX or INV"
    int svLen;              "SV Length|Absolute length of the SV in base pairs"
    uint alleleCount;       "Allele Count (AC)"
    uint alleleNumber;      "Allele Number (AN)"
    float alleleFreq;       "Allele Frequency (AF)"
    uint nSamples;          "Samples with Data (NS)"
    uint snarlLevel;        "Snarl Level|Nesting level in the pangenome snarl decomposition tree (0 = top level)"
    )
