kentSrc = ../../../..
include ../../../../inc/common.mk

JS_DIR=../..
JS_FILES= ImModel.js cart.js CladeOrgDbMixin.js PositionSearchMixin.js UserRegionsMixin.js

include ${JS_DIR}/install.mk
include ${JS_DIR}/simple.mk
