/* gencodeUniProt.h was originally generated by the autoSql program, which also 
 * generated gencodeUniProt.c and gencodeUniProt.sql.  This header links the database and
 * the RAM representation of objects. */

#ifndef GENCODEUNIPROT_H
#define GENCODEUNIPROT_H

#define GENCODEUNIPROT_NUM_COLS 4

extern char *gencodeUniProtCommaSepFieldNames;

enum gencodeUniProtDataset
    {
    gencodeUniProtSwissProt = 0,
    gencodeUniProtTrEMBL = 1,
    };
struct gencodeUniProt
/* GENCODE transcript to UniProt peptide mapping */
    {
    struct gencodeUniProt *next;  /* Next in singly linked list. */
    char *transcriptId;	/* GENCODE transcript identifier */
    char *acc;	/* UniProt/Swiss-Prot accession */
    char *name;	/* UniProt/Swiss-Prot entry name */
    enum gencodeUniProtDataset dataset;	/* UniProt dataset */
    };

void gencodeUniProtStaticLoad(char **row, struct gencodeUniProt *ret);
/* Load a row from gencodeUniProt table into ret.  The contents of ret will
 * be replaced at the next call to this function. */

struct gencodeUniProt *gencodeUniProtLoad(char **row);
/* Load a gencodeUniProt from row fetched with select * from gencodeUniProt
 * from database.  Dispose of this with gencodeUniProtFree(). */

struct gencodeUniProt *gencodeUniProtLoadAll(char *fileName);
/* Load all gencodeUniProt from whitespace-separated file.
 * Dispose of this with gencodeUniProtFreeList(). */

struct gencodeUniProt *gencodeUniProtLoadAllByChar(char *fileName, char chopper);
/* Load all gencodeUniProt from chopper separated file.
 * Dispose of this with gencodeUniProtFreeList(). */

#define gencodeUniProtLoadAllByTab(a) gencodeUniProtLoadAllByChar(a, '\t');
/* Load all gencodeUniProt from tab separated file.
 * Dispose of this with gencodeUniProtFreeList(). */

struct gencodeUniProt *gencodeUniProtCommaIn(char **pS, struct gencodeUniProt *ret);
/* Create a gencodeUniProt out of a comma separated string. 
 * This will fill in ret if non-null, otherwise will
 * return a new gencodeUniProt */

void gencodeUniProtFree(struct gencodeUniProt **pEl);
/* Free a single dynamically allocated gencodeUniProt such as created
 * with gencodeUniProtLoad(). */

void gencodeUniProtFreeList(struct gencodeUniProt **pList);
/* Free a list of dynamically allocated gencodeUniProt's */

void gencodeUniProtOutput(struct gencodeUniProt *el, FILE *f, char sep, char lastSep);
/* Print out gencodeUniProt.  Separate fields with sep. Follow last field with lastSep. */

#define gencodeUniProtTabOut(el,f) gencodeUniProtOutput(el,f,'\t','\n');
/* Print out gencodeUniProt as a line in a tab-separated file. */

#define gencodeUniProtCommaOut(el,f) gencodeUniProtOutput(el,f,',',',');
/* Print out gencodeUniProt as a comma separated list including final comma. */

/* -------------------------------- End autoSql Generated Code -------------------------------- */

#endif /* GENCODEUNIPROT_H */

