/* trackDb.h was originally generated by the autoSql program, which also
 * generated trackDb.c and trackDb.sql.  This header links the database and
 * the RAM representation of objects. */

#ifndef SEARCHTRACKS_H
#define SEARCHTRACKS_H

#include "common.h"

#define searchTracks "hgt_searchTracks"

void getSearchTrixFile(char *database, char *buf, int len);
// Fill-in the name of the track search trix file

boolean isSearchTracksSupported(char *database);
// Return TRUE if searchTracks is supported for this database

#endif /* SEARCHTRACKS_H */
