table clinvarMappedPfam
"ClinVar variants projected onto other genes sharing the same Pfam domain, at the equivalent domain position"
    (
    string chrom;         "Reference sequence chromosome"
    uint   chromStart;    "Start position of the equivalent codon in this gene"
    uint   chromEnd;      "End position of the equivalent codon in this gene"
    string name;          "Source gene and variant"
    uint   score;         "Review status scaled 0-1000 (stars x 250)"
    char[1] strand;       "Strand of this gene"
    uint   thickStart;    "Coding start (equal to chromStart)"
    uint   thickEnd;      "Coding end (equal to chromEnd)"
    uint   reserved;      "Color (itemRgb) by clinical significance of the source variant"
    int    blockCount;    "Number of codon blocks (2 if the codon spans an intron)"
    int[blockCount] blockSizes;  "Codon block sizes"
    int[blockCount] chromStarts; "Codon block starts relative to chromStart"
    string sourceGene;    "Source gene|Gene the ClinVar variant is annotated in"
    string thisGene;      "This gene|Gene carrying the equivalent domain position"
    string sourceVariant; "Source variant|ClinVar protein change in the source gene"
    uint   sourceAaPos;   "Source residue #|Residue position in the source gene"
    char[1] srcRes;       "Source residue|Reference residue in the source gene"
    char[1] thisRes;      "This-gene residue|Residue at the equivalent domain position"
    string residueMatch;  "Residue match|identical, similar or different vs the source residue"
    string clinSign;      "Clinical significance|ClinVar significance of the source variant"
    string clinSignCode;  "Significance code"
    uint   reviewStars;   "Review stars|ClinVar review status, 0-4 stars"
    string molConseq;     "Consequence|Molecular consequence in the source gene"
    string pfamId;        "Pfam domain|Pfam domain name"
    string pfamAcc;       "Pfam accession|Pfam family accession"
    uint   domainColumn;  "Domain position|Pfam HMM match-state column (shared coordinate)"
    string vcvId;         "ClinVar VCV|ClinVar variant accession"
    string sourceLocus;   "Source position|Position of the source variant on hg38"
    )
