table clinvarMappedPfamAln
"Pfam domain instances on MANE Select genes (evidence for the Pfam variant projection)"
    (
    string chrom;         "Reference sequence chromosome"
    uint   chromStart;    "Domain footprint start"
    uint   chromEnd;      "Domain footprint end"
    string name;          "Pfam domain name"
    uint   score;         "Domain bit score scaled 0-1000"
    char[1] strand;       "Gene strand"
    uint   thickStart;    "Coding start (equal to chromStart)"
    uint   thickEnd;      "Coding end (equal to chromEnd)"
    uint   reserved;      "Display color"
    int    blockCount;    "Number of exon blocks the domain spans"
    int[blockCount] blockSizes;  "Block sizes"
    int[blockCount] chromStarts; "Block starts relative to chromStart"
    string gene;          "Gene|Gene symbol"
    string pfamId;        "Pfam domain|Pfam domain name"
    string pfamAcc;       "Pfam accession|Pfam family accession"
    uint   aaStart;       "Protein start|First residue of the domain in the protein"
    uint   aaEnd;         "Protein end|Last residue of the domain in the protein"
    uint   hmmStart;      "Domain column start|First HMM match-state column covered"
    uint   hmmEnd;        "Domain column end|Last HMM match-state column covered"
    string iEval;         "i-E-value|Independent E-value of the domain hit"
    )
