#!/bin/bash

echo "Content-type: text/html"
echo ""

echo '<html>'
echo '<head>'
echo '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">'
echo '<title>no gene sorter here</title>'
echo "<LINK rel='STYLESHEET' href='../style/HGStyle.css' TYPE='text/css' />"
echo '</head>'
echo '<body>'
echo 'Sorry, the Gene Sorter is not supported in Genome Browser in a Box.<p>'
echo 'You can use the Gene Sorter at the main <a href="http://genome.ucsc.edu/cgi-bin/hgNear">UCSC website</a> instead.'
echo '</body>'
echo '</html>'

exit 0
        
