# Generated by Django 2.1 on 2019-08-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcat', '0013_auto_20190829_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='body_part',
            new_name='organ_part',
        ),
        migrations.AddField(
            model_name='project',
            name='organ',
            field=models.ManyToManyField(blank=True, to='hcat.Organ'),
        ),
    ]
