// goes in head tag, e.g. cdwGetFile html format
"                <meta charset='windows-1252'>\n"
"                <meta http-equiv='X-UA-Compatible' content='IE=edge'>\n"
"                <meta name='viewport' content='width=device-width, initial-scale=1'>\n"
"                <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\n"
"\n"
"                <link rel='shortcut icon' href='/images/schub.ico' type='image/png' />\n"
"                <script src='https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js'></script>\n"
"                <link rel='stylesheet' href='/style/cirmStyle.css?v=1548362966' type='text/css'>\n"
"                <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.2/css/all.css'\n"
"                 integrity='sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr'\n"
"                 crossorigin='anonymous'>\n"
"\n"
"                <!-- Latest compiled and minified CSS -->\n"
"                <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'\n"
"                 integrity='sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm'\n"
"                 crossorigin='anonymous'>\n"
"\n"
"                <!-- Latest compiled and minified JavaScript -->\n"
"                <script src='https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js'\n"
"                  integrity='sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q'\n"
"                 crossorigin='anonymous'></script>\n"
"                <script src='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js'\n"
"                 integrity='sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl'\n"
"                 crossorigin='anonymous'></script>\n"
"\n"
"                <noscript><div class='noscript'><div class='noscript-inner'><p><b>JavaScript is disabled in your web browser</b></p><p>You must have JavaScript enabled in your web browser to use the Genome Browser</p></div></div></noscript>\n"
"                <script type='text/javascript' SRC='/js/jquery.watermark.js?v=1494635946'></script>\n"
"                <script type='text/javascript' SRC='/js/d3pie.min.js?v=1494635946'></script>\n"
"                <script type='text/javascript' SRC='/js/dagre-d3.js?v=1503705097'></script>\n"
"                <script src='//cdnjs.cloudflare.com/ajax/libs/d3/3.4.4/d3.min.js'></script>\n"
