"<div id=\"main-menu-whole\">\n"
"    <div id=\"main-menu\"><div id=\"block-nice_menus-1\" class=\"clear-block block block-nice_menus\">\n"
"	<div class=\"upcorner\"></div>\n"
"	<div class=\"blockbg\">\n"
"	<div class=\"blockcontent\">\n"
"	<div class=\"content\">\n"
"\n"
"<ul class=\"nice-menu nice-menu-down sf-js-enabled\" id=\"nice-menu-1\">\n"
"\n"
"<li class=\"first even\" id=\"home\"><a href=\"../cgi-bin/cdwWebBrowse\" ><span id=\"home-link\">Home</span></a></li> \n"
"\n"
"<li class=\"menuparent\" id=\"browse\"><span>Browse</span>\n"
"	<ul style=\"display: none; visibility: hidden;\">\n"
"	<li class=\"first\"><a href=\"../cgi-bin/cdwWebBrowse?cdwCommand=browseFiles&cdwFile_filter=\">Files</a></li>\n"
"	<li><a href=\"../cgi-bin/cdwWebBrowse?cdwCommand=browseTracks\">Tracks</a></li>\n"
"	<li><a href=\"../cgi-bin/cdwWebBrowse?cdwCommand=browseLabs\">Labs</a></li>\n"
"	<li><a href=\"../cgi-bin/cdwWebBrowse?cdwCommand=browseDataSets\">Data Sets</a></li>\n"
"	<li><a href=\"../cgi-bin/cdwWebBrowse?cdwCommand=browseFormats\">Formats</a></li>\n"
"	</ul>\n"
"</li>\n"
"<li class=\"menuparent\" id=\"analysis\"><span>Analysis</span>\n"
"	<ul style=\"display: none;\">\n"
"	<li class=\"first\"><a href=\"../cgi-bin/cdwWebBrowse?cdwCommand=analysisQuery\">Query</a></li>\n"
"	<li><a href=\"../cgi-bin/cdwWebBrowse?cdwCommand=analysisJointPages\">Joint Data Sets</a></li>\n"
"	</ul>\n"
"</li> 	\n"
"<li id=\"help\"><a href=\"../cgi-bin/cdwWebBrowse?cdwCommand=help\">Help</a></li>\n"
"%s\n"
"</li>\n"
"\n"
"</ul>\n"
"</div>\n"
"		</div>\n"
"	</div>\n"
"	<div class=\"downcorner\"></div>\n"
"\n"
"</div>\n"
"</div><!-- end main-menu -->\n"
"</div><!-- end main-menu-whole -->\n"
"\n"
