//  this should correspond to src/hg/cirm/gateway/htdocs/inc/footer.html SSI
"<div class='footer' style='border-radius: 10px'>\n"
  "<div class='container' style='padding-top: 15px'>\n"
    "<div class='row'>\n"
      "<div class='col'>\n"
      "<p class='text-muted'>\n"
      "<a href='../sspsygene.html'>Home</a><br />\n"
      "<a href='https://www.ucsc.edu/' target='_blank'>UCSC Home <i\n"
      "class='fas fa-external-link-alt' aria-hidden='true'></i></a><br />\n"
      "<a href='https://www.nimh.nih.gov/' target='_blank'>NIMH Home <i\n"
      "class='fas fa-external-link-alt' aria-hidden='true'></i></a><br />\n"
    "</div>\n"
    "<div class='col'>\n"
      "<p class='text-muted'>\n"
      "<a href='https://docs.google.com/spreadsheets/d/1bHH1rKILTXGyWaOxb6RnaaNbRlAzqa_tahEo4sYrFxE/edit?gid=0#gid=0' target='_blank'>SSPsyGene Gene Spreadsheet <i\n"
      "class='fas fa-external-link-alt' aria-hidden='true'></i></a><br />\n"
      "<a href='https://drive.google.com/drive/folders/1nr5A3MMogKKNrl0TEeNNdiOD3U50Licd?usp=drive_link' target='_blank'>Shared SSPsyGene Folder<i\n"
      "class='fas fa-external-link-alt' aria-hidden='true'></i></a><br />\n"
      "<a  href='../sspsygeneTimeline.html' target='_blank'>SSPsyGene Timelines</a><br />\n"
      "</p>\n"
    "</div>\n"

    "<div class='col-sm'>\n"
      "<div class='row'>\n"
        "<p class='text-muted'>\n"
        "<a href='https://sspsygene.ucsc.edu/resources/'\n"
        "target='_blank'>SSPsyGene Public Resources Page\n"
        "<i class='fas fa-external-link-alt' aria-hidden='true'></i></a><br />\n"
        "</p>\n"
        "<p class='centered-text col-md-12'>\n"
        "<a href='https://www.facebook.com/nimhgov'\n"
        "target='_blank'><i class='fab fa-facebook-square fa-2x'></i></a>\n"
        "&nbsp;&nbsp;<a href='https://www.instagram.com/nimhgov/'\n"
        "target='_blank'><i class='fab fa-instagram fa-2x'></i></a>\n"
        "&nbsp;&nbsp;<a href='http://www.twitter.com/nomhgov' target='_blank'><i\n"
        "class='fab fa-twitter-square fa-2x'></i></a>\n"
      "</div>\n"
    "</div>\n"
  "</div>\n"
"</div>\n"
