"<div class=\"row\"><div class=\"col-12\"><div class='securesite-banner' style='display:none'>\n"
"<div class=\"securesite-text\">\n"
"This is the secure site for labs to access pre-publication data.  Public CIRM CESCG data\n"
"may be accessed at <a class='securesite' href='https://cirm.ucsc.edu'>https://cirm.ucsc.edu</a>.\n"
"</div></div></div></div>\n"
"<div class='cirm-banner'></div>\n"
"<div class=\"container-fluid\" style=\"width: 90%%\">\n"
"  <div class=\"row\">\n"
"    <a href=\"../index\"><img src=\"../images/cirmSChubLogo.png\" class=\"img-responsive\"\n"
"    style=\"margin-top: 15px; max-width: 450px;\"/></a>\n"
"  </div>\n"
"  <div style=\"margin-left:-15px; margin-right:-15px\">\n"
"    <div id=\"siteSearchBox\" class=\"float-right\">\n"
"      <form action=\"https://google.com/search\" method=\"get\">\n"
"        <input type=\"hidden\" name=\"sitesearch\" value=\"cirm.ucsc.edu\" />\n"
"        <input type=\"text\" name=\"q\" class=\"form-control\" placeholder=\"press enter to search site\" />\n"
"      </form>\n"
"    </div>\n"
"    <h5 style=\"margin-bottom: 0px\">\n"
"      <div style=\"line-height: 1.5em\">\n"
"        <a class=\"a-unstyled\" href=\"../cgi-bin/cdwWebBrowse?cdwCommand=browseFiles\">\n"
"        <span class=\"label back-dark-pink\">Files</span></a>\n"
"        <a class=\"a-unstyled\" href=\"../projects\">\n"
"        <span class=\"label back-light-blue\">Projects</span></a>\n"
"        <a class=\"a-unstyled\" href=\"../tools\">\n"
"        <span class=\"label back-light-green\">Tools</span></a>\n"
"        <a class=\"a-unstyled\" href=\"../cescg/cescgOrg\">\n"
"        <span class=\"label back-orange\">CESCG Organization</span></a>\n"
"        <a class=\"a-unstyled\" href=\"../cescg/cescgPeople\">\n"
"        <span class=\"label back-dark-blue\">CESCG People</span></a>\n"
"        <a class=\"a-unstyled\" href=\"../cescg/cescgPubs\">\n"
"        <span class=\"label back-dark-pink\">CESCG Publications</span></a>\n"
"        <a class=\"a-unstyled\" href=\"../help/cirmBasics\">\n"
"        <span class=\"label back-light-blue\">Help</span></a>\n"
"        <a class=\"a-unstyled\" href=\"../bestPractices\">\n"
"        <span class=\"label back-light-green\">Best Practices</span></a>\n"
"        <a class=\"a-unstyled login\" href=\"../cgi-bin/hgLogin?hgLogin.do.displayLoginPage=1\">\n"
"        <span class=\"label back-gray\">Login</span></a>\n"
"        <a class=\"a-unstyled login\" href=\"../cgi-bin/hgLogin?hgLogin.do.displayLogout=1\" style=\"display:none\">\n"
"        <span class=\"label back-gray\" id=\"logoutLink\">Logout</span></a>\n"
"      </div>\n"
"    </h5>\n"
"  </div>\n"
"</div>\n"
"<script src='//cdnjs.cloudflare.com/ajax/libs/bowser/1.6.1/bowser.min.js'></script>\n"
"<script src=\"../js/cirmStuff.js\"></script>\n"
