//  this should correspond to src/hg/cirm/gateway/htdocs/inc/footer.html SSI
"<div class='footer' style='border-radius: 10px'>\n"
"<hr>\n"
"<div class='container'>\n"
    "<div class='row'>\n"
    "<div class='col'>\n"
        "<p class='text-muted'>\n"
            "<a href='/'>Home</a><br />\n"
            "<a href='https://www.ucsc.edu/'>UCSC Home <i\n"
                 "class='fa fa-external-link' aria-hidden='true'></i></a><br />\n"
            "<a href='https://www.cirm.ca.gov/'>CIRM Home <i\n"
                 "class='fa fa-external-link' aria-hidden='true'></i></a><br />\n"
    "</div>\n"
    "<div class='col'>\n"
            "<p class='text-muted'>\n"
                "<a href='/help/cirmBasics'>Stem Cell Hub Help</a><br />\n"
                "<a href='CESCG_SequencingInformaticsCosts-102914.pdf'>CESCG Services <i\n"
                "class='fa fa-file-pdf-o' aria-hidden='true'></i></a><br />\n"
                "<a href='https://www.cirm.ca.gov/about-cirm/contact-us' target='_blank'>CIRM Contact <i\n"
                 "class='fa fa-external-link' aria-hidden='true'></i></a><br />\n"
                "<a href='/help/cirmBasics#contact'>Stem Cell Hub Contact</a><br />\n"
            "</p>\n"
    "</div>\n"

    "<div class='col-sm'>\n"
        "<div class='row'>\n"
            "<p class='centered-text col-md-12'>\n"
                "<a href='https://www.facebook.com/CaliforniaInstituteForRegenerativeMedicine'\n"
                 "target='_blank'><i class='fa fa-facebook-square fa-2x'></i></a>\n"
                "&nbsp;&nbsp;<a href='https://www.instagram.com/cirm_stemcells/'\n"
                 "target='_blank'><i class='fa fa-instagram fa-2x'></i></a>\n"
                "&nbsp;&nbsp;<a href='http://www.twitter.com/CIRMnews' target='_blank'><i\n"
                 "class='fa fa-twitter-square fa-2x'></i></a>\n"
                "&nbsp;&nbsp;<a href='https://www.youtube.com/user/CIRMTV' target='_blank'><i\n"
                 "class='fa fa-youtube fa-2x'></i></a>\n"
        "</div>\n"
        "<div class='row'>\n"
            "<p class='centered-text col-md-12'>\n"
                "<a href='https://plus.google.com/u/0/112512721505484176043/posts'\n"
                 "target='_blank'><i class='fa fa-google-plus-square fa-2x'></i></a>\n"
                "&nbsp;&nbsp;<a href='https://www.linkedin.com/groups?gid=4017737&trk=myg_ugrp_ovr'\n"
                 "target='_blank'><i class='fa fa-linkedin-square fa-2x'></i></a>\n"
                "&nbsp;&nbsp;<a href='https://www.flickr.com/photos/cirm' target='_blank'><i\n"
                 "class='fa fa-flickr fa-2x'></i></a>\n"
                "&nbsp;&nbsp;<a href='https://blog.cirm.ca.gov/' target='_blank'><i\n"
                 "class='fa fa-wordpress fa-2x'></i></a>\n"
        "</div>\n"
        "<div class='row'>\n"
            "<p class='centered-text col-md-12'>\n"
                "<a href='http://cirm.ca.gov' target='_blank'><img\n"
                 "src='https://www.cirm.ca.gov/sites/default/files/images/about_cirm/CIRM_Logo_1300px.png'\n"
                 "style='width: 59px; height: 25px; margin-top: -10px;' /></a>\n"
            "</p>\n"
        "</div>\n"
        "<div class='row'>\n"
            "<span class='pull-right' style='padding-top: 20px; padding-bottom: 10px;'></span>\n"
        "</div>\n"
    "</div>\n"
    "</div>\n"
"</div>\n"
"</div>\n"
