//  this should correspond to src/hg/cirm/gateway/htdocs/inc/header.html SSI
"<div class='cirm-banner'></div>\n"
"<div class='container-fluid' style='width: 90%%'>\n"
"  <div class='row'>\n"
"    <a href='../sspsygene.html'><img src='../images/ssPsyGeneLogo.jpg'\n"
"    style='margin-top: 15px; max-width: 450px;'/></a>\n"
"  </div>\n"
"  <div class='row'>\n"
"    <nav class='navbar navbar-expand-lg navbar-light nopadding' style='width: 100%%'>\n"
"      <button class='navbar-toggler' type='button' data-toggle='collapse'\n"
"      data-target='#navbarNavDropdown' aria-controls='navbarNavDropdown'\n"
"      aria-expanded='false' aria-label='Toggle navigation'>\n"
"        <span class='navbar-toggler-icon'></span>\n"
"      </button>\n"
"      <div class='collapse navbar-collapse' id='navbarNavDropdown'>\n"
"        <ul class='navbar-nav mr-auto mt-2 mt-lg-0'>\n"
"          <li class='nav-item back-dark-blue rounded'>\n"
"            <h5 class='nav-button'><a class='nav-link text-white padded-nav-link' href='../sspsygene.html'>Home</a></h5>\n"
"          </li>\n"
"          <li class='nav-item back-dark-pink rounded' style='margin-left: 6px'>\n"
"            <h5 class='nav-button'><a class='nav-link text-white padded-nav-link' href='../cgi-bin/cdwWebBrowse'>Data</a></h5>\n"
"          </li>\n"
"          <li class='nav-item back-dark-blue rounded' style='margin-left: 6px'>\n"
"            <h5 class='nav-button'><a class='nav-link text-white padded-nav-link' href='../help/sspsygeneHelp.html'>Help</a></h5>\n"
"          </li>\n"
"          <li class='nav-item back-gray rounded' style='margin-left: 6px'>\n"
"            <h5 class='nav-button'><a class='nav-link text-white padded-nav-link login' href='../cgi-bin/hgLogin?hgLogin.do.displayLoginPage=1'>\n"
"            Login</a></h5>\n"
"          </li>\n"
"          <li class='nav-item back-gray rounded' style='margin-left: 6px'>\n"
"            <h5 class='nav-button'><a class='nav-link text-white padded-nav-link login' id='logoutLink'\n"
"            href='../cgi-bin/hgLogin?hgLogin.do.displayLogout=1' style='display:none'>\n"
"            Logout</a></h5>\n"
"          </li>\n"
"        </ul>\n"
"      </div>\n"
"    </nav>\n"
"  </div>\n"
"</div>\n"
"<script src='//cdnjs.cloudflare.com/ajax/libs/bowser/1.6.1/bowser.min.js'></script>\n"
"<script src=\"../js/cirmStuff.js\"></script>\n"
