include ../../../../inc/common.mk
include ../../install.mk

# The original JSX source files
JSX_FILES= hgChooseDb.jsx

# The final product after compiling and bundling
BUNDLE_FILE=reactHgChooseDb.js

include ../react.mk

