kentSrc = ../../../..
include ../../../../inc/common.mk

JS_DIR=../..

# The original JSX source files
JSX_FILES= hgChooseDb.jsx

# The final product after compiling and bundling
BUNDLE_FILE=reactHgChooseDb.js

include ${JS_DIR}/install.mk
include ../react.mk
