table viennaVntr
"1000 Genomes Vienna ONT VNTR allele statistics from VAMOS genotyping"
    (
    string chrom;          "Chromosome"
    uint chromStart;       "Start position"
    uint chromEnd;         "End position"
    string name;           "VNTR locus summary"
    uint score;            "Score (0-1000)|Number of unique VNTR alleles, capped at 1000"
    char[1] strand;        "Strand"
    uint thickStart;       "Thick start (same as chromStart)"
    uint thickEnd;         "Thick end (same as chromEnd)"
    uint reserved;         "Item color RGB|by average repeat unit length"
    uint numHaps;          "Haplotypes genotyped|Number of haplotypes where allele has been genotyped"
    float ruLenAvg;        "Avg motif length|Average length of the repeat unit in bp"
    uint numUniqueVntrs;   "Unique alleles|Number of unique VNTR alleles found at the site"
    uint maxRus;           "Max repeat units|Maximum repeat unit count observed"
    uint minRus;           "Min repeat units|Minimum repeat unit count observed"
    float medianRus;       "Median repeat units|Median repeat unit count across all haplotypes"
    float pct25Rus;        "25th pct repeat units|25th percentile of repeat unit counts"
    float pct75Rus;        "75th pct repeat units|75th percentile of repeat unit counts"
    uint uniqueNumRus;     "Unique repeat counts|Count of uniquely observed repeat unit numbers"
    uint maxBps;           "Max allele bp|Maximum allele length in base pairs"
    uint minBps;           "Min allele bp|Minimum allele length in base pairs"
    float medianBps;       "Median allele bp|Median allele length in base pairs"
    float het;             "Expected heterozygosity|1 - sum(p_i^2) computed from allele frequencies across 1,019 samples"
    )
