#!/usr/bin/env python

from optparse import OptionParser
import xml.parsers.expat

class CmdOpts(object):
    usage="""%prog [options] [xmlFile]

    Set that a DAS XML file can be parsed.  Doesn't do any other validation
    """
    def __init__(self):
        parser = OptionParser(usage=CmdOpts.usage)
        (opts, args) = parser.parse_args()
        if len(args) > 1:
            parser.error("wrong number of arguments")
        elif len(args) == 0:
            self.xmlFile = "/dev/stdin"
        else:
            self.xmlFile = args[0]

opts = CmdOpts()

p = xml.parsers.expat.ParserCreate()
fh = file(opts.xmlFile)
p.ParseFile(fh)
fh.close()
