table mavemdVariants
"MaveMD variant effect measurements with ACMG functional evidence"
    (
    string chrom;          "Chromosome"
    uint   chromStart;     "Start position in chromosome"
    uint   chromEnd;       "End position in chromosome"
    string name;           "Gene and amino acid change"
    uint   score;          "Score 0-1000 (ACMG evidence strength)"
    char[1] strand;        "Strand|Transcript strand for codon-projected items; . where the variant was placed from a genomic term"
    uint   thickStart;     "Start of thick display"
    uint   thickEnd;       "End of thick display"
    uint   reserved;       "Item color (RGB)"
    int    blockCount;     "Number of blocks"
    int[blockCount] blockSizes;  "Block sizes"
    int[blockCount] chromStarts; "Block starts relative to chromStart"
    string gene;           "Gene"
    string proteinChange;  "Protein change"
    string acmgOutcome;    "ACMG evidence|Evidence code from the displayed calibration"
    string acmgStrength;   "Evidence strength"
    string funcClass;      "Functional class|Measured effect: normal, abnormal or indeterminate"
    string funcScore;      "Functional score|Assay score, on this score set's own scale"
    string oddsPath;       "OddsPath|Odds of pathogenicity for this functional class"
    string calibration;    "Calibration|The calibration whose call is shown"
    string calibrationSource; "Calibration chosen by|How the displayed calibration was picked"
    string researchUseOnly; "Research use only|Whether the displayed calibration is marked research use only"
    lstring allCalibrations; "All calibrations|Every calibration on this score set and its call"
    string clinvarSig;     "ClinVar significance"
    string clinvarReview;  "ClinVar review status"
    string clinvarRelease; "ClinVar release|Which ClinVar snapshot this classification came from"
    string gnomadAf;       "gnomAD allele frequency"
    string gnomadAc;       "gnomAD allele count"
    string gnomadAn;       "gnomAD allele number"
    string gnomadFaf95;    "gnomAD FAF95|Filtering allele frequency, 95% confidence"
    string gnomadFaf95Ancestry; "gnomAD FAF95 ancestry|Ancestry group giving the filtering allele frequency"
    string gnomadVersion;  "gnomAD version"
    string vepConsequence; "VEP consequence|Empty throughout at present; carried so the track picks up MaveDB's values if they are populated"
    string scoreSet;       "Score set"
    lstring scoreSetTitle; "Score set title"
    string assayMethod;    "Assay method|What the assay measured"
    string assayModel;     "Assay model system"
    lstring assayMechanism; "Molecular mechanism assessed"
    string libraryMethod;  "Variant library method|An in vitro construct library cannot detect effects on splicing or nonsense-mediated decay"
    lstring publication;   "Publication"
    lstring publicationUrl; "Publication link"
    string genomicChange;  "Genomic HGVS"
    string cdnaChange;     "cDNA HGVS"
    string clinGenId;      "ClinGen allele ID|CA = canonical (genomic) allele, PA = protein allele"
    string variantUrn;     "MaveDB variant"
    string placement;      "Placement method|How this variant was placed on the genome"
    )
