table mavemdHeatmap
"MaveMD variant effect maps, one heatmap per score set, colored by clinical evidence"
    (
    string chrom;      "Chromosome"
    uint   chromStart; "Start position in chromosome"
    uint   chromEnd;   "End position in chromosome"
    string name;       "Gene and score set"
    uint   score;      "Score 0-1000 (fraction of measured substitutions with pathogenic evidence)"
    char[1] strand;    "+ or -"
    uint thickStart;   "Same as chromStart"
    uint thickEnd;     "Same as chromEnd"
    uint reserved;     "Unused"
    int blockCount;    "Number of amino acid positions covered (heatmap columns)"
    int[blockCount] blockSizes;  "Block sizes (codon width, clamped to avoid overlap)"
    int[blockCount] chromStarts; "Block starts relative to chromStart"
    int _rowCount;     "Number of heatmap rows"
    string[_rowCount] _labels; "Row labels|Single-letter amino acid codes by class, then * for nonsense"
    lstring _colorBounds; "Comma-separated thresholds for the fallback color spectrum"
    lstring _colorValues; "Comma-separated colors for each threshold"
    lstring _scoreArray;  "Row-major cell colors; empty cell = not measured"
    lstring _labelArray;  "Row-major mouseover labels"
    lstring legend;    "Legend"
    string scoreSet;   "Score set"
    lstring scoreSetTitle; "Score set title"
    string assayMethod;    "Assay method|What the assay measured"
    string assayModel;     "Assay model system"
    lstring assayMechanism; "Molecular mechanism assessed"
    string libraryMethod;  "Variant library method|An in vitro construct library cannot detect effects on splicing or nonsense-mediated decay"
    string gene;       "Gene"
    string calibration; "Calibration|The calibration whose calls color the cells"
    string calibrationSource; "Calibration chosen by|How the displayed calibration was picked"
    string researchUseOnly; "Research use only|Whether that calibration is marked research use only"
    string variantCount; "Variants shown|Measured substitutions drawn in this map"
    lstring publication; "Publication"
    lstring mavedbUrl; "MaveDB record"
    )
