table trexplorer
"TRExplorer tandem repeat catalog loci with population allele frequency data"
    (
    string chrom;              "Chromosome"
    uint chromStart;           "Start position (0-based)"
    uint chromEnd;             "End position"
    string name;               "Repeat motif (truncated to 25 chars if longer)"
    uint score;                "Repeat purity scaled to 0-1000"
    char[1] strand;            "Strand"
    uint thickStart;           "Thick start (same as chromStart)"
    uint thickEnd;             "Thick end (same as chromEnd)"
    uint reserved;             "Item color RGB by motif size"
    lstring locusId;           "Unique locus identifier"
    lstring referenceMotif;    "Full repeat motif in reference orientation"
    lstring canonicalMotif;    "Canonical form of the repeat motif"
    uint motifSize;            "Length of repeat unit in bp"
    uint numRepeats;           "Number of repeat copies in reference"
    float repeatPurity;        "Repeat purity (0-1)"
    uint regionSize;           "Size of repeat region in bp"
    string source;             "Data source catalog"
    string knownDiseaseLocus;  "Known disease-associated locus name, if any"
    string knownDiseaseMotif;  "Known disease-associated motif, if any"
    string geneRegion;         "Gene region annotation (exon, intron, promoter, intergenic)"
    string geneName;           "Gene name"
    lstring tenKAlleleHist;    "TenK10K allele histogram (space-separated size=count pairs)"
    uint tenKNumAlleles;       "TenK10K total number of called alleles"
    lstring hprcAlleleHist;    "HPRC256 allele histogram (space-separated size=count pairs)"
    uint hprcNumAlleles;       "HPRC256 total number of called alleles"
    uint aouNumAlleles;        "AoU1027 total number of called alleles"
    )
