table mpravardb
"MPRA Variant Database - experimentally tested regulatory variants from MPRA studies"
    (
    string chrom;        "Reference sequence chromosome or scaffold"
    uint chromStart;     "Start position in chromosome"
    uint chromEnd;       "End position in chromosome"
    string name;         "Variant name (rsID or chr:pos:ref>alt)"
    uint score;          "Score from 0-1000 based on -log10(pvalue)"
    char[1] strand;      "Strand (always .)"
    uint thickStart;     "Same as chromStart"
    uint thickEnd;       "Same as chromEnd"
    uint reserved;       "itemRgb - color by significance"
    string ref;          "Reference allele"
    string alt;          "Alternate allele"
    string rsid;         "dbSNP rsID"
    string disease;      "Associated disease or trait"
    string cellLine;     "Cell line used in MPRA experiment"
    string description;  "Description of the MPRA experiment"
    float log2FC;        "Log2 fold change (alt vs ref allele activity)"
    float pvalue;        "P-value for allelic difference"
    float fdr;           "False discovery rate"
    string mpraStudy;    "MPRA study citation"
    string _mouseOverLog2FC;  "log2FC rounded to 3 digits for mouseOver"
    string _mouseOverPvalue;  "p-value rounded to 3 digits for mouseOver"
    string _mouseOverFdr;     "FDR rounded to 3 digits for mouseOver"
    )
