all:
	cp updateBrowser.sh /usr/local/apache/htdocs/gbib/updateBrowser.sh
	@echo Now do "'gbibCoreUpdateBeta'" on the browser box and 
	@echo then "'updateBrowser notSelf'" to test the changes to the
	@echo update script.
	@echo
	@echo To get hgwdev alpha CGIs and htdocs:
	@echo '   updateBrowser hgwdev brianlee alpha'
	@echo To get hgwdev beta CGIs and htdocs:
	@echo '   updateBrowser hgwdev brianlee beta'
	@echo and replace brianlee with your username.
