
LIST=\
wgEncodeMapability.ra \
wgEncodeGisDnaPet.ra \
wgEncodeGencode.ra \
wgEncodeCshlShortRnaSeq.ra \
wgEncodeGisRnaSeq.ra \
wgEncodeAffyRnaChip.ra \
wgEncodeUwDgf.ra \
wgEncodeHaibMethylRrbs.ra \

include ../../../../makefile.metaDb

