table g2p
"All panels in the Gene2Phenotype (G2P) database - BED 9+20"
(
    string chrom;        "Reference sequence chromosome or scaffold"
    uint   chromStart;    "Start position of feature on chromosome"
    uint   chromEnd;      "End position of feature on chromosome"
    string name;          "Gene symbol"
    uint   score;         "Score"
    char[1] strand;       "+ or - for strand"
    uint   thickStart;    "Coding region start"
    uint   thickEnd;      "Coding region end"
    uint   itemRGB;       "Color based on confidence (R,G,B values)"

    # ----- 20 additional custom fields -----
    string g2p_id;                           "G2P ID"
    string   gene_mim;                         "Gene MIM ID"
    string   hgnc_id;                          "HGNC ID"
    string previous_gene_symbols;            "List of previous gene symbols"
    lstring disease_name;                     "Disease name"
    string disease_mim;                      "Disease MIM ID"
    string disease_MONDO;                    "MONDO ID"
    string allelic_requirement;              "Number of alleles affected to cause the relevant disease"
    string cross_cutting_modifier;           "Optional cross-cutting modifiers giving extra info"
    string confidence;                       "Likelihood that the gene-disease association is true"
    string variant_consequence;              "SO terms for the variant consequence"
    lstring variant_types;                    "SO terms for variant types"
    string molecular_mechanism;              "Molecular mechanism"
    string molecular_mechanism_categorisation; "Categorisation of the molecular mechanism"
    lstring molecular_mechanism_evidence;     "Evidence to determine the disease mechanism"
    lstring phenotypes;                       "Human phenotype ontology IDs"
    lstring publications;                     "Pubmed IDs"
    string panel;                            "Disease grouping or defined clinical category"
    lstring comments;                         "Comments added by online curators"
    string date_of_last_review;              "Date of last review"
)
