
all::
	cd gmtime && $(MAKE)
	cd mktime && $(MAKE)
	cd localtime && $(MAKE)

compile::
	cd gmtime && $(MAKE) compile
	cd mktime && $(MAKE) compile
	cd localtime && $(MAKE) compile

clean::
	cd gmtime && $(MAKE) clean
	cd mktime && $(MAKE) clean
	cd localtime && $(MAKE) clean

test::
	@echo "# no tests directory in $(CURDIR)"
