all:
	cp ~/public_html/tests/testClusters.html . 
	cp ~/public_html/tests/testClusters.json . 	
	addMetaDataToJson testClusters.json meta.tab testClustersWMeta.json 
	mv testClustersWMeta* ~/public_html/tests
