all:
	cp ~/public_html/tests/testClusters.html . 
	cp ~/public_html/tests/testClusters.json . 	
	addMetaDataToJson testClusters.json testClusters.html meta.tab testClustersWMeta.json testClustersWMeta.html
	mv testClustersWMeta* ~/public_html/tests
