include ../../../../inc/common.mk
include ../../install.mk

# The original JSX source files
JSX_FILES= hgAi.jsx

# The final product after compiling and bundling
BUNDLE_FILE=reactHgAi.js

include ../react.mk

