#!/bin/bash -e
#
# euronode-dbload [-inclEsts] [-extFileUpdate] [-allowLargeDeletes]
#
# dbload for euronode servers.
opts="$*"

# other options to include
otherOpts=""

# initialize
gbRoot=/data2/genbank
cd $gbRoot
. $gbRoot/lib/gbCommon.sh
databases=`gbGetDatabases etc/euronode.dbs`

# workdir is a local dir
workdir=/data2/tmp/genbank

# wait for copy to hgwnfs1
copyTime=var/copy/copy.time

exec $gbRoot/etc/dbload $opts $otherOpts $gbRoot "$databases" $copyTime $workdir
