#!/bin/bash -e

echo not done
exit 1

# Script that runs that download, processing, and alignment of GenBank and
# RefSeq.  This is run by cron daily and is edited to add new genomes
# and assemblies

set -e  # errors terminate

# location of the genbank root (accessible on the cluster)
gbRoot=/cluster/store3/markd/genbank
PATH="$gbRoot/bin:$gbRoot/bin/i386:$PATH"

# download and process
cd $gbRoot
gbDownloadStep
gbProcessStep

# align
date=`date +"%Y.%m.%d"`
workDir="work/align.$date"

hg13ctgs='/scratch/hg/gs.14/build31/trfFa.1204/*.fa.trf'
hg13lift=/cluster/store1/gs.14/build31/jkStuff/liftAll.lft

mm2nibs='/scratch/hg/mm2/chromTrfMixedNib/chr*.nib'
mm2lift=/cluster/store2/mm.2002.02/mm2/jkStuff/liftAll.lft

rn1nibs='/scratch/hg/rn1/chromTrfMixedNib/*.nib'
rn1lift=/cluster/store4/rn1/jkStuff/liftAll.lft 
gbAlignStep -workdir $workDir \
            hg13 "$hg13ctgs" $hg13lift \
            mm2  "$mm2nibs"  $mm2lift \
            rn1  "$rn1nibs"  $rn1lift

echo "genbank build complete"
