#!/bin/bash -e

# Script to copy new processed and aligned from the build server to the this
# server (gbdb server) This polls to determine if an alignment has been done
# since the last time files were downloaded.  Remote file access is by rsync.

set -e  # errors terminate
trap "echo Error: `hostname` copy failed >&2; exit 1" ERR
exec </dev/null

# databases to copy:
databases="hg16 hg17 mm3 mm4 mm5 rn3 fr1 dm1 sacCer1 panTro1 galGal2 ce2 danRer1 danRer2 ci1 canFam1 anoGam1 tetNig1 dp2 xenTro1 apiMel1"

# initialize
gbRoot=/export/genbank
cd $gbRoot
. $gbRoot/lib/gbCommon.sh

# local location of /gbdb
gbdb=/export/gbdb

# location of the genbank root and files on the remote build server
gbBuildServer=eieio
rsyncPort="ssh"
gbBuildRoot=/cluster/data/genbank

# Checking for an existing lock file, Silently exits if lock file exists
# and is less than one day old,  error if older.
gbCheckLock $gbRoot/var/copy/run/copy.lock


gbCopyStep -rsyncPort=$rsyncPort -gbdb=$gbdb $gbBuildServer $gbBuildRoot $databases

# we don't put put a completed message, as gbCopyStep does the checking.
