#!/bin/bash -e
#
# mgc-dbload [-inclEsts] [-extFileUpdate] [-allowLargeDeletes]
#
# dbload for mgc server.
#   - loads all MGC tables (in conf file)
#   - has different databases than other rr.
opts="$*"

# databases to update
databases="hg16 hg17 mm3 mm4 mm5 rn3 fr1 dm1 sacCer1 panTro1 galGal2 ce2 danRer1 ci1 canFam1 anoGam1 tetNig1 dp2 xenTro1"

# gbRoot on hgnfs1
gbRoot=/genbank

# load files copied to hgwnfs1
copyTime=var/copy/copy.time

# workdir is a local dir
workdir=/var/tmp/genbank

# data files and dirs
dbloadVar=var/dbload/`hostname`
copyTime=var/copy/copy.time
lastCopyTime=$dbloadVar/copy.time
lastCopyTimeTmp=$lastCopyTime.tmp
dbloadTime=$dbloadVar/dbload.time

exec $gbRoot/etc/dbload $opts $gbRoot "$databases" $copyTime $workdir
