table webstr
"WebSTR short tandem repeat loci with allele frequency data from EnsembleTR panel"
    (
    string chrom;        "Chromosome"
    uint chromStart;     "Start position"
    uint chromEnd;       "End position"
    string name;         "Repeat ID"
    uint score;          "Score (0-1000)"
    char[1] strand;      "Strand"
    uint thickStart;     "Thick start (same as chromStart)"
    uint thickEnd;       "Thick end (same as chromEnd)"
    uint reserved;       "Item color RGB"
    string motif;        "Repeat unit motif"
    uint period;         "Length of repeat unit"
    uint numCopies;      "Number of repeat copies in reference"
    lstring afrAlleles;  "AFR alleles (comma-separated repeat counts)"
    lstring afrFreqs;    "AFR allele frequencies (comma-separated)"
    uint afrN;           "AFR sample count"
    lstring amrAlleles;  "AMR alleles (comma-separated repeat counts)"
    lstring amrFreqs;    "AMR allele frequencies (comma-separated)"
    uint amrN;           "AMR sample count"
    lstring easAlleles;  "EAS alleles (comma-separated repeat counts)"
    lstring easFreqs;    "EAS allele frequencies (comma-separated)"
    uint easN;           "EAS sample count"
    lstring eurAlleles;  "EUR alleles (comma-separated repeat counts)"
    lstring eurFreqs;    "EUR allele frequencies (comma-separated)"
    uint eurN;           "EUR sample count"
    lstring sasAlleles;  "SAS alleles (comma-separated repeat counts)"
    lstring sasFreqs;    "SAS allele frequencies (comma-separated)"
    uint sasN;           "SAS sample count"
    )
