table webstr
"WebSTR short tandem repeat loci with allele frequency data from EnsembleTR panel"
    (
    string chrom;        "Chromosome"
    uint chromStart;     "Start position"
    uint chromEnd;       "End position"
    string name;         "Repeat motif x copy count"
    uint score;          "Score (0-1000)"
    char[1] strand;      "Strand"
    uint thickStart;     "Thick start (same as chromStart)"
    uint thickEnd;       "Thick end (same as chromEnd)"
    uint reserved;       "Item color RGB|by heterozygosity: light gray (het=0), dark blue (<0.1), medium blue (0.1-0.3), light purple (0.3-0.5), salmon (0.5-0.7), dark red (>=0.7), medium gray (no data)"
    string motif;        "Repeat unit motif"
    uint period;         "Length of repeat unit"
    uint numCopies;      "Number of repeat copies in reference"
    string repeatId;     "WebSTR repeat identifier"
    float het;           "Expected heterozygosity|1 - sum(p_i^2) pooled across all 1000 Genomes populations"
    lstring afrHist;     "AFR allele frequency histogram (space-separated allele=freq pairs)"
    uint afrN;           "AFR sample count"
    lstring amrHist;     "AMR allele frequency histogram (space-separated allele=freq pairs)"
    uint amrN;           "AMR sample count"
    lstring easHist;     "EAS allele frequency histogram (space-separated allele=freq pairs)"
    uint easN;           "EAS sample count"
    lstring eurHist;     "EUR allele frequency histogram (space-separated allele=freq pairs)"
    uint eurN;           "EUR sample count"
    lstring sasHist;     "SAS allele frequency histogram (space-separated allele=freq pairs)"
    uint sasN;           "SAS sample count"
    )
