table mgcLibrary
"table of libraries"
    (
    int id_lib;             "NCBI assigned id"
    string flc_id;          "library name assigned by CGAP"
    string id_rna;          "rna sample used to make library"
    int id_vendor;          "id of vendor"
    int id_method;          "lib prep method id"
    byte normal;            "is library normalized"
    lstring commnt;         "comments about library success or failure"
    float rate_success;     "% success"
    float human_repeats;   "% Human repetitive elements"
    float mito_rna;         "% mitochondrial contamination"
    float ecoli;            "% bacterial contamination"
    float yeast;            "% yeast contamination"
    float mouse;            "% mouse contamination"
    float diversity;        "library diversity"
    float uniqueness;       "library uniqueness"
    int genes;              "number of genes in library"
    int discover;           "number of genes discovered"
    int flc_disc;           "number of genes discovered within FLC"
    int novel;              "number of novel genes discovered"
    float future;           "% probability of finding new genes in lib"
    float internal_primed;  "% internal priming"
    float full_length;      "% full length"
    float priority;         "priority score for going forward"
    int id_unigene;         "unigene library id"
    string organism;        "organism name"
    string vector;          "vector name"
    string host;            "host name"
    float vec_contam;       "% vector contamination"
    float mean_insize;      "mean insert size"
    string linker;          "linker sequence"
    )
