#!/bin/sh -e
# Updates hubSearchText table, run by cron for auto-push

date >> /hive/groups/browser/hubCrawl/hubSearchText.log
cd /hive/groups/browser/hubCrawl
nohup ./doPublicCrawl &> /dev/null #Send stdout & stderr to /dev/null
echo "HubSearchText Dev cron-updated on `date`. Exit status: $?" >> /hive/groups/browser/hubCrawl/hubSearchText.log 
#Return exit status of prev command, 0 = no issue
