table ccdsAccessions
"parses NcbiHinxtonAllAccessions.txt from NCBI"
    (
    int tax_id;                "taxon id"
    string chromosome;         "chromosome accession.version"
    int gene_id;               "gene id"
    string group_id;           "group id.version"
    string ccds;               "ccds1.1"
    string group_ccds_status;  "status of CCDS"
    string ncbi_mrna;          "acc.version"
    string ncbi_prot;          "acc.version"
    string hinxton_mrna;       "ensemble id"
    string hinxton_prot;       "ensemble id"
    string ncbi_mrna_non;      "when non-ccds"
    string ncbi_prot_non;      "when non-ccds"
    string hinxton_mrna_non;   "when non-ccds"
    string hinxton_prot_non;   "when non-ccds"
    char[1] cds_strand;        "+ or -"
    int cds_from;              "in 0-based chromosome coordinates "
    int cds_to;                "in 0-based chromosome coordinates"
    string cds_loc;            "comma separated list of from-to, in 0-based chromosome coordinates, for all exons"
    )
