#!/bin/tcsh -efx
encodeExpToCvDb experiment.tab series.tab result.tab both.django 
hgLoadSqlTab kentDjangoTest cvDb_experiment experiment.sql experiment.tab
hgLoadSqlTab kentDjangoTest cvDb_series series.sql series.tab
hgLoadSqlTab kentDjangoTest cvDb_result result.sql result.tab
