RUNDIR=/hive/data/outside/otto/nextstrainNcov
install: 
	# pylint -E nextstrain.py
	cp nextstrain.py nextstrainClade.as doUpdate.sh ${RUNDIR}/
clean:
	rm -f *.bed *.nh *.vcf *.bb *.gz *.tbi *.bedGraph *.varPaths
