table methaDory
"DNA methylation episignature CpG probes collected by MethaDory"
    (
    string chrom;       "Reference sequence chromosome or scaffold"
    uint chromStart;    "Start position in chromosome"
    uint chromEnd;      "End position in chromosome"
    string name;        "Illumina probe ID"
    uint score;         "Number of episignatures, capped at 1000"
    char[1] strand;     "Not applicable, always ."
    uint thickStart;    "Start of where display should be thick"
    uint thickEnd;      "End of where display should be thick"
    uint reserved;      "Colour by direction of the methylation change"
    int sigCount;       "Episignatures|Number of episignatures that report this probe"
    lstring disorders;  "Disorders|One per episignature, in the order below. A semicolon inside a name separates alternative names of the same disorder"
    lstring signatures; "Episignatures|Gene or locus, then the first author and year of the study that derived the signature"
    lstring loci;       "Genes and loci|Gene or genomic region of each episignature"
    lstring deltaBetas; "Methylation difference|Delta-beta, the mean methylation in affected individuals minus the mean in controls, for each episignature"
    lstring pvalues;    "Adjusted p-values|Adjusted p-value reported for each episignature, NA when the study did not report one"
    lstring studies;    "Studies|First author and year of each study"
    lstring publications; "Publications|PubMed entry of each study"
    string direction;   "Direction and strength|Direction and size of the strongest effect at this probe, or Conflicting when a signature of comparable size points the other way"
    float maxAbsDelta;  "Largest effect|Largest absolute delta-beta over the episignatures at this probe"
    string arraySource; "Array manifest|Illumina array manifest that provided the position of this probe"
    lstring disorderSummary; "Disorder summary|The first few disorders, for the mouseover"
    lstring _jsonSignatures; "Episignature table|JSON rendered as a table by detailsDynamicTable, so the per-signature values line up in rows"
    )
