include ../inc/common.mk

all:
	cd itsaDump && ${MAKE}
	cd itsaFind && ${MAKE}
	cd itsaMake && ${MAKE}
	cd shortRepeatFind && ${MAKE}
	cd shortRepeatMerge && ${MAKE}
	cd splat && ${MAKE}
	cd splatMerge && ${MAKE}
	cd splatTestSet && ${MAKE}
	cd splixMake && ${MAKE}
	cd sufaFind && ${MAKE}
	cd sufaMake && ${MAKE}
	cd sufaRepeatFind && ${MAKE}
	cd sufxDump && ${MAKE}
	cd sufxFind && ${MAKE}
	cd sufxMake && ${MAKE}

