include ../inc/common.mk

all:
	cd bfastMafFix && ${MAKE}
	cd elandToSplat && ${MAKE}
	cd i16Find && ${MAKE}
	cd itsaDump && ${MAKE}
	cd itsaFind && ${MAKE}
	cd itsaMake && ${MAKE}
	cd shortRepeatFind && ${MAKE}
	cd shortRepeatMerge && ${MAKE}
	cd splat && ${MAKE}
	cd splatCheck1 && ${MAKE}
	cd splatCheck2 && ${MAKE}
	cd splatMerge && ${MAKE}
	cd splatTestSet && ${MAKE}
	cd splatToEland && ${MAKE}
	cd splixMake && ${MAKE}
	cd sufaFind && ${MAKE}
	cd sufaMake && ${MAKE}
	cd sufaRepeatFind && ${MAKE}
	cd sufxDump && ${MAKE}
	cd sufxFind && ${MAKE}
	cd sufxMake && ${MAKE}
