#!/bin/csh -efx
echo building...
source ../javaenv
javac ChromInfo.java
javac ChromLibrary.java
javac DBInfo.java
javac KnownGene.java
javac Position.java
javac PositionIterator.java
javac TrackContainer.java
javac TrackDb.java
# javac HGDBLibrary.java
javac QADBLibrary.java
javac QAWebLibrary.java
# javac TrackCheck.java
javac QALibrary.java
echo done building
