include ../java.mk

CLASS = CartSettings.class ChromInfo.class ChromLibrary.class \
	HGDBInfo.class HGDBInfoTest.class KnownGene.class \
	Position.class PositionIterator.class TestTarget.class \
	TrackContainer.class  TrackControl.class TrackDb.class \
	QADBLibrary.class HgTracks.class QALibrary.class

all: ${CLASS}
	@echo done lib

clean:
	rm *.class

