include ../java.mk

CLASS = CartSettings.class ChromInfo.class ChromLibrary.class \
	HgConf.class HGDBInfo.class HGDBInfoTest.class \
	KnownGene.class Metadata.class \
	Position.class PositionIterator.class Robot.class \
	TestTarget.class \
	TrackContainer.class  TrackControl.class TrackDb.class \
	QADBLibrary.class QALibrary.class \
	HgNear.class HgTracks.class 

all: ${CLASS}
	@echo done lib

clean:
	rm *.class

