#!/bin/bash -e
#
# gbAlignRSync iserver workdir iserverdir
#
# rsync file to align to an iserver.  This filters the output to add the
# hostname to each line, so it's obvious which host a message came
# from if multiple are being run at the same time.  This will result
# in a directory with basename workdir in iserverdir.
#
# requires ssh being configured to use authorization without a password
# 
set -e

if [ $# -ne 3 ] ; then
    echo "wrong # args: gbAlignRSync iserver workdir iserverdir" >&2
    exit 1
fi
iserver=$1
workdir=$2
iserverdir=$3

# make sure we don't have a trailing slash on the workdir, or this
# will tell rsync to copy the contents of the directory.

workdir=`echo $workdir | sed 's|/*$||'`

# need last two directories:  rest/work2/work1
work2=`basename \`dirname $workdir\``
work1=`basename $workdir`

destdir="$iserverdir/$work2"

# prevent rsh problems with reading stdin
exec </dev/null

# use archive mode to preserve permissions and recursion
(
  ssh -x $iserver mkdir -p $destdir 2>&1 &&\
  rsync --rsh="ssh -x" --delete --archive --checksum \
      --exclude=align.jobs --exclude=align.expected \
      $workdir ${iserver}:$destdir  2>&1
) | awk -v host=$iserver '{print host ": " $0}'

if [ ${PIPESTATUS[0]} != 0 -o  ${PIPESTATUS[1]} != 0 ] ; then
   exit 1
fi
exit 0

