#!/bin/sh -e
# invoke version of python compiled for genbank use.  Needed until we
# get 2.4 installed on systems.


arch=`uname -m`
rtdir="/cluster/data/genbank/runtime/$arch"
LD_LIBRARY_PATH="$rtdir/lib:${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH
exec $rtdir/bin/python "$@"
