table gnomadExomesV4_1_1
"gnomAD v4.1.1 exomes variant data"
    (
    string chrom;      "Chromosome (or contig, scaffold, etc.)"
    uint   chromStart; "Start position in chromosome"
    uint   chromEnd;   "End position in chromosome"
    string name;       "md5 of data used as a key into external data file"
    uint   score;      "Score from 0-1000"
    char[1] strand;    "+ or -"
    uint thickStart;   "Start of where display should be thick (start codon)"
    uint thickEnd;     "End of where display should be thick (stop codon)"
    uint reserved;     "Used as itemRgb as of 2004-11-22"
    lstring ref; "Reference Sequence"
    lstring alt; "Alternate Sequence"
    string FILTER; "FILTER tags from VCF"
    string AC; "Allele Count"
    string AN; "Allele Number"
    string AF; "Allele Frequency"
    string faf95; "Filtering allele frequency (using Poisson 95% CI) for samples"
    string nhomalt; "Count of homozygous individuals in samples"
    string rsId; "dbSnp rsID"
    lstring genes; "List of genes affected by variant"
    string annot; "Annotation type: pLoF, missense, synonymous, or other"
    lstring variation_type; "Variant type(s)"
    uint _startPos; "Unshifted chromStart position from VCF for link outs"
    string _displayName; "gnomAD display name"
    string grpmax; "Genetic ancestry group with the maximum allele frequency"
    string AC_grpmax; "Allele count of the grpmax"
    string AN_grpmax; "Total number of alleles in the grpmax"
    string AF_grpmax; "Maximum allele frequency across genetic ancestry groups"
    string nhomaltX; "Count of homozygous individuals in XX samples, chrX and chrY only"
    string nhemi; "Count of hemizygous individuals, chrX and chrY only"
    bigInt _dataOffset; "Offset into gnomad.v4.1.1.exomes.details.tab.gz for line with more info"
    int _dataLen; "Length of the line in gnomad.v4.1.1.exomes.details.tab.gz"
    )
