table orphadata
"Aggregated Phenotype, Epidemiological, and Rare Disease Gene Relationships from Orphanet"
(
string	chrom;		"Reference sequence chromosome or scaffold"
uint	chromStart;	"Start position of feature on chromosome"
uint 	chromEnd;	"End position of feataure on chromosome"
string	name;		"Name of disorder"
uint	score;		"Score"
char[1]	strand;		"Strand"
uint 	thickStart;	"Coding region start"
uint 	thickEnd;	"Coding region end"
uint	itemRgb;	"Color"
string	disorder;	"Name of disorder"
string	geneSymbol;	"Gene symbol"
string	geneName;	"Gene name"
string	ensemblID;	"Ensembl ID"
string	geneType;	"Gene type"
string	geneLocus;	"Gene locus"
string	assnStatus;	"Association status"
string	assnType;	"Association type"
string	pmid;		"PMID(s)"
string 	orphaCode;	"OrphaCode"
string	omim;		"OMIM ID"
string	hgnc;		"HGNC ID"
string	inheritance;	"Inheritance(s)"
string	onsetList;	"Onset list"
string	deathList;	"Death list"
string	prevalences;	"Prevalence(s)"
lstring	veryFreqPhen;	"Very frequent phenotype(s)"
lstring	freqPhen;	"Frequent phenotype(s)"
lstring	occasPhen;	"Occasional phenotype(s)"
lstring	rarePhen;	"Rare phenotype(s)"
)
