
## makefile definitions for the 'brc' assembly hub

destDir=/hive/data/genomes/asmHubs/BRC
srcDir=${HOME}/kent/src/hg/makeDb/doc/brcAsmHub
orderList=$(CURDIR)/brc.orderList.tsv

indexName=index
testIndexName=testIndex
statsName=asmStats
testStatsName=testAsmStats
dataName=trackData
testDataName=testTrackData
genomesTxt=genomes
hubFile=hub
testHubFile=testHub
hubTxtFile=hub.txt

# these names trigger special behavior in the index page creation scripts:
Name=BRC
name=BRC

# African malaria mosquito (PEST 2006)
defaultAssembly=GCF_000005575.2_AgamP3

include ../asmHubs/asmHubs.mk
