
LIST=\
wgEncodeLicrHistone.ra \
wgEncodeLicrRnaSeq.ra \
wgEncodeLicrTfbs.ra \
wgEncodeSydhHist.ra \
wgEncodeSydhTfbs.ra \
wgEncodeUwDnase.ra \
wgEncodeCaltechTfbs.ra \
wgEncodeCaltechHist.ra \


include ../../../../makefile.metaDb
