#!/bin/bash -e
#run create attribute files with results of gene-check and load database tables
[ $# != 5 ] && echo "usage: geneCheckAndLoad db twoBitOrNib genePred.gp checkTable checkDetails " >&2 && exit 1;
db=$1
nib=$2
table=$3
checkTable=$4
detailsTable=$5
set -x
~markd/bin/${MACHTYPE}/gene-check -compat -genome-seqs $nib -ok-genepred-out ${table}.filter.gp -details-out ${detailsTable}.tmp ${table} ${checkTable}.tmp 
tail +3 ${checkTable}.tmp > check.tmp
mv check.tmp ${checkTable}.tmp
tail +3 ${detailsTable}.tmp > detail.tmp
mv detail.tmp ${detailsTable}.tmp
hgLoadSqlTab $db $detailsTable $HOME/kent/src/hg/lib/geneCheckDetails.sql ${detailsTable}.tmp 
hgLoadSqlTab $db $checkTable  $HOME/kent/src/hg/lib/geneCheck.sql ${checkTable}.tmp 
