#!/bin/bash -e
# loadEnsembl - load tab files created by exportEnsembl into browser database.
[ $# != 4 ] && echo "usage: loadEnsembl input-directory db " >&2 && exit 1;
indir=$1
db=$2
cd $indir
ldHgGene $db ensGene -predTab ensGene.gp -gtf -genePredExt 
ldHgGene $db ensPseudo -predTab ensPseudo.gp -gtf -genePredExt 
hgLoadSqlTab $db ensInfo $HOME/kent/src/hg/lib/ensInfo.sql ensInfo.tab
hgLoadSqlTab $db ensGtp $HOME/kent/src/hg/lib/ensGtp.sql ensGtp.tab
hgLoadSqlTab $db ensGeneXref $HOME/kent/src/hg/lib/ensGeneXref.sql ensGeneXref.tab
tawk '{print $4,$6}' ensInfo.tab |sort |uniq --count|sort -nr
cleanGeneTable $db ensGene
cleanGeneTable $db ensPseudo

