#!/bin/bash -e
# loadEnsembl - load tab files created by exportEnsembl into browser database.
[ $# != 2 ] && echo "usage: loadEnsembl input-directory db " >&2 && exit 1;
set -x
indir=$1
db=$2
cd $indir
#remove haplotype annotations until we figure out the offset
tawk '$2!~/hap/{print $0}' ensGene.gp > ensGene.nohap.gp
mv ensGene.nohap.gp ensGene.gp
tawk '$2!~/hap/{print $0}' ensPseudo.gp > ensPseudo.nohap.gp
mv ensPseudo.nohap.gp ensPseudo.gp
hgsql $db -e "drop table if exists ensGene"
ldHgGene $db ensGene -predTab ensGene.gp -gtf -genePredExt -bin
hgsql $db -e "drop table if exists ensPseudo"
ldHgGene $db ensPseudo -predTab ensPseudo.gp -gtf -genePredExt -bin
hgsql $db -e "drop table if exists ensInfo"
hgLoadSqlTab $db ensInfo $HOME/kent/src/hg/lib/ensInfo.sql ensInfo.tab
hgsql $db -e "drop table if exists ensGtp"
hgLoadSqlTab $db ensGtp $HOME/kent/src/hg/lib/ensGtp.sql ensGtp.tab
hgsql $db -e "drop table if exists ensGeneXref"
hgLoadSqlTab $db ensGeneXref $HOME/kent/src/hg/lib/ensGeneXref.sql ensGeneXref.tab
hgsql $db -e "drop table if exists ensemblXref3"
tawk '{print $4,$6}' ensInfo.tab |sort |uniq --count|sort -nr
