#!/usr/bin/perl

$id = 0;
$chr = 0;
$type = 0;
$start = 0;
$end = 0;

<>; #remove header
<>; #remove blank line

while (<>)
{
    if (/^(\d+)\s+(\w+)\s+(\w+)\/(\d+)/)
    {
	$id    = $1;
	$type  = $2;
	$chr   = $3;
	$start = $4 - 1;
	$end   = $4;
	if ($chr eq "MT") { $chr="M"; }
	print "chr$chr\t$start\t$end\trs$id\t$type\tSNP\n" unless ($chr eq "Un");
    }
    else
    {
      die "\n\n\tNOPE: try again\n$_\n";
    }
}
