kentSrc = ../../..
A = hgWormLinks
include $(kentSrc)/inc/userApp.mk

test::
	cd /cluster/data/ce1/bed/steinHelp && hgWormLinks spWp.ace seqPepDesc.ace wbConcise.txt wbGeneClass.txt ../orfToGene/orfToGene sangerLinks.txt
