#!/bin/tcsh -ef
hgsql -e "drop database visiTest; create database visiTest" mysql
hgsql visiTest < ~/kent/src/hg/visiGene/visiGene.sql
visiGeneLoad -database=visiTest test/paulGrayWhole.ra test/paulGrayWhole.tab -verbose=2
visiGeneLoad -database=visiTest test/slices.ra test/slices.tab -verbose=2
visiGeneLoad -database=visiTest test/abTest.ra test/abTest.tab -verbose=2
