table m6aAtlas
"m6A-Atlas v2.0 high-confidence m6A sites with cell-line and technique support"
(
string  chrom;          "Reference sequence chromosome or scaffold"
uint    chromStart;     "Start position of feature on chromosome"
uint    chromEnd;       "End position of feature on chromosome"
string  name;           "m6A-Atlas site ID"
uint    score;          "Score (0-1000) scaled from number of supporting techniques and cell lines"
char[1] strand;         "+ or -"
uint    thickStart;     "Coding region start"
uint    thickEnd;       "Coding region end"
uint    reserved;       "RGB color value used by browser"
string  region;         "Genomic region annotation (Exon, 3'UTR/Exon, 5'UTR/Exon, Intron, Intergenic, etc.)"
string  geneName;       "HGNC/Ensembl gene symbol"
string  geneBiotype;    "Ensembl gene biotype (protein_coding, lncRNA, etc.)"
string  ensemblId;      "Ensembl gene ID"
uint    nTechniques;    "Number of distinct detection techniques supporting this site"
string  techniques;     "Comma-separated list of detection techniques"
uint    nCellLines;     "Number of distinct cell lines / tissues supporting this site"
lstring cellLines;      "Comma-separated list of cell lines or tissues"
uint    rbpNum;         "Number of overlapping RBP binding sites in m6A-Atlas annotations"
uint    miRNANum;       "Number of overlapping miRNA targets"
uint    splicingSiteNum;"Number of nearby splicing sites"
uint    snpNum;         "Number of nearby SNPs"
lstring evidence;       "Per-study evidence: GSE;technique;species;cellLine;treatment, separated by | "
string  geneSource;     "Gene model source (e.g. ensembl_havana, havana)"
string  detailUrl;      "Link to m6A-Atlas detail page for this site"
)
