>contig_26669 (forward), chromosome 1, physical start about 4330461 bases, genetic position at about 4.4 cM (MGSC_2002April11_V3)
1:(-4854,10450106)<483,467>98
NNNTTTATTCGCATTTGTTTAATGCTGAATTTATTCCCATGTCACAAGTTTTT-TCCCTTCAATTTCTTC
   |||| | |||||| ||  ||||||| |||||||||||| ||||||||||| |  ||||| |||||||
TATTTTAATTGCATTTATTGTATGCTGAGTTTATTCCCATGCCACAAGTTTTTGTTTCTTCAGTTTCTTC

TAGGATATCCTTTTCTCTGTTGTGTTCTCCTTTCATGACCCTGGGATATTTTCCTTTTCAGTGAGGATCA
|  | ||   |||||     ||     ||||  | || |   || | |  |  |||| | |||||||||
T--GGTACAGTTTTCCTCTGTGCAACTTCCTCACCTGGCTTGGGAACAAGTGTCTTTACCGTGAGGATCG

TTTCTCCATGTGGCAGGAGCTTGTGTACAGGGTAACATGACCATGGGCTCTTTAAGCTCAGTGCCACATC
  |||| ||||| | ||      ||||  |   |||  |||||   || ||  |||  |     | ||||
--TCTCAATGTGACGGGGCGCCCTGTATGGATGAACCCGACCACCAGCCCTGGAAGTCCCACAGCGCATC

TTATGTGCTTTGTTCACATGGCTATTTCAATGACTAGAGAATCCTCATGTAAACCCTTAAGTTCAGCATT
 |  |||||                  |||  || |||||  |  ||| || ||||| |  |||||  |
CTGGGTGCT------------------CAAACACCAGAGAGCCTACATCTACACCCTCACATTCAGTGTG

ACTCTCTGTATTTTTA-GCAAGTGCAGCAAAACTTCACAGCACTTTTTGCGTCCCTGGCCCTGTATCCCG
||||||   |||||||     ||||||||||| ||||  || ||||| | ||| |   |||||| ||| |
ACTCTCCACATTTTTAATTGTGTGCAGCAAAAATTCAGCGCTCTTTTCGGGTCACCAACCCTGTGTCCAG

C---TGTATTTGGATTGGGCACACCTACATGCTCTACTGCTGTACTGTCAAG-TGGCATATTTTGCTTCT
|     | |||||  | || |||||| |  |||| ||  |||    |||    |||||||   || ||||
CCCCACTGTTTGGCCTAGGTACACCTGCCAGCTCCACCCCTGCCAAGTCGGAATGGCATACACTGTTTCT

TTAAAGAGAAATCATTCAGATATTTGGCTGCCATTTAGATATGTATACCCTTAATGGCCTGGGCAGTTT
 ||||| ||  || |||||| | ||||   |   | |  |||| |||||||| ||||||||||||||||
ATAAAGGGACGTCTTTCAGACACTTGGTGACTTCTCACGTATGCATACCCTTGATGGCCTGGGCAGTTT

