
LIST=\
wgEncodeCaltechHist.ra \
wgEncodeCaltechTfbs.ra \
wgEncodeLicrHistone.ra \
wgEncodeLicrRnaSeq.ra \
wgEncodeLicrTfbs.ra \
wgEncodePsuTfbs.ra \
wgEncodeSydhHist.ra \
wgEncodeSydhTfbs.ra \
wgEncodeUwDnase.ra \

include ../../../../makefile.metaDb
