
all::
	@echo "ERROR: obsolete utility hg/hgText/"

my::
	@echo "ERROR: obsolete utility hg/hgText/"

alpha::
	@echo "ERROR: obsolete utility hg/hgText/"

beta::
	@echo "ERROR: obsolete utility hg/hgText/"

strip::
	@echo "ERROR: obsolete utility hg/hgText/"

install::
	@echo "ERROR: obsolete utility hg/hgText/"

debug::
	@echo "ERROR: obsolete utility hg/hgText/"

lib::
	@echo "ERROR: obsolete utility hg/hgText/"

clean::
	@echo "ERROR: obsolete utility hg/hgText/"

tags::
	@echo "ERROR: obsolete utility hg/hgText/"

compile:
	@echo "ERROR: obsolete utility hg/hgText/"
